### ISSUE TITLE
Is there anyway to have a fully configured MacOS container with ssh without using any graphical interface (no vnc)?

### ISSUE THREAD

**Issue by UliPrantz** [sickcodes/Docker-OSX#104]
I just need a fully configured MacOS container for CI/CD is there anyway to get a container without going through the setup process in which I assume I need a vnc connection? 
In other words is there a way to programmatically setup the container from the beginning? I read through the README.md and think even if I build it myself I need to connect to a vnc server once and go through the initial setup process, is it right? Would there be any way how to automate this process?

**Comment by L-U-C-K-Y** [comment]
Check this issue, is this helping: https://github.com/sickcodes/Docker-OSX/issues/83

**Comment by UliPrantz** [comment]
Not really I think. They consider to use the vnc version to setup the container and once it's setup they auto boot into it. But I also want this initial setup to be automated. Am I missing something? The documentation is a little bit too hard for somebody that has not much experience with virtualization, sorry.

**Comment by MrBenFTW** [comment]
You can setup the container and then commit it. 

Then in the future run it from your commit and it will be pre set up

**Comment by sickcodes** [comment]
> Not really I think. They consider to use the vnc version to setup the container and once it's setup they auto boot into it. But I also want this initial setup to be automated. Am I missing something? The documentation is a little bit too hard for somebody that has not much experience with virtualization, sorry.

Can't automate it, as you have to accept Apple's End User License Agreement.

**Comment by weskerfoot** [comment]
I did the following:

1. Enable sshd automatically (had to use a plist file for this)
2. `docker commit` the image
3. Call `docker run` with `-e EXTRA="-monitor telnet::45454,server,nowait -nographic -serial null`

and it works

**Comment by sickcodes** [comment]
@weskerfoot great work. Do you want to submit a PR? You can add a CI/CD Solution heading to the readme if you'd like.

😎 Make sure to write "host it privately"!

As a committed image has a ton of private information ❤️

**Comment by sickcodes** [comment]
The full installation automation can be done with xdotool auto-clicking but I don't encourage anyone to spend any time doing that as it's not an ideal solution.

By far the best way is to do exactly what @weskerfoot has done, `docker commit` your image when it's ready for spinning up and spinning down, as well as duplicating.

Mind your keys in the image!

**Comment by weskerfoot** [comment]
@sickcodes 

Yes, definitely make sure to use a private registry. I am using AWS ECR for this.

Also, yeah I can make a PR. Do you want me to do it as a separate entrypoint script? The plist file for starting up sshd would have to be created manually after you've installed OSX obviously. It basically amounts to using LaunchDaemon to run `sudo systemsetup -setremotelogin on` in a script at boot.

**Comment by sickcodes** [comment]
Added https://github.com/sickcodes/Docker-OSX/commit/27d7496a70665ac0ead1aaf50a6417ab9dc5135c

CTRL F the README for `OSX_COMMANDS`
