### ISSUE TITLE
Unable to init server.   gtk initialization failed

### ISSUE THREAD

**Issue by rcg12387** [sickcodes/Docker-OSX#106]
Hi. I cannot run this docker image though [run with allowing SSH into OSX](https://github.com/sickcodes/Docker-OSX#run-but-allow-ssh-into-osx).
os: Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-52-generic x86_64)
RAM: 64GB
cpu model name: Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
count of cpus: 20
remote: using MobaXterm Professional Edition v10.7

```
$ sudo docker run --device /dev/kvm --device /dev/snd -e RAM=16 -p 50922:10022 -v /tmp/.X11-unix:/tmp/.X11-unix -e "DISPLAY=${DISPLAY:-:0.0}" sickcodes/docker-osx:latest
ssh-keygen: generating new host keys: RSA DSA ECDSA ED25519
Unable to init server: Could not connect: Connection refused
QEMU 5.1.0 monitor - type 'help' for more information
(qemu) ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
alsa: Could not initialize DAC
alsa: Failed to open `default':
alsa: Reason: No such file or directory
ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
alsa: Could not initialize DAC
alsa: Failed to open `default':
alsa: Reason: No such file or directory
audio: Failed to create voice `dac'
ALSA lib pcm_dsnoop.c:638:(snd_pcm_dsnoop_open) unable to open slave
alsa: Could not initialize ADC
alsa: Failed to open `default':
alsa: Reason: No such file or directory
ALSA lib pcm_dsnoop.c:638:(snd_pcm_dsnoop_open) unable to open slave
alsa: Could not initialize ADC
alsa: Failed to open `default':
alsa: Reason: No such file or directory
audio: Failed to create voice `adc'
gtk initialization failed
```
```
$ echo $DISPLAY
localhost:12.0
```
```
$ echo $TERM
xterm
```
```
$ pgrep -a X
2763 /usr/bin/Xwayland :1024 -rootless -terminate -accessx -core -listen 4 -listen 5 -displayfd 6
```
```
$ egrep -c '(svm|vmx)' /proc/cpuinfo
20
```
```
$ sudo dokerd
sudo: dokerd: command not found
```
```
$ sudo systemctl enable docker
Synchronizing state of docker.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable docker
```
Tried this but also failed:
```
$ sudo apt install x11-xserver-utils
$ xhost +
$ sudo docker run --privileged -e "DISPLAY=${DISPLAY:-:0.0}" -v /tmp/.X11-unix:/tmp/.X11-unix sickcodes/docker-osx ./OpenCore-Boot.sh
Unable to init server: Could not connect: Connection refused
Could not access KVM kernel module: Permission denied
qemu-system-x86_64: failed to initialize kvm: Permission denied
```
Please help me.

**Comment by sickcodes** [comment]
Try changing display to :12.0

`-e "DISPLAY=12.0"`

Remove sudo from docker run and add yourself to the Docker group

`sudo chmod 666 /dev/kvm `

Remove opencoreboot from the end

Remove `--device /dev/snd`

**Comment by BridgetNichols** [comment]
I'm having the exact same issue. Their was an issue posted yesterday that was having the same output too. I've tried everything posted so far and haven't had any luck either.

**Comment by rcg12387** [comment]
> Try changing display to :12.0
> 
> `-e "DISPLAY=12.0"`
> 
> Remove sudo from docker run and add yourself to the Docker group
> 
> `sudo chmod 666 /dev/kvm `
> 
> Remove opencoreboot from the end
> 
> Remove `--device /dev/snd`

@sickcodes Thank you for your reply. I have tried your recommendations but also failed.
```
$ sudo usermod -aG docker "DL-001"
$ sudo chmod 666 /dev/kvm
$ docker run --device /dev/kvm -e RAM=16 -p 50922:10022 -v /tmp/.X11-unix:/tmp/.X11-unix -e "DISPLAY=12.0" sickcodes/docker-osx:latest
docker: unknown server OS: .
See 'docker run --help'.
```

**Comment by sickcodes** [comment]
I just tested using the code from the readme:

```bash
docker run \
    --device /dev/kvm \
    --device /dev/snd \
    -e RAM=4 \
    -p 50922:10022 \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    sickcodes/docker-osx:latest 
```

![Screenshot](https://user-images.githubusercontent.com/65906298/99045513-5f9ffd80-2589-11eb-8acb-4ea345687a28.png)

**Comment by rcg12387** [comment]
Thank you for your reply.
It still fails. I have tried ["How to Install macOS VM on Linux"](https://sick.codes/how-to-install-macos-virtual-machine-on-linux-arch-manjaro-catalina-mojave-or-high-sierra-xcode-working/) and it seems working. Awesome.

**Comment by sickcodes** [comment]
> Thank you for your reply.
> It still fails. I have tried ["How to Install macOS VM on Linux"](https://sick.codes/how-to-install-macos-virtual-machine-on-linux-arch-manjaro-catalina-mojave-or-high-sierra-xcode-working/) and it seems working. Awesome.

Haha great :P That was the original version!

**Comment by rcg12387** [comment]
@sickcodes I have a problem with mouse moving. Two cursors are appeared in the screen (one is of QEMU, another one is of MacOS, I think), and these two are not synchronized. Do you have any suggestion?
This issue is not appropriate to this git repo, anyway please help me.

**Comment by sickcodes** [comment]
One mouse should be for the host the other mouse should be the macs mouse cursor.

Dont zoom in or out as it will change the cursor calibration

I think in the qemu menu there's options to change the way the mouse works. If the mouse dies, change usb-mouse to usb-tablet in the launcher script, was necessary for me.

**Comment by rcg12387** [comment]
> If the mouse dies, change usb-mouse to usb-tablet in the launcher script, was necessary for me.

I have used OpenCore-Boot.sh, it is written as -usb -device usb-kbd -device usb-tablet. You mean this don't you?
