### ISSUE TITLE
Stuck at installation progress

### ISSUE THREAD

**Issue by wufan618223** [sickcodes/Docker-OSX#107]
I have tried so many times, stuck at installation progress.
![image](https://user-images.githubusercontent.com/12378482/99766388-f2b5d600-2b3b-11eb-9d97-5bf6290e73f8.png)
cpu:Intel(R) Core(TM) i7-7700 CPU @ 3.60GH
I can not find out why...
I do the following cmd:
1.docker build -t docker-osx-vnc .
2.docker run --device /dev/kvm --device /dev/snd -p 8888:5999 -p 50922:10022 -d --privileged docker-osx-vnc:latest
3.VNC connect
4.Boot the macOS Base System
5.Click Disk Utility
6.Erase the BIGGEST disk
7.Click Reinstall macOS

**Comment by weskerfoot** [comment]
How much memory does your system have?

**Comment by wufan618223** [comment]
total        used        free      shared  buff/cache   available
Mem:       16172356      436732      154600       53568    15581024    15349024
Swap:       8191996           0     8191996
by free cmd~

**Comment by sickcodes** [comment]
How much disk space do you have? I have tested the latest image, I will give it another test today.

Which disk did you select to install onto?

**Comment by wufan618223** [comment]
I have almost 100G disk space.
i install macos onto the biggest BIGGEST disk(around 200G)

**Comment by Tkd-Alex** [comment]
I have the same error, stuck on install progress

**Comment by weskerfoot** [comment]
If you haven't, I'd make sure you also have swap enabled. That made a huge difference for me.

**Comment by sickcodes** [comment]
I have actually noticed installations can freeze if:

- Internet drops out

- VPN on/off

Try fiddling with your connection. I have been unable to install once or twice solely based on the IP I was using.

**Comment by sickcodes** [comment]
@wufan618223 did you solve this? If so please let us know how and feel free to close the issue when it's solved :)

**Comment by sickcodes** [comment]
Solved by adding :auto image
