### ISSUE TITLE
Restore Backup

### ISSUE THREAD

**Issue by joandervieira** [sickcodes/Docker-OSX#108]
Hi ! Amazing job you've done !

How can I restore a backup made by: 
`docker cp oldcontainerid:/home/arch/OSX-KVM/mac_hdd_ng.img .`
in another computer ?

**Comment by sickcodes** [comment]
Added some more documentation around this :+1: 
https://github.com/sickcodes/Docker-OSX#use-an-old-docker-osx-disk-in-a-fresh-container-replication

Enjoy!
