### ISSUE TITLE
Does it support macOS Big Sur 11.0.1 ?

### ISSUE THREAD

**Issue by ghasemikasra39** [sickcodes/Docker-OSX#109]

**Comment by sickcodes** [comment]
Not sure, you're welcome to test

**Comment by MrBenFTW** [comment]
The software catalog used does not contain 11.x, need to update it.

**Comment by MrBenFTW** [comment]
> The software catalog used does not contain 11.x, need to update it.

Actually it contains 11.1

**Comment by MrBenFTW** [comment]
Something needs fixing, `11.0` shows up but DockerOSX cannot download it
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/27426792/103017012-de019f00-453a-11eb-998d-e7418287da3e.png">

**Comment by MrBenFTW** [comment]
Just to confirm, the latest version of `gibMacOS` is able to download `11.1` however, in macOS big sur there is no longer the ability to download `BaseSystem.dmg`

It will now download `installassistant.pkg` instead. We need to convert this into a base system. I have no idea how to 
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/27426792/103017347-62ecb880-453b-11eb-81aa-fb87121b7fa0.png">

**Comment by sickcodes** [comment]
Alright I'll update gibMacOS if it's there!

**Comment by erosfabbriminer** [comment]
What if we install MacOs Catalina and then update from there?

**Comment by MrBenFTW** [comment]
> What if we install MacOs Catalina and then update from there?

You could try this, however I know that during the beta this would brick your VM.

**Comment by sickcodes** [comment]
I haven't actually tried Big Sur, I'll give it a go this week

**Comment by sickcodes** [comment]
Working on this now, confirming I am unable to download the BaseSystem.img for bigsur too.

**Comment by sickcodes** [comment]
Testing this (slow downloading) https://github.com/sickcodes/Docker-OSX/pull/158

**Comment by sickcodes** [comment]
Added in big sur to Docker-OSX with https://github.com/sickcodes/Docker-OSX/pull/158,

use `--build-arg VERSION=11` but you have to build it yourself (at the moment).

Creating `:big-sur` currently

**Comment by sickcodes** [comment]
```bash
# big sur
docker run -it \
    --device /dev/kvm \
    -p 50922:10022 \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    sickcodes/docker-osx:big-sur
```
