### ISSUE TITLE
Macos starts from the installation over and over again

### ISSUE THREAD

**Issue by itsoulos** [sickcodes/Docker-OSX#118]
Dear all I have followed your instructions to install macos but
after every successful installation the procedure starts again instead of booting to the installed disk
What is wrong with my installation?

Best regards
Giannis Tsoulos

**Comment by thematrixdev** [comment]
Do you see the boot menu (showing two hard drives) after install? Have you chosen the one you have installed OSX to (instead of the base volume)?

**Comment by itsoulos** [comment]
No I see only the drive to install macos

Here is the command that I execute as root

docker run --privileged -e "DISPLAY=${DISPLAY:-:0.0}" -v /tmp/.X11-unix:/tmp/.X11-unix sickcodes/docker-osx

**Comment by thematrixdev** [comment]
The new drive will only show up after installation. Before installation, did you use "disk utility" to "erase" and "create" on the LARGEST drive?

**Comment by itsoulos** [comment]
Yes I have seen the new drive but it has been lost when I closed the application docker and restart it

**Comment by thematrixdev** [comment]
Oh I see. The docker volume does not presist so you have lost the installation. I would suggest you using docker-compose. git clone this project, and `docker-compose up -d`.

**Comment by itsoulos** [comment]
So, you say to execute docker-compose up -d after the installation?

**Comment by thematrixdev** [comment]
No. Use `docker-compose up -d` from the very begining, so the "docker volume" will be managed and persist by `docker-compose`. After installation, use and shut-down, you can use `docker-compose up -d` next time you need to use OSX.

**Comment by sickcodes** [comment]
`docker ps` to get the container ID

`docker start containerid`


Otherwise you'll get a new box every time.

**Comment by itsoulos** [comment]
I have managed to install it but the MACOS can not see IOS Devices

**Comment by sickcodes** [comment]
I will have a prebuilt image ready soon
