### ISSUE TITLE
Mounting an exFAT drive from Ubuntu onto OSX

### ISSUE THREAD

**Issue by thematrixdev** [sickcodes/Docker-OSX#119]
On my computer, Ubuntu is installed on a NVMe-SSD drive. Docker-OSX Docker version is installed on the same drive.

There is another 2.5" SATA SSD dirve on my computer. I have formated it to be exFAT, so both Ubuntu and OSX can read the data from it. It is mounted in /media/me/SSD on Ubuntu; and onto OSX by adding `-hda /dev/sde` onto `docker-compose.yml`.

To make sure the drive is really mounted, I have placed several files onto the drive before running `docker-compose up`. After OSX is installed and booted, the drive "SSD" is shown up in the Finder. The several test files exist.

However, after I have tried putting some more files from Ubuntu, the newly added files are now shown up in OSX. And putting some files from OSX, they don't show up in Ubuntu neither.

1. default -hda mounting should be read-only on the guest OS? I want it to be read-only on the guest OS actually
2. why the drive is mounted, but showing different content? the mounted drive shows correct filesystem format and disk size.

Thanks.

**Comment by sickcodes** [comment]
Hey!

I haven't used the Docker compose file but I believe it could be out of date.

The compose file was added a few months ago and a few things have changed, does it work using the normal commands?

**Comment by thematrixdev** [comment]
I need to install on a headless server.
May I know if this is still being maintain?
https://hub.docker.com/r/darkatse/docker-osx-vnc

**Comment by thematrixdev** [comment]
I have just try to update the docker-compose after reading the single command, seems no difference.

It seems the external harddisk is read at the very beging, the state is kept, and the disk is cloned and separated. Even I erase the disk in OSX, the data is still there on the host. So strange...

**Comment by sickcodes** [comment]
Correct me if I'm wrong, but won't the OSX disk be created in created in `/var/lib/docker/volumes`?

**Comment by mrkvn** [comment]
@thematrixdev I'm curious. Can you post here the `docker-compose.yml` you're using?

**Comment by sickcodes** [comment]
Added arbitrary disk passthrough in https://github.com/sickcodes/Docker-OSX/commit/2295eef68fb180d9021bb50b8244cdead3c1531d

Please see examples here: https://github.com/sickcodes/Docker-OSX#mount-a-disk-inside-osx-from-the-host
