### ISSUE TITLE
Running the same container afterwards

### ISSUE THREAD

**Issue by igaurab** [sickcodes/Docker-OSX#12]
Hi, although I do not know how to work with docker, I managed to install it and was able to run and install my Mac os following the README and reading through the issues. 

The problem now I am having is how do I get back my MacOs that I had installed. I tried running docker start <container-id> of the previously created container, but it only prints out the container id, and if I try running the `docker run ****` command which was prev used it creates a new instance of container. I think this is what was supposed to happen but, I am getting lost here. 

**How do I re run my prev created container, i guess** 

Thanks

**Comment by sickcodes** [comment]
Try the `docker start` command

**Comment by igaurab** [comment]
Hi I tried `docker start container-id` and it did nothing? Just prints the container id and nothing

**Comment by sickcodes** [comment]
The container is running, which means it might not be the right machine, or it didn't start correct.

Open all of them
```
docker start $(docker ps -q --all)
docker start $(docker ps -q --all --filter "ancestor=sickcodes/docker-osx")
```

and then close the ones you don't want

And then `docker ps` and save that name

then you can do docker start

**Comment by sickcodes** [comment]
Please check the readme for new instructions including how to launch the old machine

**Comment by ntd94** [comment]
I have the same problem as @igaurab. Here's the log
```bash
$ docker start 70766a2c9a69
70766a2c9a69

$ docker ps --all --filter "ancestor=sickcodes/docker-osx"
CONTAINER ID        IMAGE                  COMMAND                CREATED             STATUS                      PORTS               NAMES
70766a2c9a69        sickcodes/docker-osx   "./OpenCore-Boot.sh"   3 hours ago         Exited (1) 13 seconds ago                       elastic_varahamihira
```
I couldn't figure out how to start the installed image. Helps would be appreciate, thanks.

**Comment by lucasfjportela** [comment]
I am having the same problem of @ntd94 , if anyone knows how to fix this it would be great, thanks!

**Comment by RockJohnson503** [comment]
sudo chmod 666 /dev/kvm @ntd94 @lucasfjportela @igaurab
