### ISSUE TITLE
"/dev/kvm": no such file or directory

### ISSUE THREAD

**Issue by xiaoqi7s** [sickcodes/Docker-OSX#127]
docker run --device /dev/kvm --device /dev/snd -v /tmp/.X11-unix:/tmp/.X11-unix -e "DISPLAY=${DISPLAY:-:0.0}" sickcodes/docker-osx:latest
docker: Error response from daemon: error gathering device information while adding custom device "/dev/kvm": no such file or directory.
ERRO[0000] error waiting for container: context canceled

**Comment by sickcodes** [comment]
You need to install kvm https://github.com/sickcodes/Docker-OSX#requirements-kvm-on-the-host

**Comment by xiaoqi7s** [comment]
My system is centos and I installed it with command :
sudo yum install libvirt qemu-kvm
sudo systemctl enable libvirtd.service
sudo systemctl enable virtlogd.service
sudo modprobe kvm
reboot

when I run docker,it's  error:  
``` docker: Error response from daemon: error gathering device information while adding custom device "/dev/kvm": no such file or directory.
ERRO[0000] error waiting for container: context canceled ```

**Comment by sickcodes** [comment]
Is this a server or desktop? This happens when your CPU does not support hardware virtualization.

Try a different server, like Digital Ocean, which works perfectly.

**Comment by ghasemikasra39** [comment]
I am getting the same error on Ubuntu. The command I run:

```bash
sudo docker run --device /dev/kvm --device /dev/snd -v /tmp/X11-unix:/tmp/X11-unix -e "DISPLAY=${DISPLAY:-:0.0}" sickcodes/docker-osx:latest

```

The output I get:
```bash
docker: Error response from daemon: error gathering device information while adding custom device "/dev/kvm": no such file or directory.
ERRO[0001] error waiting for container: context canceled 
```

What I tried:

```bash
sudo apt install qemu qemu-kvm libvirt-clients libvirt-daemon-system bridge-utils virt-manager

sudo systemctl enable --now libvirtd
sudo systemctl enable --now virtlogd

echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs

sudo modprobe kvm
```

**Comment by sickcodes** [comment]
> I am getting the same error on `Ubuntu 20.04.2.0 LTS` . The command I run:
> 
> 
> 
> ```bash
> 
> sudo docker run --device /dev/kvm --device /dev/snd -v /tmp/X11-unix:/tmp/X11-unix -e "DISPLAY=${DISPLAY:-:0.0}" sickcodes/docker-osx:latest
> 
> 
> 
> ```
> 
> 
> 
> The output I get:
> 
> ```bash
> 
> docker: Error response from daemon: error gathering device information while adding custom device "/dev/kvm": no such file or directory.
> 
> ERRO[0001] error waiting for container: context canceled 
> 
> ```
> 
> 
> 
> What I tried:
> 
> 
> 
> ```bash
> 
> sudo apt install qemu qemu-kvm libvirt-clients libvirt-daemon-system bridge-utils virt-manager
> 
> 
> 
> sudo systemctl enable --now libvirtd
> 
> sudo systemctl enable --now virtlogd
> 
> 
> 
> echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs
> 
> 
> 
> sudo modprobe kvm
> 
> ```

The server does not support KVM, which cloud is it?

**Comment by mgkha** [comment]
> > I am getting the same error on `Ubuntu 20.04.2.0 LTS` . The command I run:
> > ```shell
> > sudo docker run --device /dev/kvm --device /dev/snd -v /tmp/X11-unix:/tmp/X11-unix -e "DISPLAY=${DISPLAY:-:0.0}" sickcodes/docker-osx:latest
> > ```
> > 
> > 
> > The output I get:
> > ```shell
> > docker: Error response from daemon: error gathering device information while adding custom device "/dev/kvm": no such file or directory.
> > 
> > ERRO[0001] error waiting for container: context canceled 
> > ```
> > 
> > 
> > What I tried:
> > ```shell
> > sudo apt install qemu qemu-kvm libvirt-clients libvirt-daemon-system bridge-utils virt-manager
> > 
> > 
> > 
> > sudo systemctl enable --now libvirtd
> > 
> > sudo systemctl enable --now virtlogd
> > 
> > 
> > 
> > echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs
> > 
> > 
> > 
> > sudo modprobe kvm
> > ```
> 
> The server does not support KVM, which cloud is it?

I got the same error on digital ocean.

**Comment by sickcodes** [comment]
This sets you up on Digital Ocean,

https://github.com/sickcodes/Docker-OSX/blob/master/tests/test.sh

Just ignore the `docker push` commands at the end.

**Comment by sickcodes** [comment]
I am using compute optimized instances, I don't believe the lower image tiers support nested virtualization.

**Comment by ZGuQing** [comment]
> You need to install kvm https://github.com/sickcodes/Docker-OSX#requirements-kvm-on-the-host
How to install kvm?

**Comment by ZGuQing** [comment]
> > You need to install kvm https://github.com/sickcodes/Docker-OSX#requirements-kvm-on-the-host
> > How to install kvm? macos

**Comment by dm-for-git** [comment]
It seems a silly question but can I use this image on a Monterey macOS host machine running on a M1 pro macbook?
Because I got the same error when trying to install your Monterey image
` error gathering device information while adding custom device "/dev/kvm": no such file or directory`

**Comment by CainPy** [comment]
Hi everyone!

I'm trying to install BLISSOS on Linux Mint 20.3, Kernel 5.4.0-125, Intel i3-7100. Nvidia GP107, 8Gb RAM

I do every step as indicated in https://docs.blissos.org/install-bliss-os/run-from-docker

But I'm stucked on

docker run -it \
    --device /dev/kvm \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e RAM=4 \
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    -p 5555:5555 \
    sickcodes/dock-droid:latest
    
    docker: Error response from daemon: error gathering device information while adding custom device "/dev/kvm": **not a device node**.
ERRO[0000] error waiting for container: context canceled

Any help?

**Comment by Areopagitics** [comment]
I get the same error on PopOS (Ubuntu 22.04)

**Comment by Areopagitics** [comment]
> Same. I'm no linux pro, but I've done everything I can find to do and I still get the "no such file or directory" for /dev/kvm. But it's there. I have taken ownership of it. kvm-ok says I'm good to go. Check CPU capabilities is good. I'm at a loss.

exactly the same

**Comment by Areopagitics** [comment]
I just tried it using the docker CLI and now it boots up to `In Memory Stackshot Suceeded` 

STAY AWAY FROM DOCKER DESKTOP and make sure to use sudo before the docker command

https://docs.docker.com/engine/install/ubuntu/#set-up-the-repository
![errors](https://user-images.githubusercontent.com/24683841/208550501-f1eb8126-a709-4241-89ef-599decf07970.jpg)

**Comment by sickcodes** [comment]
Can you show me which Docker version? I may need to update Docs about secomp and privileged use

**Comment by Areopagitics** [comment]
docker -v  _outputs_

`Docker version 20.10.22, build 3a2c30b
`

I am also using PopOs 22.04 (Ubuntu based) on a Ryzen 9 4900h laptop (Asus TUF506IV)

**Comment by ChristopherSargent** [comment]
If you are using a virtual machine the above error is likely due to host cpu virtualization not being enabled. This can be enabled on KVM and VMware. Below are screenshots of examples. 

vCenter with esxi host:
![image](https://user-images.githubusercontent.com/75126362/212470279-68e69ad4-cf9b-4444-9803-f09c837e368c.png)

KVM:
![image](https://user-images.githubusercontent.com/75126362/212470332-73ae1ab6-d324-406d-b0f1-23b84924b3ff.png)

**Comment by AZetZ** [comment]
To solve problem you can go to BIOS and change settings. For my AMD processor I needed to enabled the AMD V Technology.

**Comment by CrypticGuru** [comment]
> To solve problem you can go to BIOS and change settings. For my AMD processor I needed to enabled the AMD V Technology.

I also had to enable virtualization in my BIOS for this to work (`sudo kvm-ok` hinted to me that it wasn't enabled). You'll have to google how to do this for your specific BIOS version, but this solved it for me!

**Comment by heruit777** [comment]
> I just tried it using the docker CLI and now it boots up to `In Memory Stackshot Suceeded`
> 
> STAY AWAY FROM DOCKER DESKTOP and make sure to use sudo before the docker command
> 
> https://docs.docker.com/engine/install/ubuntu/#set-up-the-repository ![errors](https://user-images.githubusercontent.com/24683841/208550501-f1eb8126-a709-4241-89ef-599decf07970.jpg)

I used sudo before docker command and it worked for me. Thank you!

**Comment by ChronSyn** [comment]
In case anyone is searching for an Unraid-specific solution, make sure VM support is enabled (Settings -> VM Management).

If enabled is set to 'false', the `/dev/kvm` path isn't present, and this container and other '<OS>InDocker'-like containers will fail to start due to the missing path.

To resolve, set 'enabled' to 'true'.

**Comment by chriscarrollsmith** [comment]
> > I just tried it using the docker CLI and now it boots up to `In Memory Stackshot Suceeded`
> > STAY AWAY FROM DOCKER DESKTOP and make sure to use sudo before the docker command
> > https://docs.docker.com/engine/install/ubuntu/#set-up-the-repository ![errors](https://user-images.githubusercontent.com/24683841/208550501-f1eb8126-a709-4241-89ef-599decf07970.jpg)
> 
> I used sudo before docker command and it worked for me. Thank you!

This fixed it for me; thank you!
