### ISSUE TITLE
Scripts for waiting mac ssh to come up

### ISSUE THREAD

**Issue by shifujun** [sickcodes/Docker-OSX#129]
Just sharing😃

Install `sshpass` for auto enter password.
`sudo yum install sshpass`

Make a `sshDockerOsx.sh`:
```
sshpass -p docker-osx \
ssh \
  -o UserKnownHostsFile=/dev/null \
  -o StrictHostKeyChecking=no \
  -p 50922 \
  docker-osx@localhost $@
```

Make a `waitForDockerOsx.sh`:
```
until ./sshDockerOsx.sh true; do
  echo "sleep 2 for waiting"
  sleep 2
done
echo "Docker-OSX SSH ready"
```

After `docker run -d ....` start up macOs, execute `./waitForDockerOsx.sh && ./sshDockerOsx.sh` can auto wait and login macOS.

**Comment by sickcodes** [comment]
Perfect! This will work good for version 3, will be using SSH keys however, but the loop is good, thank you 😁!

**Comment by sickcodes** [comment]
Added here: https://github.com/sickcodes/Docker-OSX/commit/a09c565e36d45f6663567b7c4f1402279e725519
