### ISSUE TITLE
Docker fails to start

### ISSUE THREAD

**Issue by Otus9051** [sickcodes/Docker-OSX#131]
Whenever I am trying the start OSX with this command
```
docker run \ 
    --device /dev/kvm \
    --device /dev/snd \
    -v /tmp/X11-unix:/tmp/X11-unix \ 
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    sickcodes/docker-osx:latest
```
This happens
```
docker: unknown server OS: .
```
This is my ```uname -a```
```
Linux garuda 5.10.7-111-tkg-bmq #1 TKG SMP PREEMPT Sun, 17 Jan 2021 02:26:07 +0000 x86_64 GNU/Linux
```
The distro I am using is ```Garuda Linux``` based on ```Arch Linux``` with ```5.10.7-111-TKG-BMQ Kernel```

**Comment by wulei-github** [comment]
add sudo docker run

**Comment by Otus9051** [comment]
> add sudo docker run

Forgot to include that I did do it, but it didn't work and the error was same.

**Comment by sickcodes** [comment]
`sudo dockerd`

Your docker daemon is off

**Comment by Otus9051** [comment]
@sickcodes well i did do ```sudo dockerd```

**Comment by sickcodes** [comment]
> Whenever I am trying the start OSX with this command
> 
> ```
> docker run \ 
>     --device /dev/kvm \
>     --device /dev/snd \
>     -v /tmp/X11-unix:/tmp/X11-unix \ 
>     -e "DISPLAY=${DISPLAY:-:0.0}" \
>     sickcodes/docker-osx:latest
> ```
> 
> This happens
> 
> ```
> docker: unknown server OS: .
> ```
> 
> This is my `uname -a`
> 
> ```
> Linux garuda 5.10.7-111-tkg-bmq #1 TKG SMP PREEMPT Sun, 17 Jan 2021 02:26:07 +0000 x86_64 GNU/Linux
> ```
> 
> The distro I am using is `Garuda Linux` based on `Arch Linux` with `5.10.7-111-TKG-BMQ Kernel`

You have a trailing space after `docker run \_`

**Comment by Otus9051** [comment]
@sickcodes 
```
docker run \ 
    --device /dev/kvm \
    --device /dev/snd \
    -v /tmp/X11-unix:/tmp/X11-unix \ 
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    sickcodes/docker-osx:latest
docker: unknown server OS: .
See 'docker run --help'.
```

**Comment by sickcodes** [comment]
`docker run --device /dev/kvm --device /dev/snd -v /tmp/X11-unix:/tmp/X11-unix -e "DISPLAY=${DISPLAY:-:0.0}" sickcodes/docker-osx:latest`

You have a trailing space on the first line.

**Comment by Otus9051** [comment]
Well my OS effed up... I'll try this once I fix it. Thanks for the help tho...

**Comment by Otus9051** [comment]
![image](https://user-images.githubusercontent.com/58171861/106241275-c7322480-622b-11eb-85a6-75a067c1cadc.png)
@sickcodes

**Comment by Silfalion** [comment]
Tried `xhost + ` ?

**Comment by Otus9051** [comment]
What's that?

**Comment by Silfalion** [comment]
Run it in your terminal then run your docker command

**Comment by Otus9051** [comment]
nope. same thing.

**Comment by sickcodes** [comment]
`echo $DISPLAY`
If this is blank you have no screen. 

`egrep -c '(svm|vmx)' /proc/cpuinfo`
If this is 0, turn on hardware virt in your bios.

**Comment by Otus9051** [comment]
```
> echo $DISPLAY
:0
```
```
> egrep -c '(svm|vmx)' /proc/cpuinfo
4
```

**Comment by sickcodes** [comment]
```
docker: unknown server OS: .
See 'docker run --help'.
```
This happens when dockerd is off

Can you confirm the docker daemon is running? `pgrep dockerd`

**Comment by Otus9051** [comment]
```
> pgrep dockerd
558
```

**Comment by Otus9051** [comment]
> ```
> docker: unknown server OS: .
> See 'docker run --help'.
> ```

Actually this error doesn't happen now
Something is up with ALSA

**Comment by Otus9051** [comment]
I'll try the troubleshooting commands from the README.md
See if that works...

**Comment by sickcodes** [comment]
> I'll try the troubleshooting commands from the README.md
> 
> See if that works...

Sounds good! Can you let us know when you've fixed it?

**Comment by Otus9051** [comment]
Welp... I gave up on it and decided to install the prebuilt image and now, the error is kinda like this...
```
> docker run -it \
    --device /dev/kvm \
    -p 50922:10022 \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    -e "OSX_COMMANDS=/bin/bash -c \"pwd && uname -a\"" \
    sickcodes/docker-osx:auto

/usr/sbin/ssh-copy-id: INFO: Source of key(s) to be installed: "/home/arch/.ssh/id_docker_osx.pub"
ssh: connect to host 127.0.0.1 port 10022: Connection refused
Disk is being copied between layers. Repeating until able to copy SSH key into OSX...
No protocol specified
```
And this loops on and on and in until terminated...

**Comment by sickcodes** [comment]
Remove the OSX_COMMANDS line because it will close the image


```bash
docker run -it \
    --device /dev/kvm \
    -p 50922:10022 \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    sickcodes/docker-osx:auto
```

**Comment by Otus9051** [comment]
```
docker: Error response from daemon: failed to create endpoint peaceful_visvesvaraya on network bridge: failed to add the host (veth517af6d) <=> sandbox (vethe1632dd) pair interfaces: operation not supported. ERRO[0001] error waiting for container: context canceled
```

**Comment by mostwanted002** [comment]
> Welp... I gave up on it and decided to install the prebuilt image and now, the error is kinda like this...
> 
> ```
> > docker run -it \
>     --device /dev/kvm \
>     -p 50922:10022 \
>     -v /tmp/.X11-unix:/tmp/.X11-unix \
>     -e "DISPLAY=${DISPLAY:-:0.0}" \
>     -e "OSX_COMMANDS=/bin/bash -c \"pwd && uname -a\"" \
>     sickcodes/docker-osx:auto
> 
> /usr/sbin/ssh-copy-id: INFO: Source of key(s) to be installed: "/home/arch/.ssh/id_docker_osx.pub"
> ssh: connect to host 127.0.0.1 port 10022: Connection refused
> Disk is being copied between layers. Repeating until able to copy SSH key into OSX...
> No protocol specified
> ```
> 
> And this loops on and on and in until terminated...

The same is happening with me when I'm trying to use `docker-osx:auto`. And it gives `gtk initialization has failed` when running `docker-osx:latest`.

**Comment by sickcodes** [comment]
@mostwanted002 @Otus9051 


`    -e "OSX_COMMANDS=/bin/bash -c \"pwd && uname -a\"" \`

Will run, inside Mac's Terminal:

`bin/bash -c "pwd && uname -a"`

pwd is print working directory

uname -a will print system info

Then it will exit.

Remove that line if you want to stay running, or add `&& /bin/bash` at the end

**Comment by C9-Dev** [comment]
I'm trying to run but i got this error `Unable to init server: Could not connect: Connection refused
qemu-system-x86_64: cannot set up guest memory 'pc.ram': Cannot allocate memory
QEMU 5.2.0 monitor - type 'help' for more information
(qemu)`
Can anyone help me?
I am trying the start OSX with this command
`sudo docker run --device /dev/kvm --device /dev/snd -v /tmp/X11-unix:/tmp/X11-unix -e "DISPLAY=${DISPLAY:-:0.0}" sickcodes/docker-osx:latest`

**Comment by sickcodes** [comment]
Connect refused is either /dev/kvm permissions, xhost +, or you're not in libvirt, docker or kvm groups, or you're running with root

**Comment by C9-Dev** [comment]
I've tried to run now but I got this error
`gtk initialization failed`

**Comment by BackMountainDevil** [comment]
> add sudo docker run

it is not recommand to run docker with sudo. It may be dangerous

**Comment by allansrc** [comment]
who is running on WSL must to use Docker on Windows Client and extern it to wsl v2

after that, You can run it perfectly. 
 ```
docker run -it \
    --device /dev/kvm \
    -p 50922:10022 \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    -e GENERATE_UNIQUE=true \
    -e MASTER_PLIST_URL=https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom.plist \
    sickcodes/docker-osx:big-sur
```

**Comment by sickcodes** [comment]
> who is running on WSL, and are getting stuck on `docker: unknown server OS: .`
> must to use Docker on Windows Client and extern it to wsl v2
> 
> check https://docs.docker.com/docker-for-windows/wsl/
> 
> make sure that your distro is enabled
> 
> <img alt="" width="450px/" src="https://user-images.githubusercontent.com/35867294/126843683-8369245b-034e-4ab6-a1df-5b77e5def6d8.png">
> 
> after that, You can run it perfectly.
> 
> ```
> docker run -it \
>    --device /dev/kvm \
>    -p 50922:10022 \
>    -v /tmp/.X11-unix:/tmp/.X11-unix \
>    -e "DISPLAY=${DISPLAY:-:0.0}" \
>    -e GENERATE_UNIQUE=true \
>    -e MASTER_PLIST_URL=https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom.plist \
>    sickcodes/docker-osx:big-sur
> ```

Fantastic! It runs perfectly now? Thank you for letting us know :)

**Comment by allansrc** [comment]
> > who is running on WSL, and are getting stuck on `docker: unknown server OS: .`
> > must to use Docker on Windows Client and extern it to wsl v2
> > check https://docs.docker.com/docker-for-windows/wsl/
> > make sure that your distro is enabled
> > <img alt="" width="450px/" src="https://user-images.githubusercontent.com/35867294/126843683-8369245b-034e-4ab6-a1df-5b77e5def6d8.png">
> > after that, You can run it perfectly.
> > ```
> > docker run -it \
> >    --device /dev/kvm \
> >    -p 50922:10022 \
> >    -v /tmp/.X11-unix:/tmp/.X11-unix \
> >    -e "DISPLAY=${DISPLAY:-:0.0}" \
> >    -e GENERATE_UNIQUE=true \
> >    -e MASTER_PLIST_URL=https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom.plist \
> >    sickcodes/docker-osx:big-sur
> > ```
> 
> Fantastic! It runs perfectly now? Thank you for letting us know :)

Yep i just test on Windowns 10 21H1 and also on windows 11. runs good

**Comment by sickcodes** [comment]
Fantastic, thank you! And thank you for https://github.com/sickcodes/Docker-OSX/pull/318

**Comment by pedro3g** [comment]
I solved my problem by running as sudo.

**Comment by dimashpt** [comment]
> who is running on WSL, and are getting stuck on `docker: unknown server OS: .` must to use Docker on Windows Client and extern it to wsl v2
> 
> check [docs.docker.com/docker-for-windows/wsl](https://docs.docker.com/docker-for-windows/wsl/)
> 
> make sure that your distro is enabled
> 
> <img alt="" width="450px/" src="https://user-images.githubusercontent.com/35867294/126843683-8369245b-034e-4ab6-a1df-5b77e5def6d8.png">
> 
> after that, You can run it perfectly.
> 
> ```
> docker run -it \
>    --device /dev/kvm \
>    -p 50922:10022 \
>    -v /tmp/.X11-unix:/tmp/.X11-unix \
>    -e "DISPLAY=${DISPLAY:-:0.0}" \
>    -e GENERATE_UNIQUE=true \
>    -e MASTER_PLIST_URL=https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom.plist \
>    sickcodes/docker-osx:big-sur
> ```

Been 4 years, and still works like a charm, thank you!
