### ISSUE TITLE
iMessage

### ISSUE THREAD

**Issue by sickcodes** [sickcodes/Docker-OSX#136]
Want to do end-to-end automation for setting up iMessage.

If anyone has successfully used iMessage, feel free to post your notes and I will release a stripped down image that should support iMessage.

"The goal is to conduct security research on the iMessage system which has been afflicted by 0days in the past."

**Comment by JGmmcap** [comment]
Take a look here: 

https://github.com/foxlet/macOS-Simple-KVM/blob/master/docs/guide-Apple-ID.md

Test with a throwaway apple ID before you sign out and log in with an existing ID.

With watch OS 7.0.1, it was possible to activate an apple ID on a watch in standalone mode that was previously banned as an apple ID to unban the ID. I expect this would factor into security considerations with respect to imessage.

**Comment by sickcodes** [comment]
Been working on this recently using https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html

**Comment by sickcodes** [comment]
Successfully activated iMessage on Docker-OSX. Tutorial will probably be added in due course!

**Comment by sickcodes** [comment]
Added with https://github.com/sickcodes/Docker-OSX/commit/27efe6658d7b0bdeaabf042422ebc663b8bc6d04
