### ISSUE TITLE
Crash on the 22Gb version

### ISSUE THREAD

**Issue by Silfalion** [sickcodes/Docker-OSX#139]
Hi everyone. Love the 22Gb but it keeps crashing with this error the first time:

`Connection to 127.0.0.1 closed by remote host.
Connection to 127.0.0.1 closed.
`
Then afterward using `docker start containerId` prints just the containerId without starting the VM like in issue [12](https://github.com/sickcodes/Docker-OSX/issues/12).

Any container made after this with `docker run` would crash on boot as well, QEMU starts and after a few seconds it crashes again. 

This issue seems to be linked with the 22Gb version as I didn't have this issue with the normal version before.

Any idea how to fix it?

**Comment by sickcodes** [comment]
Yeah it needs more work, but you can Docker start it and then docker exec commands to launch.

I'll work on it for auto start shortly!

In any case, use the naked image on the existing disk .img, it will be the same.

**Comment by Silfalion** [comment]
Thank you! 

Not very familiar with docker though, could you give me a small example of the arguments to use for docker exec? pasted the arguments used to run the docker file from the gihub but they seem incorrect. Also where to find the existing disk image in the /var/lib/docker folder please?

**Comment by sickcodes** [comment]
Find old image: https://github.com/sickcodes/Docker-OSX#backup-the-disk-wheres-my-disk

Working on `docker start` now for the auto image.

**Comment by Silfalion** [comment]
Stumbled upon that solution a few moments prior to your message lol. Messed up though by overriding the right image, Downloading it again now.

Thank you so much for your hardwork, you're awesome, wish you the best in the world. It's been a long time I wanted to get easy access to a mac.

Out of context, did you have time to look at the other gpu passthrough issue(not an issue) that was opened a few days ago?

**Comment by sickcodes** [comment]
> Hi everyone. Love the 22Gb but it keeps crashing with this error the first time:
> 
> 
> 
> `Connection to 127.0.0.1 closed by remote host.
> 
> Connection to 127.0.0.1 closed.
> 
> `
> 
> Then afterward using `docker start containerId` prints just the containerId without starting the VM like in issue [12](https://github.com/sickcodes/Docker-OSX/issues/12).
> 
> 
> 
> Any container made after this with `docker run` would crash on boot as well, QEMU starts and after a few seconds it crashes again. 
> 
> 
> 
> This issue seems to be linked with the 22Gb version as I didn't have this issue with the normal version before.
> 
> 
> 
> Any idea how to fix it?

It's not crashing btw, it's waiting for the huge image to copy to another layer. Then it will automatically log in

**Comment by Silfalion** [comment]
Oh, maybe that's why it was making those beeping sounds.

**Comment by sickcodes** [comment]
Fixed in https://github.com/sickcodes/Docker-OSX/commit/27d7496a70665ac0ead1aaf50a6417ab9dc5135c

Use `docker start -i` to start plus get a shell.

Please wait until the new images are pushed and then make sure you docker pull the latest image.

**Comment by Silfalion** [comment]
Sure! Thank you so much! Looking forward to it.

**Comment by Silfalion** [comment]
Tested it and getting the same behavior, it shows the screen now but after a few seconds it shows this:

`/usr/sbin/ssh-copy-id: INFO: Source of key(s) to be installed: "/home/arch/.ssh/id_docker_osx.pub"
Warning: Permanently added '[127.0.0.1]:10022' (ECDSA) to the list of known hosts.
IdentityFile ~/.ssh/id_docker_osx
Default username: user
Default password: alpine
Change it immediately using the command: passwd
Warning: Permanently added '[127.0.0.1]:10022' (ECDSA) to the list of known hosts.
/Users/user
Darwin users-iMac-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64
`

Could it be an openssh problem?

**Comment by sickcodes** [comment]
It worked, you ran `uname -s`.

Don't use OSX_COMMANDS if you don't want to run commands

**Comment by Silfalion** [comment]
sorry, didn't precise, after it shows that the vm window get closed, for the command I just used `docker start -i <container-di>`

**Comment by sickcodes** [comment]
Yes, because before the container was stopped, it had OSX_COMMANDS set in the example.

Remove that line, and you can docker start it willy nilly.

**Comment by Silfalion** [comment]
my bad 🤦🏻, thank you so much!

**Comment by Silfalion** [comment]
Sorry again, new error:

`ssh: connect to host 127.0.0.1 port 10022: Connection refused
Disk is being copied between layers. Repeating until able to copy SSH key into OSX...
`
repeatedly and never ending.

Tried xhost +, chmod 666 /dev/kvm, reinstalling openssh-server, changing the ssh port to 10022. The server is active too.

**Comment by Silfalion** [comment]
Finally got it working. Had to give up on the script for the 22Gb version and used the naked image as you advised yesterday. Everything should be working well now, thank you again!

**Comment by itlwy** [comment]
what command can launch,please?
