### ISSUE TITLE
Cannot allocate memory

### ISSUE THREAD

**Issue by Mehran** [sickcodes/Docker-OSX#14]
i got this error,  i run it on DigitalOcean Host with 3GB ram

```
Unable to init server: Could not connect: Connection refused
QEMU 5.0.0 monitor - type 'help' for more information
(qemu) qemu-system-x86_64: cannot set up guest memory 'pc.ram': Cannot allocate memory
```

**Comment by sickcodes** [comment]
`free -mh`
It will barely run without at least 5gb+ of RAM.
Add 10gb of swap ram you’ll be able to boot it

You also need a display, I will add the VNC version today so you can connect to the VNC display.

If anyone else wants professional support setting it up you can leave a message on my site https://sick.codes/contact/
