### ISSUE TITLE
No protocol specified Unable to init server

### ISSUE THREAD

**Issue by Cristuker** [sickcodes/Docker-OSX#15]
I run 
```
sudo apt install x11-xserver-utils
```
and
```
sudo apt install qemu qemu-kvm libvirt-clients libvirt-daemon-system bridge-utils virt-manager
```
```bash
docker run --privileged -e "DISPLAY=${DISPLAY:-:0.0}" -v /tmp/.X11-unix:/tmp/.X11-unix sickcodes/docker-osx     

No protocol specified
Unable to init server: Could not connect: Connection refused
Could not access KVM kernel module: Permission denied
qemu-system-x86_64: failed to initialize kvm: Permission denied
```

**Comment by sickcodes** [comment]
Please post output:

```
egrep -c '(svm|vmx)' /proc/cpuinfo
ls -l /dev/kvm
pgrep -a X
echo $SHELL
echo $DISPLAY
```

Try this command:
`docker run --privileged --net host --cap-add=ALL -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev:/dev -v /lib/modules:/lib/modules sickcodes/docker-osx`

**Comment by Cristuker** [comment]
Sorry, i try other commands and read the readme whit attention this issue is unecessary, my mistake, sorry.

**Comment by sickcodes** [comment]
Thanks mate :) which command worked for you?

**Comment by proequilibrium** [comment]
I had same issue, after another which was solved by https://github.com/sickcodes/Docker-OSX troubleshoots.
Finaly I used the first docker command and it works.
`docker run --privileged -e "DISPLAY=${DISPLAY:-:0.0}" -v /tmp/.X11-unix:/tmp/.X11-unix sickcodes/docker-osx`

**Comment by sickcodes** [comment]
> I had same issue, after another which was solved by https://github.com/sickcodes/Docker-OSX troubleshoots.
> 
> Finaly I used the first docker command and it works.
> 
> `docker run --privileged -e "DISPLAY=${DISPLAY:-:0.0}" -v /tmp/.X11-unix:/tmp/.X11-unix sickcodes/docker-osx`

Thanks for letting us know :)
