### ISSUE TITLE
Larger Disk Size

### ISSUE THREAD

**Issue by kinteseay** [sickcodes/Docker-OSX#16]
I'm trying to type the command on the bottom of the readme to make a volume of 256G instead of 32G.  But when I try it I'm getting the following message.

"docker build" requires exactly 1 argument

I'm running this on Arch linux.  Is there something else I should be doing?

**Comment by antoineraulin** [comment]
If I remember well, you just need to add a dot a the end of the command

**Comment by kinteseay** [comment]
Thanks
