### ISSUE TITLE
Utilizing more RAM

### ISSUE THREAD

**Issue by ZackaryNisbet** [sickcodes/Docker-OSX#18]
I've been extremely impressed with the container's performance. But I was on Xcode and when I tried to summon the simulator, and I was given the following error: 

> **Unable to boot device due to insufficient memory**
Too many processes
Simulated devices are not supported on systems with less than 4GB of physical memory

I know the container is utilizing 3GB of RAM. I found solutions on stackoverflow to allow more RAM to Docker on Windows and Mac, but I have my docker container built on Linux (Ubuntu 20.04). I was wondering if there was any way I could dedicate more RAM. 

edit: docker has access to all 16GB of my RAM; it's just the container that's limited. 
[docker stats](https://imgur.com/UpxXDFt)

**Comment by sickcodes** [comment]
Yes I forgot about that, let me add it to the optional runtime arguments!

**Comment by sickcodes** [comment]
Change the 8000 to how many MB of ram you want:

docker run --privileged -v /tmp/.X11-unix:/tmp/.X11-unix sickcodes/docker-osx /bin/bash -c "sed -e 's/3072/8000/g' ./OpenCore-Boot.sh | sh -"

**Comment by sickcodes** [comment]
I think it should be kept as a runtime arg, in case people have more or less RAM

 will add it tomorrow as a runtime arg, like
`-e RAM=3076`

The ram line is in the OpenCore-Boot.sh script if someone wants to beat me to it, it’s `-m 3076`

**Comment by ZackaryNisbet** [comment]
Thank you! One last thing, is there anything I can do to improve the refresh rate and resolution? The docker believes I'm on a 30.5 inch iMac Pro but running at 1920x1080, so everything is very crisp but smaller than I'd like. In settings there is no option for scaling. The refresh rate also appears to be below 60hz as its not as smooth as it should be. Perhaps this has to do with the low virtual ram, but I'm not sure.

**Comment by sickcodes** [comment]
I think it’s the VMware display device. I’m not sure how to increase the refresh rate.

 I also dont have a real GPU so I can’t test any pass-through, perhaps someone else can contribute if they are able to nail pass-through.

**Comment by sickcodes** [comment]
Closing this issue related to RAM, I’m following upstream for vram changes, happy to hear from anyone who has input or has solved it already.
