### ISSUE TITLE
Running on Windows

### ISSUE THREAD

**Issue by leduardo99** [sickcodes/Docker-OSX#190]
Is it possible to create an OSX container using a windows machine as a host or do we really need to use Linux?

I use Windows and I have Docker, but I was unable to use the aforementioned commands.

**Comment by sickcodes** [comment]
Please see existing Windows discussion here: https://github.com/sickcodes/Docker-OSX/issues/37

It is incredibly slow on WSL2, might change in the future though if Windows keeps doing what they're doing!
