### ISSUE TITLE
Increase RAM after creating container

### ISSUE THREAD

**Issue by marcocastignoli** [sickcodes/Docker-OSX#197]
Is it possible to increase RAM of an existing container?

**Comment by sickcodes** [comment]
Yes take the image out and use `:naked`

**Comment by marcocastignoli** [comment]
I saw the small section in the readme saying quite the same thing. But it's not clear what you it means to "take the image out". Thanks for your patience

**Comment by marcocastignoli** [comment]
I just found what you mean... I suggest you to insert a link to the section "Backup the disk (Where's my disk?)" in the section "Start the same container later (persistent disk)" (if it makes sense)

**Comment by sickcodes** [comment]
Will provide instructions shortly! Did you work it out regardless?

**Comment by marcocastignoli** [comment]
I reacreated the container before you replied :+1: very fast, so no problem man. Great work!

**Comment by mchemweno** [comment]
Can you please help with the instructions about 'taking an image out'

**Comment by catleeball** [comment]
@mchemweno : It looks like this is mentioned in the [Container creation](https://github.com/sickcodes/Docker-OSX#container-creation-examples) part of the docs.

Briefly, it looks something like this:

```bash
$ docker pull sickcodes/docker-osx:auto
[...]
Status: Downloaded newer image for sickcodes/docker-osx:auto
docker.io/sickcodes/docker-osx:auto

$ sudo find /var/lib/docker -size +10G | grep mac_hdd_ng.img | head -n 1
/var/lib/docker/overlay2/43736bffc5990b2c44e61c30110414b00389d18419638b1ccae1acf42df034a4/diff/home/arch/OSX-KVM/mac_hdd_ng.img

$ cp --sparse=always /var/lib/docker/overlay2/43736bffc5990b2c44e61c30110414b00389d18419638b1ccae1acf42df034a4/diff/home/arch/OSX-KVM/mac_hdd_ng.img ./
```

or in one line with something like this maybe:

```bash
$  docker pull sickcodes/docker-osx:auto && cp $(sudo find /var/lib/docker -size +10G | grep mac_hdd_ng.img | head -n 1) ./
```

**Comment by gustavotoyota** [comment]
Leaving the solution here as it was hard for me to find: https://github.com/sickcodes/Docker-OSX/discussions/199#discussioncomment-510813
