### ISSUE TITLE
Quemu error with naked image

### ISSUE THREAD

**Issue by bayramog** [sickcodes/Docker-OSX#204]
Hi,

I am getting below error when I try to run docker.

![image](https://user-images.githubusercontent.com/61725918/111431006-44e2be80-870c-11eb-94e7-1f1cbbfc4dba.png)

**Comment by sickcodes** [comment]
Is the file mac_hdd_ng_auto.img in your current working directory? Naked is for supplying a local file as the disk to be used, you can make one first using :latest, or pull :auto, move the image out and use that as the input file

**Comment by sickcodes** [comment]
But yeah just run

`wget https://images.sick.codes/mac_hdd_ng_auto.img`

And then run again

Alternatively, docker pull the auto image and then pull the image out because it may download faster via hub.docker
