### ISSUE TITLE
kvm version too old

### ISSUE THREAD

**Issue by Denoic** [sickcodes/Docker-OSX#205]
When i try to run the cointainer its says "kvm version too old". How can i fix that?

![image](https://user-images.githubusercontent.com/51166786/111437391-b2dab600-870b-11eb-995f-fc2be798523b.png)
this is a screenshot

**Comment by sickcodes** [comment]
I agree that is a screenshot 😜


Can you post the output of this:

```bash
# OS related issued, please help us identify the issue by posting the output of this
uname -a \
; echo "${DISPLAY}" \
; echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs \
; grep NAME /etc/os-release \
; df -h . \
; qemu-system-x86_64 --version \
; libvirtd --version \
; free -mh \
; nproc \
; egrep -c '(svm|vmx)' /proc/cpuinfo \
; ls -lha /dev/kvm \
; ls -lha /tmp/.X11-unix/ \
; ps aux | grep dockerd \
; docker ps | grep osx \
; grep "docker\|kvm\|virt" /etc/group
```

**Comment by Denoic** [comment]
well i kinda don't get there. I just start the docker and it does this. I'm on windows (if that matters)

**Comment by Denoic** [comment]
and sorry for the late response. I was sleeping @sickcodes

**Comment by sickcodes** [comment]
It doesn't work on windows

**Comment by Denoic** [comment]
oof sorry, what other alternatives you could recommend me? I want a virutal mac only for the xCode. VirtualBox has bad performance.

**Comment by ZEON-1** [comment]
My guy u got this _don't Give up NEVER BACK DOWN 🐷🤞

**Comment by sickcodes** [comment]
Sorry it works it's just incredibly slow. You can find by searching WSL2 in the closed issues section.

**Comment by CommanderGL** [comment]
I'm getting this issue on linux now
