### ISSUE TITLE
Is storage persistant?

### ISSUE THREAD

**Issue by Xenfo** [sickcodes/Docker-OSX#215]
I saw that your saving to a tmp directory but it does not seem like that is the actual OS. Is there a way to keep my data or will it be wiped each time?

**Comment by Xenfo** [comment]
Nevermind found what I was looking for.

**Comment by shahidcodes** [comment]
Share what have you found?

**Comment by Xenfo** [comment]
I ended up making a script.

```
#!/bin/bash

cd /var/lib/docker/overlay2/4cba4fb2343e8673cb32c2bce509e9b960e4f56c4b71df81dae1215ee0aca57d/diff/home/arch/OSX-KVM

docker run -it \
    --device /dev/kvm \
    -p 50922:10022 \
    -v "${PWD}/mac_hdd_ng.img:/image" \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    sickcodes/docker-osx:naked
```

Replace the path to whatever yours is (you get it by running the image first).
