### ISSUE TITLE
SSH - WIP

### ISSUE THREAD

**Issue by sickcodes** [sickcodes/Docker-OSX#22]
Just a heads up if anyone was working on it, I will have an SSH “double” tunnel fix added today so you can SSH straight through from host, to container, to the QEMU guest.

**Comment by coef** [comment]
@sickcodes How's it looking? Any hickups?

**Comment by sickcodes** [comment]
```
# allow ssh to container
WORKDIR /root
RUN mkdir .ssh
RUN chmod 700 .ssh

WORKDIR /root/.ssh
RUN touch authorized_keys
RUN chmod 644 authorized_keys

WORKDIR /etc/ssh
RUN tee -a sshd_config <<< 'AllowTcpForwarding yes'
RUN tee -a sshd_config <<< 'PermitTunnel yes'
RUN tee -a sshd_config <<< 'X11Forwarding yes'
RUN tee -a sshd_config <<< 'PasswordAuthentication yes'
RUN tee -a sshd_config <<< 'PermitRootLogin yes'
RUN tee -a sshd_config <<< 'PubkeyAuthentication yes'
RUN tee -a sshd_config <<< 'HostKey /etc/ssh/ssh_host_rsa_key'
RUN tee -a sshd_config <<< 'HostKey /etc/ssh/ssh_host_ecdsa_key'
RUN tee -a sshd_config <<< 'HostKey /etc/ssh/ssh_host_ed25519_key'

# enable ssh on start
USER arch
RUN tee -a ssh_enable.sh <<< '[[ -f /etc/ssh/ssh_host_rsa_key ]] || \ '
RUN tee -a ssh_enable.sh <<< '[[ -f /etc/ssh/ssh_host_ed25519_key ]] || \ '
RUN tee -a ssh_enable.sh <<< '[[ -f /etc/ssh/ssh_host_ed25519_key ]] || \ '
RUN tee -a ssh_enable.sh <<< 'sudo /usr/bin/ssh-keygen -A'
```

Here's enabling SSH which works fine.

Because I set it to usermode networking, I am not sure how to then SSH into the QEMU instance. I can do it when it's bridged, but bridged networking wasn't working. Do you have experience with it?

**Comment by sickcodes** [comment]
```
# from host
ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_dockerosx
chmod 644 ~/.ssh/id_dockerosx.pub
chmod 500 ~/.ssh/id_dockerosx
# docker copy the key to the guest's ssh folder and as authorized_hosts
docker cp ~/.ssh/id_dockerosx.pub ${CONTAINER}:/root/.ssh/id_dockerosx.pub
docker cp ~/.ssh/id_dockerosx.pub ${CONTAINER}:/root/.ssh/authorized_keys

# chmod 644 public key & authorized_keys
docker exec -u root -it $CONTAINER /bin/chmod 644 /root/.ssh/id_dockerosx.pub 
docker exec -u root -it $CONTAINER /bin/chmod 644 /root/.ssh/authorized_keys

# chown root:root public key & authorized_keys
docker exec -u root -it $CONTAINER /bin/chown root:root /root/.ssh/id_dockerosx.pub 
docker exec -u root -it $CONTAINER /bin/chown root:root /root/.ssh/authorized_keys 
docker exec -u root -d $CONTAINER /bin/sshd -D

```

**Comment by sickcodes** [comment]
Can SSH if switch back to bridge networking, but I think libvirt didn’t create a default virsh networking profile. Or if someone wants to contribute something like a sock like /dev ssh or anything really that’d be great.

**Comment by sickcodes** [comment]
Thanks mate! Hopefully this weekend I’ll have some free time. Someone else could fix this by changing the networking part back to bridging and then you can just forward 22 on the QEMU box to 23 or something on the Arch host. I’ve SSH’d in before fine, the issue is the default network in virsh is not present on install. 

The QEMU system is reachable in 10.0.15.2 or similar. 

Would be great if someone with QEMU or simple container networking could help :)

**Comment by coef** [comment]
@sickcodes Right on, good lookin' profile pic 😄

**Comment by sickcodes** [comment]
Finished :)
https://github.com/sickcodes/Docker-OSX/commit/0a9da5af75df1f08446c76c527ad3a3a0e2b50f8
