### ISSUE TITLE
Failed to connect to socket /tmp/dbus-1fky4S5tTx: Connection refused

### ISSUE THREAD

**Issue by 19317362** [sickcodes/Docker-OSX#224]
Server Version: 19.03.8
 
Kernel Version: 5.9.0-050900-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64

The last error message is :
qemu-system-x86_64: warning: dbind: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-1fky4S5tTx: Connection refused
qemu-system-x86_64: -drive id=InstallMedia,if=none,file=/home/arch/OSX-KVM/BaseSystem.img,format=qcow2: Could not open '/home/arch/OSX-KVM/BaseSystem.img': No such file or directory

**Comment by 19317362** [comment]
Sorry, I found it's caused by my network. --- Can not download file from github in my country

**Comment by sickcodes** [comment]
You can build locally :)

`docker build -t docker-osx .`
