### ISSUE TITLE
Update Dockerfile for moved fetch-macOS.py script in OSX-KVM

### ISSUE THREAD

**Issue by mewtlu** [sickcodes/Docker-OSX#225]
In kholia/OSX-KVM's latest commit to master the `fetch-macOS.py` script was moved to `backups/fetch-macOS.py` in favour of a new `fetch-macOS-v2.py` script in the root, which means that this Dockerfile is no longer working since it expects the old script.

Not sure whether the old/new scripts are better but just thought I'd raise an issue to help get this sorted quickly since I've had to make this change locally for now.

**Comment by sickcodes** [comment]
https://github.com/sickcodes/Docker-OSX/commit/d4ffc1f2f315f2953085ee4fee182bc39ad0c26a

**Comment by sickcodes** [comment]
Just noticed about 10 mins ago, uploaded it locally instead to the REPO, just pushing the images :)

**Comment by sickcodes** [comment]
Happened last night, pushed and went to sleep

**Comment by mewtlu** [comment]
Haha awesome, thanks for the quick response and the awesome project!
