### ISSUE TITLE
Installation of OSX hangs

### ISSUE THREAD

**Issue by pkos98** [sickcodes/Docker-OSX#226]
- I have > 50GB of free space
- I have 8 GB of total RAM
- Linux architect 5.11.9-arch1-1 #1 SMP PREEMPT Wed, 24 Mar 2021 18:53:54 +0000 x86_64 GNU/Linux

After running the docker image, Erasing the Disk, Creating a new partition with \<size\>-1GB and clicking on "reinstall Mac-OS" the installation always hangs - on Catalina and Big Sur! On Catalina it always hangs at the "4 minutes remaining" mark.

![image](https://user-images.githubusercontent.com/29687073/112719924-d0720180-8efb-11eb-8194-cc11e828d917.png)

**Comment by pkos98** [comment]
Here's an image from the installation log:

![image](https://user-images.githubusercontent.com/29687073/112723706-38cade00-8f10-11eb-8b61-2973e41dc537.png)


Total RAM used on my laptop was < 5GB

**Comment by sickcodes** [comment]
This usually relates to IP address. Can you try with a VPN on?

**Comment by pkos98** [comment]
@sickcodes I tried it using my company's VPN and unfortunately it did not change anything.

**Comment by sickcodes** [comment]
You can use an already made image

```bash
wget https://images2.sick.codes/mac_hdd_ng_auto.img

docker run -it \
    --device /dev/kvm \
    -p 50922:10022 \
    -v "${PWD}/mac_hdd_ng_auto.img:/image" \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    sickcodes/docker-osx:naked
```

Can you show me the docker command you used to run the container?

Have you changed the location of /var/lib/docker?

How fast is your internet?

**Comment by pkos98** [comment]
Right now I am downloading the mac image with constant 12 MB/s, I pay for a 100MBit connection und usually don't have problems with it (latency/loss rate wise).  

Sure, the command I used is:
```bash
docker run --privileged -it \                                                               
    --device /dev/kvm \
    -p 50922:10022 \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    sickcodes/docker-osx:latest
```

I didn't change the location, and my `/etc/docker/daemon.json` only contains this line: `{ "storage-driver": "devicemapper" }`.  

Many thanks for your help, btw!

**Comment by pkos98** [comment]
thank you @sickcodes, now it works!  
Currently installing Xcode :).

**Comment by sickcodes** [comment]
No problem! I'll try and get to the bottom of the error you had

**Comment by pkos98** [comment]
Happy to help where I can, so don't hesitate to reach out if you need some information.  

Also, what's the admin user's password in the image you provided :D?

**Comment by sickcodes** [comment]
alpine


To get root just do `sudo su`

Password is alpine

And then change the password using `passwd`

You may need to change /etc/ssh/sshd_config and allow root login

Change permit root login to yes I think
