### ISSUE TITLE
After Big-Sur is installed, it starts very slowly every time. Is this normal?

### ISSUE THREAD

**Issue by lizhogn** [sickcodes/Docker-OSX#227]

**Comment by sickcodes** [comment]
Turn off automatic updates in settings because it's downloading updates and hogs the processor.

Mouse lags on first boot of Big Sur not sure why. Fixes on first reboot however.

You can post a video if you want

**Comment by lizhogn** [comment]
> Turn off automatic updates in settings because it's downloading updates and hogs the processor.
> 
> Mouse lags on first boot of Big Sur not sure why. Fixes on first reboot however.
> 
> You can post a video if you want

Ok, thanks very much. I will come back to feedback after in-depth experience

**Comment by sickcodes** [comment]
Please do :)

I have plans with the automated images I am working on a script over vnc to turn updates off and things like that

**Comment by lizhogn** [comment]
> Please do :)
> 
> I have plans with the automated images I am working on a script over vnc to turn updates off and things like that

okey, I will do it.
