### ISSUE TITLE
any reason you're using arch instead of alpine in Dockerfile?

### ISSUE THREAD

**Issue by chovy** [sickcodes/Docker-OSX#23]
Alpine is generally considered to be the best Linux distro for docker because its light weight.

**Comment by sickcodes** [comment]
When I began this project, some of the packages were not in mainstream repo, OVMF and virsh were only available in AUR, relative to the community repo. You can see my process here:  https://sick.codes/how-to-install-macos-virtual-machine-on-linux-arch-manjaro-catalina-mojave-or-high-sierra-xcode-working/ 

Also wanted to always have latest, or testing packages, in case something new comes out. The AUR guys are lightning fast. If we were going to compile all packages may as well rewrite it in Gentoo, which I’m open to the idea of as well!

If Alpine is better, then let’s change it, I just don’t can’t see the big reason to rewrite it other than simplify it currently.

Also nothing wrong that learning a new OS, I’m not your boss, but it’s good to play around in other distros. I’m a freelancer so knowing dpkg, rpm, apt-get, apt, yum, dnf, plus pacman, looks good!

**Comment by sickcodes** [comment]
I think we need alpine as I am unable to add systemd services in a simple fashion.

Alpine has `/etc/init.d/` which is much more desirable, I am keen to hear from others on this issue.

**Comment by sickcodes** [comment]
Hey @meal, I agree!
Arch also has a very up-to-date wiki when it comes to debugging issues, specifically virtualization.
