### ISSUE TITLE
docker: Error response from daemon: 

### ISSUE THREAD

**Issue by abjelosevic** [sickcodes/Docker-OSX#233]
Hi, when i start the  containter this error happens all the time:

docker: Error response from daemon: error gathering device information while add ing custom device "C": no such file or directory.

**Comment by sickcodes** [comment]
Sounds like you're trying to pass the entire C drive, can you check this issue: https://github.com/sickcodes/Docker-OSX/issues/37

**Comment by abjelosevic** [comment]
Basically this is only for Linux subsystem?
I have windows 10 with docker installed, want to try this but with no lack...
