### ISSUE TITLE
Can't install Xcode requires newer version of MacOS

### ISSUE THREAD

**Issue by peterandrewd** [sickcodes/Docker-OSX#24]
As the title says. Would some be kind enough to let me know how I can install Xcode to sideload apps?

**Comment by sickcodes** [comment]
Really? Let me check now and change to installed a newer build.

I will upload how I sideloaded my unc0ver shorty. It involved signing the release https://dantheman827.github.io/ios-app-signer/

And then installed using OTA plist method. I am not sure if you need a iOS Developer certificate to do OTA app installs by your phone's UUID, but it might.

**Comment by peterandrewd** [comment]
Ok thanks. That would be much appreciated.
Latest Xcode only supports newest Mac OS, and lower Xcode versions don't support iOS 13.5.
I have a developer account so I don't mind doing OTA install method.
Please let me know when you've changed it to a newer build.

**Comment by peterandrewd** [comment]
> Really? Let me check now and change to installed a newer build.
> 
> I will upload how I sideloaded my unc0ver shorty. It involved signing the release https://dantheman827.github.io/ios-app-signer/
> 
> And then installed using OTA plist method. I am not sure if you need a iOS Developer certificate to do OTA app installs by your phone's UUID, but it might.

how's the progress?

**Comment by sickcodes** [comment]
Yeah done, just testing out a new thing I did for the QEMU arguments so any argument can be modified with docker env args:

-e RAM
-e CORES
-e NFS_DISK
-e ROOT_PASS

Etc.

**Comment by peterandrewd** [comment]
> Yeah done, just testing out a new thing I did for the QEMU arguments so any argument can be modified with docker env args:
> 
> -e RAM
> -e CORES
> -e NFS_DISK
> -e ROOT_PASS
> 
> Etc.

Awesome. Love your work.
So to reinstall MacOS with the new image, follow the same steps as before?

**Comment by Extrememist** [comment]
Would love this rn xD

**Comment by sickcodes** [comment]
> > Yeah done, just testing out a new thing I did for the QEMU arguments so any argument can be modified with docker env args:
> > -e RAM
> > -e CORES
> > -e NFS_DISK
> > -e ROOT_PASS
> > Etc.
> 
> Awesome. Love your work.
> So to reinstall MacOS with the new image, follow the same steps as before?

I will include instructions (in the form of an automated shell script) how to migrate the img to the new container.

But regarding the new version, I would suggest doing the new actual box when I push it

**Comment by sickcodes** [comment]
New version will have the absolute works.

- CI/CD 1-click
- SHH tunneling
- VNC via SSH tunneling
- NFS/Samba Drives
- Optional arguments for pretty much every constant in the entire project (including upstream)
- Automated building -> sign -> push to developer devices via OTA App installs and submissions to App Store/Transport etc.

**Comment by sickcodes** [comment]
> Would love this rn xD

Hopefully tonight, just stocked up on Red Bull 😂

**Comment by peterandrewd** [comment]
> > Would love this rn xD
> 
> 
> 
> Hopefully tonight, just stocked up on Red Bull 😂

You the man!
Also include instructions for creating a new box for the new OS please

**Comment by Extrememist** [comment]
> 
> 
> > Would love this rn xD
> 
> Hopefully tonight, just stocked up on Red Bull 😂

Damn you, i just ran out XD

**Comment by peterandrewd** [comment]
So eagerly awaiting for the new instructions to run and sideload apps haha

**Comment by sickcodes** [comment]
> So eagerly awaiting for the new instructions to run and sideload apps haha

I’m pretty tired, got a few more things to check.

QEMU crashed unexpectedly, not sure why.

Here’s what I used to do the OTA update if you can’t wait: https://gist.github.com/hramos/774468

You need a domain with SSL, if you don’t want to buy anything just use a .tk domain + Lets Encrypt

Is the app signed yet?

**Comment by peterandrewd** [comment]
> > So eagerly awaiting for the new instructions to run and sideload apps haha
> 
> I’m pretty tired, got a few more things to check.
> 
> QEMU crashed unexpectedly, not sure why.
> 
> Here’s what I used to do the OTA update if you can’t wait: https://gist.github.com/hramos/774468
> 
> You need a domain with SSL, if you don’t want to buy anything just use a .tk domain + Lets Encrypt
> 
> Is the app signed yet?

Sorry for my lack of knowledge here but how do I use this script? What do I do exactly?

**Comment by sickcodes** [comment]
Here is an explanation, https://medium.com/@adrianstanecki/distributing-and-installing-non-market-ipa-application-over-the-air-ota-2e65f5ea4a46

Gotta finish some client work today unfortunately I won't be able to release v2 yet.

Will let everyone know ASAP, will post here and on my twitter http://twitter.com/sickcodes

**Comment by peterandrewd** [comment]
> Here is an explanation, https://medium.com/@adrianstanecki/distributing-and-installing-non-market-ipa-application-over-the-air-ota-2e65f5ea4a46
> 
> 
> 
> Gotta finish some client work today unfortunately I won't be able to release v2 yet.
> 
> 
> 
> Will let everyone know ASAP, will post here and on my twitter http://twitter.com/sickcodes

I’ve followed it to a tee. I can access my local server through my iPhone safari browser, I click the install link to the ipa I want to install and it just keeps asking me to open itunes. I have a developer account. Wtf am I doing wrong? I’m pretty frustrated

**Comment by peterandrewd** [comment]
Well I changed something and now the link does sweet fuck all.
Where am I supposed to put the ipa files so it can be added and accessed on my local host server?

**Comment by sickcodes** [comment]
Same directory.

It does require a valid SSL cert

So it cannot be http://localhost

It must be https:// and I am not sure because it alsoneeds a valid SSL certificate. I had been meaning to test IPA downloads with invalid or self signed certs, perhaps installing the certificate first, which should work but that’s why I mentioned .tk and let’s encrypt

Also the URL looks like this

 itms-services://?action=download-manifest&url=https://website.com/manifest.plist

**Comment by HexCodeFFF** [comment]
Would upgrading within the VM to Catalina work? 
![image](https://user-images.githubusercontent.com/35177464/84448567-a7a0aa00-ac10-11ea-879a-b32c52350584.png)

**Comment by HexCodeFFF** [comment]
It didnt work with the default storage amount BUT you can build the dockerfile with any version that [gibMacOS](https://www.tonymacx86.com/threads/gibmacos-tutorial-how-to-download-macos-catalina.295248/) supported

```
sudo docker build -t docker-osx:latest \
--build-arg VERSION=10.15.4 \
--build-arg SIZE=200G
```
then replace `sickcodes/docker-osx` with `docker-osx:latest` in your run command
```
sudo docker run --privileged -v /tmp/.X11-unix:/tmp/.X11-unix docker-osx:latest /bin/bash -c "sed -e 's/3072/8000/g' ./OpenCore-Boot.sh | sh -"
```
I currently haven't gotten to the desktop or installed xcode yet, but it did boot and it shows macOS Catalina on the install screen.

**Comment by sickcodes** [comment]
10.15.5 builds fine too.

Old version for stability, same reason LTS kernels exist.

**Comment by peterandrewd** [comment]
> It didnt work with the default storage amount BUT you can build the dockerfile with any version that [gibMacOS](https://www.tonymacx86.com/threads/gibmacos-tutorial-how-to-download-macos-catalina.295248/) supported
> 
> ```
> sudo docker build -t docker-osx:latest \
> --build-arg VERSION=10.15.4 \
> --build-arg SIZE=200G
> ```
> 
> then replace `sickcodes/docker-osx` with `docker-osx:latest` in your run command
> 
> ```
> sudo docker run --privileged -v /tmp/.X11-unix:/tmp/.X11-unix docker-osx:latest /bin/bash -c "sed -e 's/3072/8000/g' ./OpenCore-Boot.sh | sh -"
> ```
> 
> I currently haven't gotten to the desktop or installed xcode yet, but it did boot and it shows macOS Catalina on the install screen.
> 
> Edit: I installed Xcode and ran it

I get this error when inputting the above commands. I have downloaded Catalina from gibMacOS.
Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile

How to fix?

**Comment by HexCodeFFF** [comment]
Download the github repository, cd to it, and add a dot to the end iirc

**Comment by peterandrewd** [comment]
Now it does sweet fuck all. Doesn't load anything

**Comment by HexCodeFFF** [comment]
Guess I remembered wrong. I’m pretty sure you need the repo downloaded to
build it though. Google the errors I guess idk

**Comment by peterandrewd** [comment]
Really? That's your solution in trying to help? GTFO off here then.

**Comment by AubreyHewes** [comment]
@peterandrewd Unable to find image 'docker-osx:latest' literally... means you have no image downloaded at that tag name.. so check that it is available locally been built? `docker images`..

Your previous usage errors on `docker build` actually literally means you are probably not correctly copying the command proposed... i.e. missing a slash or such like.. 

Docker usage is not part of this repo.. linux/macos shell usage is not part of this repo..

**Comment by HexCodeFFF** [comment]
dude, I’m not the owner of the repo. I’m just posting what worked for me.
No need to be so rude

**Comment by peterandrewd** [comment]
> @peterandrewd Unable to find image 'docker-osx:latest' literally... means you have no image downloaded at that tag name.. so check that it is available locally been built? `docker images`..
> 
> Your previous usage errors on `docker build` actually literally means you are probably not correctly copying the command proposed... i.e. missing a slash or such like..
> 
> Docker usage is not part of this repo.. linux/macos shell usage is not part of this repo..
> 
> An error from a cli command telling you how to use the command is not an error. It is a user error.

well could someone be kind enough to give me a step by step guide?

**Comment by AubreyHewes** [comment]
@peterandrewd A step by step guide on how to use docker?

The image you are displaying is `sickcodes/docker-osx:latest` not `docker-osx:latest` (cf your error)... so  I assume you have missed a step?

**Comment by AubreyHewes** [comment]
@peterandrewd Possibly be kind enough to apologise to @HexCodeFFF as was only trying to help and there was no need for your type of reaction?

**Comment by peterandrewd** [comment]
> @peterandrewd A step by step guide on how to use docker? Or read directions?
> 
> The image you are displaying is `sickcodes/docker-osx:latest` not `docker-osx:latest` (cf your error)... so I assume you have missed a step?
> 
> Maybe just rename it and get on going?
> 
> Possibly be kind enough to apologise to @HexCodeFFF as was only trying to help and there was no need for your type of reaction?

Ok I apologise for how I spoke. I am just frustrated.
When I run docker run --privileged -e "DISPLAY=${DISPLAY:-:0.0}" -v /tmp/.X11-unix:/tmp/.X11-unix sickcodes/docker-osx:latest in theory whatever it's named, it should let me install Catalina. But it still says Mojave on the install screen.

**Comment by HexCodeFFF** [comment]
You have to run the build command successfully first, that’s where it
actually “changes” to Catalina.

**Comment by AubreyHewes** [comment]
@peterandrewd see docs on setting the version...

It is no excuse to talk as you did. Mention and apologize to @HexCodeFFF explicitly and not an off hand oh sorry.

The platform/software you are using is delivered by people. That you are frustrated ok. Keep that to yourself. Ask questions on how to alleviate your problem and be polite there within you can be frustrated.

The way you react. Determines how people see you.. You have a very shallow github profile (means nothing I know).. but such info added with your reactions also tells others what kind of person you are.

**Comment by peterandrewd** [comment]
> You have to run the build command successfully first, that’s where it actually “changes” to Catalina.

Ok so ive renamed sickcodes/docker-osx:latest to docker-osx:latest as I was meant to do. But when I copy and paste his above commands: sudo docker build -t docker-osx:latest \
--build-arg VERSION=10.15.4 \
--build-arg SIZE=200G
I get the same error: "docker build" requires exactly 1 argument.

**Comment by peterandrewd** [comment]
> @peterandrewd see docs on setting the version...
> 
> It is no excuse to talk as you did. Mention and apologize to @HexCodeFFF explicitly and not an off hand oh sorry.
> 
> The platform/software you are using is delivered by people. That you are frustrated ok. Keep that to yourself. Ask questions on how to alleviate your problem and be polite there within you can be frustrated.
> 
> The way you react. Determines how people see you.. You have a very shallow github profile (means nothing I know).. but such info added with your reactions also tells others what kind of person you are.

Noted. Ive apologised that's all I can do and won't do it again.

**Comment by AubreyHewes** [comment]
@peterandrewd You should apologize direct to the person you have been rude to. i.e. mention and apologize directly (which you have not done). A sign of respect and humility brings you a long way.

I have no time to tell you how to copy-paste commands in your shell...

If you do it correctly then you should not have a problem.. obviously you are not using the exact command...? i.e. missing slashes?

**Comment by peterandrewd** [comment]
> You have to run the build command successfully first, that’s where it
> actually “changes” to Catalina.
> 

I’m sorry for talking to you the way I did HexCode

**Comment by peterandrewd** [comment]
> > You have to run the build command successfully first, that’s where it
> > actually “changes” to Catalina.
> > 
> 
> I’m sorry for talking to you the way I did HexCode

Now can I please get some help with the codes

**Comment by AubreyHewes** [comment]
@peterandrewd You may be new to GitHub. To mention a person you first use a @.. this way you know that that person may receive your message. Within an issue you are autofilled with names who are in the issue.. why am i explaining this? .. then you can continue. I understand that you did apologise.. though as the person was not mentioned.. they may not ever know. They may be the only person that can help. Do you understand what I am saying?

**Comment by peterandrewd** [comment]
@HexCodeFFF  I am sorry for how I spoke to you. Please accept my apology it will not happen again.

**Comment by peterandrewd** [comment]
> @peterandrewd You may be new to GitHub. To mention a person you first use a @.. this way you know that that person may receive your message. Within an issue you are autofilled with names who are in the issue.. why am i explaining this? .. then you can continue. I understand that you did apologise.. though as the person was not mentioned.. they may not ever know. They may be the only person that can help. Do you understand what I am saying?

Yep understood. Still learning. Done.
But now can I please get some help regarding my codes and issue im having.

**Comment by AubreyHewes** [comment]
@peterandrewd what problem do you have? still the invalid docker command usage? did you put the complete command on one line and then use it?

**Comment by AubreyHewes** [comment]
@peterandrewd there are no "codes".. it is mostly knowledge.. asking to fix the "codes" is actually also very depressing.. you should probably ask the "codes" questions on stack or such like...

**Comment by peterandrewd** [comment]
> @peterandrewd what problem do you have? still the invalid docker command usage? did you put the complete command on one line and then use it?

just tried it on 1 line: sudo docker build -t docker-osx:latest \--build-arg VERSION=10.15.5 \--build-arg SIZE=200G
getting this error: unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/peter/docker-osx:latest/Dockerfile: no such file or directory

**Comment by AubreyHewes** [comment]
@peterandrewd Also it is generally regarded when someone gives a usable answer that the recipient says something.. also a new thing for you.. but as you are learning.. and know everything better I do not really care.

**Comment by peterandrewd** [comment]
> @peterandrewd Also it is generally regarded when someone gives a usable answer that the recipient says something.. also a new thing for you.. but as you are learning.. and know everything better I do not really care.

wtf? since when did I say I knew everything better?
I have done my due diligence and apologised directly.

**Comment by AubreyHewes** [comment]
@peterandrewd The error is a user error has nothing to do with this repo or any other repo. You should probably fix it or go to the Docker repo and ask there?

**Comment by peterandrewd** [comment]
> @peterandrewd The error is a user error has nothing to do with this repo or any other repo. You should probably fix it or go to the Docker repo and ask there?

alrightyyyy thennn

**Comment by AubreyHewes** [comment]
@peterandrewd It is just the attitude... no remorse.. fine. But that makes you who you are

**Comment by peterandrewd** [comment]
> @peterandrewd It is just the attitude... no remorse.. fine. But that makes you who you are

I do have remorse. I apologised and meant it. That to me is called remorse.

**Comment by AubreyHewes** [comment]
And I do not have a problem sharing knowledge.. You are welcome

**Comment by peterandrewd** [comment]
You know without me posting about the bug in the 1st place none of this would've even been known. So I think for that AND the fact that I did apologise several times, I deserve some help regarding what to do to boot into Catalina installer.

**Comment by sickcodes** [comment]
You’re still missing the dot at the end


docker build -t mylabel .

The dot means the directory that you are in, it is the missing argument.

`docker build -t docker-osx:latest 
--build-arg VERSION=10.15.4 
--build-arg SIZE=200G .`

**Comment by peterandrewd** [comment]
@sickcodes Error response from daemon: the Dockerfile (Dockerfile) cannot be empty
what is actually meant to be in the Dockerfile though?

**Comment by peterandrewd** [comment]
It’s the content in the dockerfile I don’t understand.

**Comment by ImranR98** [comment]
The Dockerfile should have some stuff in it from this repo. I was able to get xcode running with a few simple steps.
- First, clone this repo: `git clone https://github.com/sickcodes/Docker-OSX.git`
- cd into it: `cd Docker-OSX`
- Make sure you have all the dependencies: `sudo apt install qemu qemu-kvm libvirt-clients libvirt-daemon-system bridge-utils virt-manager` - this is the command using APT, check the README for others.
- Build a custom image. I used OSX 10.15.5 (latest) and a 64GB drive: `docker build -t docker-osx:latest --build-arg VERSION=10.15.5 --build-arg SIZE=64G .`
- Run `sudo chmod 666 /dev/kvm` - I had to do this, maybe you won't need to.
- Start the container: `docker run --privileged -e "DISPLAY=${DISPLAY:-:0.0}" -v /tmp/.X11-unix:/tmp/.X11-unix docker-osx`

All this can be found in the README, I don't get why you were showing attitude and acting like you "deserved" support for a free project someone is maintaining in their free time.

**Comment by peterandrewd** [comment]
>     * docker run --privileged -e "DISPLAY=${DISPLAY:-:0.0}" -v /tmp/.X11-unix:/tmp/.X11-unix docker-osx

I was simply very frustrated. I get my attitude wasn't right, and Ive done my due diligence for that.
I followed your steps and got this error: make: msgfmt: No such file or directory
make: *** [Makefile:150: po/pt.mo] Error 127
==> ERROR: A failure occurred in package().
    Aborting..

**Comment by ImranR98** [comment]
Hmm. Yeah I have no idea what that error means. Although I just realized after my last comment that he's uploaded a docker-compose file, which means that you shouldn't even need to clone and build the repo. Just download the docker-compose file, change the VERSION and SIZE params to your liking, then run `docker-compose up`. I was just able to get a working VM in a few minutes with that, none of the time consuming build process. Maybe worth a shot.

**Comment by peterandrewd** [comment]
Thank you. And to actually boot into the new build?

**Comment by ImranR98** [comment]
Not sure what you mean my 'to boot into the new build'. Were you able to run the docker-compose command? If it helps, maybe try starting fresh with a clean slate by deleting all your current containers and images you might have accumulated while troubleshooting.

**Comment by peterandrewd** [comment]
Yeah the docker compose command worked. Did its thing and then at the end gave me that error.

**Comment by peterandrewd** [comment]
Removed and pruned all docker images and still same error. See now I have a reason to be frustrated.

**Comment by ImranR98** [comment]
Hmm yeah I guess I'd be pretty frustrated too at this point. I can't help but wonder if there's something obvious you missed. How about taking screenshots of your whole process one command after the other up to the point you get stuck? Maybe sickcodes or someone else who knows their stuff can help further.

Also, forget the docker compose idea, doesn't seem to work after all (for me) but the clone and build method should.

**Comment by peterandrewd** [comment]
All screenshots at below link:
https://ufile.io/f/76ba1

**Comment by peterandrewd** [comment]
Anyone? My frustration level is a 9/10 right now. ANY immediate help would be appreciated

**Comment by qcasey** [comment]
I also ran into that make error for the record.

I think something in the Dockerfile needs to be tweaked but I'm not well versed enough here to do that.

@peterandrewd it might be a while until custom builds are working. If this is critical for some strange reason you may want to look at the original MacOS KVM repo this docker image is based on.

**Comment by peterandrewd** [comment]
I can get it to boot into Mojave installer using the docker-compose up command. But it’s still only Mojave.
The other command also still gives me the error

**Comment by qcasey** [comment]
Just saw #39, I'm on mobile but I will try a build without yay later today and post what comes out of that. It may help your original build issue.

I haven't tried docker-compose, can't speak to that

**Comment by peterandrewd** [comment]
> Just saw #39, I'm on mobile but I will try a build without yay later today and post what comes out of that. It may help your original build issue.
> 
> I haven't tried docker-compose, can't speak to that

thank you id really appreciate that

**Comment by qcasey** [comment]
> The Dockerfile should have some stuff in it from this repo. I was able to get xcode running with a few simple steps.
> - First, clone this repo: `git clone https://github.com/sickcodes/Docker-OSX.git`
> - cd into it: `cd Docker-OSX`
> - Make sure you have all the dependencies: `sudo apt install qemu qemu-kvm libvirt-clients libvirt-daemon-system bridge-utils virt-manager` - this is the command using APT, check the README for others.
> - Build a custom image. I used OSX 10.15.5 (latest) and a 64GB drive: `docker build -t docker-osx:latest --build-arg VERSION=10.15.5 --build-arg SIZE=64G .`
> - Run `sudo chmod 666 /dev/kvm` - I had to do this, maybe you won't need to.
> - Start the container: `docker run --privileged -e "DISPLAY=${DISPLAY:-:0.0}" -v /tmp/.X11-unix:/tmp/.X11-unix docker-osx`
> 
> All this can be found in the README, I don't get why you were showing attitude and acting like you "deserved" support for a free project someone is maintaining in their free time.

I removed yay and it built Catalina successfully. @peterandrewd try these great instructions above, but change the git clone to my fork for now. I'd also do a docker image prune if you haven't already.

`docker image prune
 git clone https://github.com/qcasey/Docker-OSX.git
...cd and the other instructions above`

**Comment by peterandrewd** [comment]
That worked! thank you so much. You are awesome

**Comment by peterandrewd** [comment]
@qcasey so I'm booted into Catalina. But it won't recognise my iPhone connected via USB. I need that to be able to sideload using Xcode.
Host OS (Linux) see's it, but not macOS on QEMU

**Comment by qcasey** [comment]
#36 mentions this, the solution is being worked on AFAIK

**Comment by HexCodeFFF** [comment]
Haven’t tested it yet, but you can add USB devices by editing open core
boot or whatever it’s called (see #38 )

**Comment by peterandrewd** [comment]
> Haven’t tested it yet, but you can add USB devices by editing open core boot or whatever it’s called (see #38 )

I found opencore.ssh but what parameters or text do I add?

**Comment by sickcodes** [comment]
Updated to Catalina for the original opened issued

SSH added

Ability to add USB via QEMU arg -e EXTRAS and -v of the volume folder
