### ISSUE TITLE
Im getting an error when im going for the simple method 

### ISSUE THREAD

**Issue by KeshavJ0shi** [sickcodes/Docker-OSX#257]
fish: ${ is not a valid variable in fish.
    -e "DISPLAY=${DISPLAY:-:0.0}" \

I have run: 

 docker run -it \
        --device /dev/kvm \
        -p 50922:10022 \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
        -e "DISPLAY=${DISPLAY:-:0.0}" \
        sickcodes/docker-osx:big-sur 

and also docker pull sickcodes/docker-osx:big-sur before that and all have installed all dependencies
![Screenshot_4](https://user-images.githubusercontent.com/43142500/115604724-53ba2380-a2ff-11eb-8aa4-d85350716403.png)

**Comment by iyadahmed** [comment]
I think you should use another shell, like bash, you shouldn't use fish as your default sh

**Comment by sickcodes** [comment]
You can just replace that variable with your display

Fish doesn't have shell substitutions from what you showed me which is a good point.

```
docker run -it 
--device /dev/kvm \
-p 50922:10022 \
-v /tmp/.X11-unix:/tmp/.X11-unix |
-e "DISPLAY=${DISPLAY}" \
sickcodes/docker-osx:big-sur 
```

**Comment by KeshavJ0shi** [comment]
Oh yes, so i did try it in endeavor with gnome and it worked 1st try, so yes the terminal also does matter
