### ISSUE TITLE
Hello, I'd like to ask about mount

### ISSUE THREAD

**Issue by longlong94** [sickcodes/Docker-OSX#259]
Hello, I think this project is good. I want to ask, I use naked to specify the Mac OS image. How can I get through the Mac OS to access the local CentOS directory? I have tried, but only CentOS can interact with the KVM container, but CentOS can't interact with the Mac OS file. Do you have any good suggestions, please

**Comment by sickcodes** [comment]
https://github.com/sickcodes/Docker-OSX/issues/242#issuecomment-820759859

**Comment by longlong94** [comment]
已经解决 感谢
