### ISSUE TITLE
Does not start the system

### ISSUE THREAD

**Issue by alicemtoyama** [sickcodes/Docker-OSX#264]
Hi,

When Big Sur finishes the installation, it does not appear MacOS Data, only MacOS Install.

Are there any restrictions for AMD Ryzen 9 processors?

**Comment by alicemtoyama** [comment]
ok

**Comment by sickcodes** [comment]
I also have Ryzen 9, and there are no issues, is everything ok now?

**Comment by victorMagalhaesPacheco** [comment]
Hi,

i also have the same problem, my processor is i5 8400 and does not show the MacOS Data option.
I tried several times, but it doesn't appear.
Version: Ubuntu 20.04 and docker 19.03..8

Thanks

**Comment by alicemtoyama** [comment]
Mine is an AMD Ryzen 9 ubuntu 20.04 64Bits and does not show MAC Data, only Install and does not leave the install screen. But I'm in no hurry for that, thank you all.

**Comment by victorMagalhaesPacheco** [comment]
> Mine is an AMD Ryzen 9 ubuntu 20.04 64Bits and does not show MAC Data, only Install and does not leave the install screen. But I'm in no hurry for that, thank you all.

I used with Catalina and it worked!

```bash
docker run -it \
    --device /dev/kvm \
    -p 50922:10022 \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    sickcodes/docker-osx:latest
```

Now i am upgrade to bigsur.

**Comment by sickcodes** [comment]
Working on it here: https://github.com/sickcodes/osx-serial-generator/pull/12

**Comment by sickcodes** [comment]
Please add the following lines and you will be able to boot Big Sur! 
```
    -e GENERATE_UNIQUE=true \
    -e MASTER_PLIST_URL=https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom.plist \
```
