### ISSUE TITLE
Is there a headless version for CICD?

### ISSUE THREAD

**Issue by JonasLaux** [sickcodes/Docker-OSX#27]
First of all, great work! 
I would like to build iOS apps in my CICD (bitbucket-pipelines) where i'm on something similar to TekTon i think. 
Currently we have a mac mini as a build server for our iOS apps. 
Would it possible to use this project somehow as a headless building container?

**Comment by sickcodes** [comment]
Hey Jonas!
Yes I am working on it today :)

**Comment by sickcodes** [comment]
Delayed due to work for some of my clients. If anyone wants to contribute, I am very open to pull requests!

**Comment by sickcodes** [comment]
SSH version is up now!
