### ISSUE TITLE
How to change resolution, activate pulse audio or enlarge ram?

### ISSUE THREAD

**Issue by derbrachialist** [sickcodes/Docker-OSX#278]
I have installed OSX successfully and now want to change the vm's resolution.
All I found was #35 and it redirects to #163. What am I supposed to do?

I would like to be able to use sound, how do I activate PulseAudio? The code on the front page does not help me, other than installing another docker:
```
docker run \
    --device /dev/kvm \
    -e AUDIO_DRIVER=pa,server=unix:/tmp/pulseaudio.socket \
    -v "/run/user/$(id -u)/pulse/native:/tmp/pulseaudio.socket" \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    sickcodes/docker-osx
```
Also, how do I add some more ram? 3 GB seems a bit low for me.

**Comment by tejasc0** [comment]
See the instructions to change resolution on readme file

**Comment by sickcodes** [comment]
Use naked now, see the readme to change container types
