### ISSUE TITLE
breaks on PopOS 20.04

### ISSUE THREAD

**Issue by luiscarbonell** [sickcodes/Docker-OSX#28]
## Recreating

- PopOS 20.04 (i.e. Ubuntu 20.04)
- Docker 19.03.9

## Issue

All commands seam to break because of an issue with KVM/QEMU or part of the build process...

This command got me the furthest:

```bash
docker run --privileged --net=host --cap-add=ALL -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev:/dev -v /lib/modules:/lib/modules sickcodes/docker-osx
```

But it gives me the following stack trace.... 🤷‍♂️ 

```
No protocol specified
Unable to init server: Could not connect: Connection refused
QEMU 5.0.0 monitor - type 'help' for more information
(qemu) ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
alsa: Could not initialize DAC
alsa: Failed to open `default':
alsa: Reason: Device or resource busy
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
alsa: Could not initialize DAC
alsa: Failed to open `default':
alsa: Reason: Device or resource busy
audio: Failed to create voice `dac'
gtk initialization failed
```

**Comment by sickcodes** [comment]
Upstream QEMU? Was it working for you yesterday? Have you done all the README fixes? There are some closed issues specific to Pop! OS

**Comment by sickcodes** [comment]
https://github.com/sickcodes/Docker-OSX/issues/4

**Comment by sickcodes** [comment]
Let me know if that fixed it @luiscarbonell and we can close this

**Comment by sickcodes** [comment]
> ## Recreating
> * PopOS 20.04 (i.e. Ubuntu 20.04)
> * Docker 19.03.9
> 
> ## Issue
> All commands seam to break because of an issue with KVM/QEMU or part of the build process...
> 
> This command got me the furthest:
> 
> ```shell
> docker run --privileged --net=host --cap-add=ALL -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev:/dev -v /lib/modules:/lib/modules sickcodes/docker-osx
> ```
> 
> But it gives me the following stack trace.... 🤷‍♂️
> 
> ```
> No protocol specified
> Unable to init server: Could not connect: Connection refused
> QEMU 5.0.0 monitor - type 'help' for more information
> (qemu) ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
> alsa: Could not initialize DAC
> alsa: Failed to open `default':
> alsa: Reason: Device or resource busy
> ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
> alsa: Could not initialize DAC
> alsa: Failed to open `default':
> alsa: Reason: Device or resource busy
> audio: Failed to create voice `dac'
> gtk initialization failed
> ```

Missing $DISPLAY please check the readme and you should be fine. POP OS seemed to be running on display :0 or :1 whereas many others on :0.0

This is solved by adding

`-e DISPLAY=${DISPLAY}`
