### ISSUE TITLE
is there a way to automatically select the boot disk

### ISSUE THREAD

**Issue by OliverwengFiltered** [sickcodes/Docker-OSX#286]
Hi there,

I have everything installed, but every time when boot it up, I need to select the correct disk to get into the system, any way I can automatically select the disk and get in ?

Appreciate any insights.
Thanks

**Comment by sickcodes** [comment]
```
    -e MASTER_PLIST_URL=https://raw.githubusercontent.com/sickcodes/Docker-OSX/master/custom/config-nopicker-custom.plist \
    -e GENERATE_UNIQUE=true \
```

**Comment by OliverwengFiltered** [comment]
@sickcodes 
Thank you !
