### ISSUE TITLE
maxcpu = 4, how do we increase the number

### ISSUE THREAD

**Issue by OliverwengFiltered** [sickcodes/Docker-OSX#287]
Hi @sickcodes ,

This docker-osx is really an awesome project, thanks for making it open source, engineering can't happen without this kinda of science project.

quick question about the cpu setting, when I'm trying to bring more cores by this `-e CORES=8 -e RAM=8` for example, it doesn't allow me, and it throws error saying maxcpu needs to be 4.

the reason why I'm trying to bring more cores is that I feel like it's a bit slow when I'm using it on GCP vm machine with 8vCPUs, and 32 mem. and then I tried the same with 16vCPUs, and 32 mem, not much difference on performance.

any idea how to bring the performance up a little bit ?

Thanks
-Oliver

**Comment by OliverwengFiltered** [comment]
wondering if you have any updates on this one ?

@sickcodes

**Comment by OliverwengFiltered** [comment]
nvm found it.
```
-smp 8,cores=8,sockets=1,threads=1,maxcpus=8
```
Thanks

**Comment by LiushuiXiaoxia** [comment]
how to use this options

`-smp 8,cores=8,sockets=1,threads=1,maxcpus=8`

@OliverwengFiltered  Thanks
