### ISSUE TITLE
stuck in EB.RH.LRHIP! Err(0XE) <- EB.LD.LF  EB.BST.FBS|! Err(0XE) <- EB.RH.LRH after docker run -it...

### ISSUE THREAD

**Issue by VictorLee0321** [sickcodes/Docker-OSX#294]
## OS base info
![image](https://user-images.githubusercontent.com/11787320/123046203-656a9500-d42e-11eb-8052-dc792b047922.png)
### I have other disk capability
![image](https://user-images.githubusercontent.com/11787320/123046778-1a04b680-d42f-11eb-8384-f04868f3c9aa.png)

## After run `docker run -it ...` and stuck in this windows
![image](https://user-images.githubusercontent.com/11787320/123046654-ef1a6280-d42e-11eb-92b4-2fb76e2522b8.png)

What's the problem, and how can I solve it ? THX.

**Comment by DiscordDigital** [comment]
I just ran into a similar looking issue, however this occurred after restarted my host and the container was working before the restart. 
Not sure what causes it.
![screen](https://user-images.githubusercontent.com/56228439/124306541-d3b60280-db66-11eb-9243-475b725ff60e.png)

**Comment by DiscordDigital** [comment]
> I just ran into a similar looking issue, however this occurred after I restarted my host and the container was working before the restart.
> Not sure what causes it.

Update: I just checked the README and ran "echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs" which fixed the issue for me, however I don't know if the original issue is related to this "solution".

**Comment by sickcodes** [comment]
> > I just ran into a similar looking issue, however this occurred after I restarted my host and the container was working before the restart.
> > Not sure what causes it.
> 
> Update: I just checked the README and ran "echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs" which fixed the issue for me, however I don't know if the original issue is related to this "solution".

This is a required command, and actually I had been missing it for a while, I will rearrange the documentation in a bit.

**Comment by VictorLee0321** [comment]
> "echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs"

yes, fixed it by setting this.

**Comment by qr4d** [comment]
> 

where to run this?
