### ISSUE TITLE
Screen resolution can not change.

### ISSUE THREAD

**Issue by ccb-github** [sickcodes/Docker-OSX#297]
It seems that whatever the HEIGHT, WIDTH I set at the "docker run" command, I get the same size of window at startup. However if I check the "zoom to fit" option, it could resize the window, as well as all the "zoom" option in the top menu bar. And when I enter the guest system. It only has one resolution available in **system preference>display** , so the inner window can display same amount of thing whatever. I think I face the same issue with sosumi, Yet another tool run mac in the kvm,

**Comment by sickcodes** [comment]
https://github.com/sickcodes/Docker-OSX#changing-display-resolution

**Comment by ccb-github** [comment]
Thanks, I did not realize this was on the mainpage, obviously I have not read it carefully. But I have a little question, is the **MASTER_PLIST_URL** setting needed for the resolution change to work.

**Comment by sickcodes** [comment]
Yeah so the plist URL creates boot disk at runtime, as opposed to using the existing one, which has 1920x1080

**Comment by ccb-github** [comment]
Hello again, I find myself stuck at  _request ...443 ... error,  curl 16 error in the HTTP2 framing laye_r kind of network error. And I did managed to download the image you provide and used it in **naked** image; and I update the system to big-sur successfully. But I was not fully understand the concept of **image** and **container**, and everytime I start the container use **docker run** command. For troubleshooting this problem, I even delete all the file under /var/lib/docker and reinstall docker. But I still facing this kind of network problem, I was wondering if  you could give me a hint.
