### ISSUE TITLE
Stuck at disk install selection step

### ISSUE THREAD

**Issue by paulsmith** [sickcodes/Docker-OSX#3]
The macOS installer starts up okay, but there is no option to install onto a disk that isn't locked.

![Screenshot from 2020-06-04 15-33-26](https://user-images.githubusercontent.com/1210/83807548-e36bca80-a678-11ea-8ba9-8bb6a850faec.png)

Invoked with:

docker run --privileged --net host --cap-add=ALL -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev:/dev -v /lib/modules:/lib/modules sickcodes/docker-osx

Machine info:

 OS: Debian 10 buster
 Kernel: x86_64 Linux 4.19.0-9-amd64
 CPU: Intel Core i5-8400 @ 6x 4GHz [44.0°C]
 GPU: Radeon RX 580 Series (POLARIS10, DRM 3.27.0, 4.19.0-9-amd64, LLVM 7.0.1)

**Comment by sickcodes** [comment]
Have you tried these?

```
# Boot the macOS Base System

# Click Disk Utility

# Erase the biggest disk

# Partition that disk and subtract 1GB and press Apply

# Click Reinstall macOS
```

**Comment by paulsmith** [comment]
That worked, ty.

![image](https://user-images.githubusercontent.com/1210/83813134-6cd3ca80-a682-11ea-8a5f-c3282f5b88d1.png)

**Comment by ntd94** [comment]
thank @sickcodes for your greate work. 
I haven't try macos before. So what to do next after the installation?

**Comment by sintaxx** [comment]
I was also wondering about this.... is it ok to erase these disks that show up in here? it wont affect my host will it? and it wont consume a 200+GB space will it? or does it work like a VM 'thin provision' disk ?

**Comment by tanmaster** [comment]
> I was also wondering about this.... is it ok to erase these disks that show up in here? it wont affect my host will it? and it wont consume a 200+GB space will it? or does it work like a VM 'thin provision' disk ?

I was wondering the same :-)

**Comment by sintaxx** [comment]
> > I was also wondering about this.... is it ok to erase these disks that show up in here? it wont affect my host will it? and it wont consume a 200+GB space will it? or does it work like a VM 'thin provision' disk ?
> 
> I was wondering the same :-)

Nope, I did it and it worked fine. It's just a qemu virtual disk. It's fine.

**Comment by sickcodes** [comment]
Yeah you don't even have to partition it, just erase the biggest disk and quit the disk utility

**Comment by livefromph** [comment]
> Have you tried these?
> 
> ```
> # Boot the macOS Base System
> 
> # Click Disk Utility
> 
> # Erase the biggest disk
> 
> # Partition that disk and subtract 1GB and press Apply
> 
> # Click Reinstall macOS
> ```

Fixed it for me

**Comment by NesredinJemal** [comment]
Thanks

**Comment by maietta** [comment]
I got stuck here too, finally got the OS installed only to restart my container and everything gone. (Wish the docs were just a bit more clear about this)
