### ISSUE TITLE
showing disk locked during installation

### ISSUE THREAD

**Issue by kndt** [sickcodes/Docker-OSX#30]
installation hangs while showing disk is locked

**Comment by sickcodes** [comment]
OS, disk type, drive space?

**Comment by kndt** [comment]
OS: Ubuntu 18.04
processor: AMD® Ryzen 5 3500u with radeon vega mobile gfx × 8
graphics: AMD® Raven
arch: 64bit
RAM: 8GB
disk: 250GB SSD

**Comment by sickcodes** [comment]
Did you partition the right disk? There are partition instructions in the readme
