### ISSUE TITLE
Stuck at installation stage

### ISSUE THREAD

**Issue by skyridertk** [sickcodes/Docker-OSX#300]
Hello I ran this

docker run -it \
    --device /dev/kvm \
    -p 50922:10022 \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    -e GENERATE_UNIQUE=true \
    -e MASTER_PLIST_URL=https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom.plist \
    sickcodes/docker-osx:big-sur

And formatted my largest qemu harddisk to APFS format which is about 214Gb. Virtualization is  enabled in the bios. And I have an i5 8th gen intel laptop with 24Gb ram. So it should be capable enough.

But it getting stuck at installation stage. It keeps showing 2 hours and 19 minutes remaining.....and the progress bar move at all. What might be the issue?
![Screenshot from 2021-07-01 08-00-06](https://user-images.githubusercontent.com/18192375/124073753-c273d580-da42-11eb-8162-352a019085bd.png)
![Screenshot from 2021-07-01 08-01-43](https://user-images.githubusercontent.com/18192375/124073766-c69ff300-da42-11eb-9555-4d5b85d004b9.png)
![Screenshot from 2021-07-01 08-01-52](https://user-images.githubusercontent.com/18192375/124073777-cacc1080-da42-11eb-8c34-e1b9ce049cec.png)

**Comment by sickcodes** [comment]
It will take a while to install, but that is correct.

Rarely, your IP address may be prevented from downloading the image.

Can you try with a VPN or proxy?

**Comment by sickcodes** [comment]
It also depends on your internet speed, right now I am installing and it's using 500Mbps

**Comment by skyridertk** [comment]
Ok. I understand

**Comment by lecoredump** [comment]
Hello, I just ran into the same issue, and it doesn't seem to come from anything network related (same behaviour on tethering and 4 different networks, with or without going through a VPN).

This also seems to affect the 3 different OSX versions available, the only difference between each one is the point where they get stuck (multiple attempts for each) :
- catalina : 7 minutes left
- big-sur & monterey : 43 minutes left

**Comment by triptec** [comment]
I'm trying to install big sur and I'm stuck here:
![Screenshot from 2021-09-15 15-51-25](https://user-images.githubusercontent.com/240159/133446086-44373d4b-08f8-4f80-ad37-017acd179ba6.png)

**Comment by sickcodes** [comment]
Some countries are not allowed to download: https://support.apple.com/en-us/HT204411

Can you try with a VPN?
