### ISSUE TITLE
run success and fail. And image size wired.

### ISSUE THREAD

**Issue by BackMountainDevil** [sickcodes/Docker-OSX#303]
# how i run Docker-OSX successfully?
all in #280 
I have successful run it this morning. erase disk\ reinstall os\ finally go into a OS screen to set language, keyboard. I can open app store or use  Safari to look Bilibili( youtube like). It eels very good ! you guys are do an amazing thing.

The install process really take a long time.. and I clear lots of cache(pacman, yay..) to get more disk usable.

```bash
$ docker images
REPOSITORY                  TAG       IMAGE ID       CREATED        SIZE
sickcodes/docker-osx        latest    87e0808867a0   5 weeks ago    3.09GB
dinghao188/rcore-tutorial   latest    779b0c88b284   4 months ago   1.17GB
```

# question 1
Thing get wired after I take a snap. When I run a again, everything turn back to zero. I need to do erase, disk partition, install agagin.. Is this normal ??? To see whether mac install or not. I use Filelight to see the size of /var/lib/docker is 47.9 G. and /var/lib/docker/overlay2 is 47.9G too.  /var/lib/docker/overlay2/e7ee801b954d13438a975ab2b228dbb858c2d8be7d95ca083dbeb141ac157b95 take 27.6G. Is this means that I have installed the mac? If it is so, why it just go into the os.

 # question 2
I erase the 200 G disk and divide a 60G to use. So it will suddenly use 60 G or just use a little at first then geteting bigger and bigger until 60G?

**Comment by sickcodes** [comment]
So the 47GB then you can use in the `:naked` image 

Move the 47GB image somewhere else, chown to $USER, and then:

```bash
docker run -it \
    --device /dev/kvm \
    -p 50922:10022 \
    -v "${PWD}/mac_hdd_ng_auto.img:/image" \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    sickcodes/docker-osx:naked
```

**Comment by sickcodes** [comment]
Second question, yes qcow2 grows as the system grows.

However, APFS Big Sur starts at 40GB.


You can reduce the image size here: https://github.com/sickcodes/Docker-OSX#tips-for-reducing-the-size-of-the-image

**Comment by BackMountainDevil** [comment]
Thank for your answer. That is very helpful.
