### ISSUE TITLE
Wiki "initial-setup" suggestion

### ISSUE THREAD

**Issue by CoreyVidal** [sickcodes/Docker-OSX#311]
Hey,

I'm unfortunately a script-kiddie, so when I talk about things, please don't think that anything I have to say comes with any expertise. I'm familiar with Docker and run about 20 containers, but I don't know how things _actually_ work. Let me describe my issue/suggestion:

I'm following along with https://github.com/sickcodes/Docker-OSX#initial-setup  
I did everything as recommended, but failed almost right away. I'm on Ubuntu and thus ran

`sudo apt install qemu qemu-kvm libvirt-clients libvirt-daemon-system bridge-utils virt-manager`

Then I wanted to generate serials, so went into the /custom folder and ran:

`sudo ./generate-unique-machine-values.sh --count 1 --plists --bootdisks --envs`

And something went wrong:

```
./opencore-image-ng.sh: line 121: guestfish: command not found
ERROR: starting guestfish failed
### cleaning up ...
```

I tried running:

`sudo apt install guestfish`

But that's not a thing. Luckily, Ubuntu told me to install libguestfs-tools. So I ran 

`sudo apt install libguestfs-tools`

After it installed I started the process over from the beginning, and it worked properly.

So I don't know what I did (script-kiddie), but I do like being helpful. I came to write this post and then ask/suggest that you might want to add libguestfs-tools to the instructions. You'd add it in here:

```
# UBUNTU DEBIAN
sudo apt install qemu qemu-kvm libvirt-clients libvirt-daemon-system bridge-utils virt-manager
```

It could help dumbasses like me.

And if not, I wrote this in a way that hopefully Google picks it up, and maybe others having issues might one day stumble upon this. You never know!

**Comment by sickcodes** [comment]
Good idea, adding now!
