### ISSUE TITLE
visual display

### ISSUE THREAD

**Issue by alicera** [sickcodes/Docker-OSX#317]
I have two computers. And A computer install the docker-OSX.
I try to ssh -X A@127.0.0.2 and command  
docker run -it --device /dev/kvm -p 50923:10022 -v /tmp/.X11-unix:/tmp/.X11-unix -e "DISPLAY=${DISPLAY:-:0.0}" sickcodes/docker-osx:auto
with B computer.

How can I use the B computer to open the visual display in A computer？

ssh: connect to host 127.0.0.1 port 10022: Connection refused
Disk is being copied between layers. Repeating until able to copy SSH key into OSX...
/usr/sbin/ssh-copy-id: INFO: Source of key(s) to be installed: "/home/arch/.ssh/id_docker_osx.pub"

**Comment by sickcodes** [comment]
You can use VNC to access from another computer: https://github.com/sickcodes/Docker-OSX#building-a-headless-container-which-allows-insecure-vnc-on-localhost-for-local-use-only
