### ISSUE TITLE
Mount external usb disk? 

### ISSUE THREAD

**Issue by reini1989** [sickcodes/Docker-OSX#34]
Is there a possibility to mount external hard drives? Automatically it doesn't seem to work.

My goal is to access/explore my old time machine disk.

Running from Ubuntu.

Thanks

**Comment by sickcodes** [comment]
I wouldn't risk it, but you can use -v /directory:/directory

and then pass -e EXTRA "some qemu volume arg for /directory:/guest"

**Comment by miwgmail** [comment]
Hi iam miw from Thailand and I donknow how I play
