### ISSUE TITLE
Resolution change

### ISSUE THREAD

**Issue by kgorol** [sickcodes/Docker-OSX#35]
Is there any way to change resolution?

**Comment by sickcodes** [comment]
Use the ./boot-macOS-HS.sh argument at the end of your docker run command. It will launch 1000x1000

**Comment by kgorol** [comment]
I have 4K monitor and if I would like to launch it at 2560×1440 resolution is there any way to do this?

**Comment by weaming** [comment]
> Use the ./boot-macOS-NG.sh argument at the end of your docker run command. It will launch 1000x1000

So what's the detail extra options?

**Comment by sickcodes** [comment]
> > Use the ./boot-macOS-NG.sh argument at the end of your docker run command. It will launch 1000x1000
> 
> 
> 
> So what's the detail extra options?

You can use any QEMU command line arguments there

https://www.qemu.org/docs/master/system/index.html

Resolution is controlled via OpenCore: https://github.com/kholia/OSX-KVM

**Comment by taishi8117** [comment]
has anyone figured out what qemu arguments to specify?

**Comment by sickcodes** [comment]
Resolution is controlled here now: https://github.com/sickcodes/Docker-OSX/blob/master/custom/config-nopicker-custom.plist#L819

Follow these steps:

https://github.com/sickcodes/Docker-OSX/issues/156

https://github.com/sickcodes/Docker-OSX#serial-numbers

**Comment by sickcodes** [comment]
Specifically,
```bash
git clone https://github.com/sickcodes/Docker-OSX.git
cd ./Docker-OSX
sed -i -e s/1920x1080/new/ ./custom/config-nopicker-custom.plist
./custom/generate-unique-machine-values.sh \
        --custom-plist ./custom/config-nopicker-custom.plist
        --count 1 \
        --tsv ~/my_permanent_serial_number.tsv \
        --output-env ~/my_permanent_serial_number.sh
```

**Comment by sickcodes** [comment]
I'm adding x and y resolution to the docker arguments

**Comment by sickcodes** [comment]
https://github.com/sickcodes/Docker-OSX/pull/163

Untested yet, but its here

**Comment by sickcodes** [comment]
Added https://github.com/sickcodes/Docker-OSX/pull/163

Examples: https://github.com/sickcodes/Docker-OSX#change-docker-osx-resolution-examples
