### ISSUE TITLE
Current builds broken 

### ISSUE THREAD

**Issue by sickcodes** [sickcodes/Docker-OSX#370]
![Screenshot_2021-10-30_05-31-54](https://user-images.githubusercontent.com/65906298/139522061-9fdb30fb-fe15-4356-a358-d98e20bdb9d8.png)

Will fix in the morning

**Comment by spouradrix** [comment]
Hi I used this command just now:

`sudo docker run -it     --device /dev/kvm     -p 50922:10022     -v /tmp/.X11-unix:/tmp/.X11-unix     -e "DISPLAY=${DISPLAY:-:0.0}"     -e GENERATE_UNIQUE=true     -e MASTER_PLIST_URL='https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom.plist'     sickcodes/docker-osx:monterey`

Am I wasting my time waiting for the download?

**Comment by bbeckkk** [comment]
Please let us know when it is fixed...

**Comment by sickcodes** [comment]
Fixing now @bbeckkk

**Comment by sickcodes** [comment]
Fixed, pushing new images

**Comment by sickcodes** [comment]
Problems were:

Typo in Opencore OpenCore (moved upstream)

https://github.com/sickcodes/Docker-OSX/commit/0a0ae76333ef26aeb8762a18efa7d069684d3615

Hard failing on anything libguestfs so it will not push new images:

https://github.com/sickcodes/Docker-OSX/commit/50c87a4bac573e3d2516b857f2fd72aa496c5356

Lastly, logic related to building guestfs', inside of Docker, without really having linux:

https://github.com/sickcodes/Docker-OSX/commit/e6fcfd86dbbb9854ceefe82b49b957edfa19c52b

Pushing images

**Comment by bbeckkk** [comment]
![Screenshot_2021-10-31_02-05-43](https://user-images.githubusercontent.com/56904369/139570443-d75c0373-316f-41d0-99fd-674f37f23681.png)

**Comment by takov751** [comment]
Checked it seems like the OSX serial generater messes up the bootdisk creation weird

**Comment by sickcodes** [comment]
Yeah I think it's the kext/OCI Folder. Let me try OSX-KVM's new plist

**Comment by sickcodes** [comment]
Works fine, so it should be my qcow

**Comment by takov751** [comment]
> Upstream works fine, so it should be my qcow, moment, fixed in https://github.com/sickcodes/osx-serial-generator/commit/e024505db8f61e769936d21416c9ba3ab2293047

Nice thanks will test it

**Comment by sickcodes** [comment]
![Screenshot_2021-10-31_16-39-58](https://user-images.githubusercontent.com/65906298/139593609-9f0884c8-1a52-425b-b765-85d38584311a.png)

Lovely
