### ISSUE TITLE
big-sur shows blank screen in QEMU

### ISSUE THREAD

**Issue by bbeckkk** [sickcodes/Docker-OSX#371]
After downloaing the image for bug-sur, it shows nothing except choose the operating system text

![Screenshot_2021-10-31_00-52-20](https://user-images.githubusercontent.com/56904369/139568538-49b5ca01-677f-443e-bc2b-9614fa2a8686.png)

**Comment by sickcodes** [comment]
Yeah I'm aware, give me a few hours

**Comment by sickcodes** [comment]
Fixed!

![Screenshot_2021-10-31_16-39-58](https://user-images.githubusercontent.com/65906298/139593602-e081b276-b23e-4a6c-a3cd-961597d80b42.png)

**Comment by bbeckkk** [comment]
It works now but big-sur installs monterey and then if the installation is continued, it gets stuck.

![monteryStucks](https://user-images.githubusercontent.com/56904369/139614568-0c016736-a0cb-4ac3-a725-84db3fdf3026.png)
