### ISSUE TITLE
Installing Monterey instead of Big Sur

### ISSUE THREAD

**Issue by spouradrix** [sickcodes/Docker-OSX#373]
Hi,

I used this command:
`sudo docker run -it \
    --device /dev/kvm \
    -p 50922:10022 \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    -e RAM=8 \
    -e CPU_STRING=$(nproc) \
    sickcodes/docker-osx:big-sur`

and when booting and installing OS X, it prompts me to install Monterey, why is this?

**Comment by sickcodes** [comment]
Yeah I just noticed also, latest is not `big-sur` anymore

**Comment by sickcodes** [comment]
Will add high-sierra and mojave while I'm at it

```
 #    ProductID    Version   Post Date  Title
 1    061-26578    10.14.5  2019-10-14  macOS Mojave
 2    061-26589    10.14.6  2019-10-14  macOS Mojave
 3    041-91758    10.13.6  2019-10-19  macOS High Sierra
 4    041-88800    10.14.4  2019-10-23  macOS Mojave
 5    041-90855    10.13.5  2019-10-23  Install macOS High Sierra Beta
 6    061-86291    10.15.3  2020-03-23  macOS Catalina
 7    001-04366    10.15.4  2020-05-04  macOS Catalina
 8    001-15219    10.15.5  2020-06-15  macOS Catalina
 9    001-36735    10.15.6  2020-08-06  macOS Catalina
10    001-36801    10.15.6  2020-08-12  macOS Catalina
11    001-51042    10.15.7  2020-09-24  macOS Catalina
12    001-57224    10.15.7  2020-10-27  macOS Catalina
13    001-68446    10.15.7  2020-11-11  macOS Catalina
14    071-72781     11.5.1  2021-07-26  macOS Big Sur
15    071-78704     11.5.2  2021-08-18  macOS Big Sur
16    071-97382       11.6  2021-09-17  macOS Big Sur
17    002-23774     12.0.1  2021-10-25  macOS Monterey
```

**Comment by sickcodes** [comment]
Fixing plus adding High Sierra and Mojave, via https://github.com/sickcodes/Docker-OSX/pull/374

In addition, submitted: https://github.com/kholia/OSX-KVM/pull/185 upstream to allow simple versioning

**Comment by sickcodes** [comment]
`--build-arg SHORTNAME=mojave`
`--build-arg SHORTNAME=big-sur`
`--build-arg SHORTNAME=monterey`
`--build-arg SHORTNAME=catalina`
`--build-arg SHORTNAME=high-sierra` 

I would like some feedback on the proposed changes

**Comment by sickcodes** [comment]
This was fixed, thanks for the patiences btw!

**Comment by Ayuubgaajo** [comment]
> Will add high-sierra and mojave while I'm at it
> 
> 
> 
> ```
> 
>  #    ProductID    Version   Post Date  Title
> 
>  1    061-26578    10.14.5  2019-10-14  macOS Mojave
> 
>  2    061-26589    10.14.6  2019-10-14  macOS Mojave
> 
>  3    041-91758    10.13.6  2019-10-19  macOS High Sierra
> 
>  4    041-88800    10.14.4  2019-10-23  macOS Mojave
> 
>  5    041-90855    10.13.5  2019-10-23  Install macOS High Sierra Beta
> 
>  6    061-86291    10.15.3  2020-03-23  macOS Catalina
> 
>  7    001-04366    10.15.4  2020-05-04  macOS Catalina
> 
>  8    001-15219    10.15.5  2020-06-15  macOS Catalina
> 
>  9    001-36735    10.15.6  2020-08-06  macOS Catalina
> 
> 10    001-36801    10.15.6  2020-08-12  macOS Catalina
> 
> 11    001-51042    10.15.7  2020-09-24  macOS Catalina
> 
> 12    001-57224    10.15.7  2020-10-27  macOS Catalina
> 
> 13    001-68446    10.15.7  2020-11-11  macOS Catalina
> 
> 14    071-72781     11.5.1  2021-07-26  macOS Big Sur
> 
> 15    071-78704     11.5.2  2021-08-18  macOS Big Sur
> 
> 16    071-97382       11.6  2021-09-17  macOS Big Sur
> 
> 17    002-23774     12.0.1  2021-10-25  macOS Monterey
> 
> ```

@sickcodes

**Comment by sickcodes** [comment]
Would you rather product ID download or using just "big-sur"
