### ISSUE TITLE
Bigsur machine can not boot (Halting on critical error)

### ISSUE THREAD

**Issue by osmankibar** [sickcodes/Docker-OSX#375]
Hi,

Bigsur machine can not boot. When I try my local machine, there is an error like this 

 OCS: Failed to parse string field as value with type boolean and <Disabled> contents, context >GopPassThrough>!
 OCS: No schema for AppleEg2Info at 3 index, context <ProtocolOverrides>!
 OCS: No schema for EnableVectorAcceleration at 2 index, context <Quirks>!
 OCS: No schema for  ForceOcWriteFlash at 4 index, context <Quirks>!
 OCS: No schema for ReloadOptionsRoms at 8 index, context <Quirks>!
 OC: Driver at 0 cannot be found!;
 Halting on critical error

# OS related issued, please help us identify the issue by posting the output of this
uname -a \
; echo "${DISPLAY}" \
; echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs \
; grep NAME /etc/os-release \
; df -h . \
; qemu-system-x86_64 --version \
; libvirtd --version \
; free -mh \
; nproc \
; egrep -c '(svm|vmx)' /proc/cpuinfo \
; ls -lha /dev/kvm \
; ls -lha /tmp/.X11-unix/ \
; ps aux | grep dockerd \
; docker ps | grep osx \
; grep "docker\|kvm\|virt" /etc/group

1
NAME="Ubuntu"
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p2  916G  522G  348G  61% /
QEMU emulator version 4.2.1 (Debian 1:4.2-3ubuntu6.18)
Copyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers
libvirtd (libvirt) 6.0.0
              total        used        free      shared  buff/cache   available
Mem:           62Gi       9,1Gi        45Gi       369Mi       7,8Gi        52Gi
Swap:         2,0Gi          0B       2,0Gi
24
24
crw-rw----+ 1 root kvm 10, 232 Kas  1 10:19 /dev/kvm
total 124K
drwxrwxrwt  2 root root 4,0K Kas  1 08:44 .
drwxrwxrwt 32 root root 116K Kas  1 10:23 ..
srwxrwxrwx  1 root root    0 Kas  1 08:44 X0
srwxrwxrwx  1 root root    0 Kas  1 08:44 X1
root        2869  0.0  0.1 9500528 91108 ?       Ssl  08:44   0:05 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
myuser     35344  0.0  0.0  11780  2680 pts/8    S+   10:23   0:00 grep --color=auto dockerd
aa415c0b1a58   sickcodes/docker-osx:naked      "/bin/bash -c 'sudo …"   17 minutes ago   Up 4 minutes   0.0.0.0:50923->10022/tcp, :::50923->10022/tcp   scripts_osx1_1
kvm:x:108:myuser
docker:x:998:myuser
libvirt:x:137:myuser
libvirt-qemu:x:64055:libvirt-qemu
libvirt-dnsmasq:x:138:

**Comment by harguus** [comment]
I have the same mistake, it started from yesterday to today.

**Comment by harguus** [comment]
I have the same mistake, it started from yesterday to today.
from what I saw in the log and searching there is a problem in the Alsa audio driver:

```
(qemu) ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5111:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5111:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5111:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5599:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
alsa: Could not initialize DAC
alsa: Failed to open `default':
alsa: Reason: No such file or directory
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5111:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5111:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5111:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5599:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
alsa: Could not initialize DAC
alsa: Failed to open `default':
alsa: Reason: No such file or directory
audio: Failed to create voice `dac'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5111:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5111:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5111:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5599:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
alsa: Could not initialize ADC
alsa: Failed to open `default':
alsa: Reason: No such file or directory
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5111:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5111:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5111:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5599:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
alsa: Could not initialize ADC
alsa: Failed to open `default':
alsa: Reason: No such file or directory
audio: Failed to create voice `adc'
```

**Comment by sangdrax8** [comment]
I have been booting BigSur for a few months, and just now ran into this as well.  I did do a system update recently, but not really sure where to start troubleshooting this?

**Comment by osmankibar** [comment]
I updated the image today and now it is booting. I don't know what happens but I will close the issue.

**Comment by harguus** [comment]
> I updated the image today and now it is booting. I don't know what happens but I will close the issue.

How did you do it? I'm trying to recreate the container as it says in the doc and I keep getting the same error.

`
docker run -it --device /dev/kvm -p 50922:10022 -e GENERATE_UNIQUE=true -e DEVICE_MODEL="iMacPro1,1" -e RAM=6 -e WIDTH=1280 -e CORES=4 -e HEIGHT=768 -v /tmp/.X11-unix:/tmp/.X11-unix -e "DISPLAY=${DISPLAY:-:0.0}" sickcodes/docker-osx:big-sur`

**Comment by sickcodes** [comment]
Hey guys, yesterday the images were busted: https://github.com/sickcodes/Docker-OSX/issues/370

Just docker pull the new ones, will test naked right now anyway

**Comment by sickcodes** [comment]
`docker pull sickcodes/docker-osx:naked`

**Comment by harguus** [comment]
> Hey guys, yesterday the images were busted: #370
> 
> Just docker pull the new ones, will test naked right now anyway

I'm using the Big Sur image and it still has the same error, first I did it docker pull sickcodes/docker-osx:big-sur it didn't work, then I did it docker pull sickcodes/docker-osx:naked and it continues the same way, with the same error.

**Comment by harguus** [comment]
This command, which is in the doc, also gives the same error.

`docker run -it \
    --device /dev/kvm \
    -p 50922:10022 \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    sickcodes/docker-osx:big-sur

# docker build -t docker-osx -e VERSION='Big Sur' .
`

**Comment by sickcodes** [comment]
> I have the same mistake, it started from yesterday to today. from what I saw in the log and searching there is a problem in the Alsa audio driver:
> 
> My version: `Advanced Linux Sound Architecture Driver Version k5.4.0-89-generic.`
> 
> SO: `Linux Mint 20.2 Cinnamon`
> 
> Kernel: `5.4.0-89-generic`
> 
> ```
> (qemu) ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
> ALSA lib conf.c:5111:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
> ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
> ALSA lib conf.c:5111:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
> ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
> ALSA lib conf.c:5111:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
> ALSA lib conf.c:5599:(snd_config_expand) Evaluate error: No such file or directory
> ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
> alsa: Could not initialize DAC
> alsa: Failed to open `default':
> alsa: Reason: No such file or directory
> ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
> ALSA lib conf.c:5111:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
> ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
> ALSA lib conf.c:5111:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
> ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
> ALSA lib conf.c:5111:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
> ALSA lib conf.c:5599:(snd_config_expand) Evaluate error: No such file or directory
> ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
> alsa: Could not initialize DAC
> alsa: Failed to open `default':
> alsa: Reason: No such file or directory
> audio: Failed to create voice `dac'
> ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
> ALSA lib conf.c:5111:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
> ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
> ALSA lib conf.c:5111:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
> ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
> ALSA lib conf.c:5111:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
> ALSA lib conf.c:5599:(snd_config_expand) Evaluate error: No such file or directory
> ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
> alsa: Could not initialize ADC
> alsa: Failed to open `default':
> alsa: Reason: No such file or directory
> ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
> ALSA lib conf.c:5111:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
> ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
> ALSA lib conf.c:5111:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
> ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
> ALSA lib conf.c:5111:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
> ALSA lib conf.c:5599:(snd_config_expand) Evaluate error: No such file or directory
> ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
> alsa: Could not initialize ADC
> alsa: Failed to open `default':
> alsa: Reason: No such file or directory
> audio: Failed to create voice `adc'
> ```

There should be an error just above this, as that is all normal output in the context of Docker OSX
