### ISSUE TITLE
Where is OpenCore-Boot.sh?

### ISSUE THREAD

**Issue by HexCodeFFF** [sickcodes/Docker-OSX#38]
[This comment](https://sick.codes/how-to-install-macos-virtual-machine-on-linux-arch-manjaro-catalina-mojave-or-high-sierra-xcode-working/#comment-41151) says it's in `/home/user/OSX-KVM/OpenCore-Boot.sh` but there isn't even a `OSX-KVM` directory in my home dir. I'm trying to edit it to add a usb device.

**Comment by sickcodes** [comment]
It’s inside the docker container.

You can physically edit that file by running the container with /bin/bash and then editing it manually.

I should add vim and nano in the next version but you can install once you’re inside using

`sudo pacman -syu vim nano `

**Comment by sickcodes** [comment]
You can also find it in /var/lib/docker.... if you want to edit it outside of the machine.

Make sure the container is off when you edit that file, it bugs out otherwise.
