### ISSUE TITLE
I cannot share a folder. What do I do?

### ISSUE THREAD

**Issue by q351941406** [sickcodes/Docker-OSX#394]
Appears after a command is run on macOS
mount_9p: fs_tag hostshare not found

docker run -i \
    --device /dev/kvm \
    -p 50922:10022 \
    -p 5999:5999 \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v "$PWD/hostshare:/mnt/hostshare" \
    -e EXTRA="-virtfs local,path=/mnt/hostshare,mount_tag=hostshare,security_model=passthrough,id=hostshare" \
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    -e EXTRA="-display none -vnc 0.0.0.0:99,password=on" \
    sickcodes/docker-osx:auto

**Comment by trompx** [comment]
@q351941406 may I know how you solved this. I have the same problem, the shared folder is not mounted?
