### ISSUE TITLE
Microphone not working

### ISSUE THREAD

**Issue by mikob** [sickcodes/Docker-OSX#403]
Anyway to get the microphone input working? I see "no input devices found" under sound > input.

**Comment by mikob** [comment]
If not the internal mic, is it possible to get a USB mic working?

**Comment by sickcodes** [comment]
USB microphone works fine, you can do USB pass-through or usbredir, like this:

https://github.com/sickcodes/Docker-OSX#mount-usb-drive-hotplughot-plug-usb

**Comment by mikob** [comment]
@sickcodes that worked! BTW, honor to be your first sponsor :1st_place_medal:  (as LipSurf) Appreciate the project!

**Comment by sickcodes** [comment]
> @sickcodes that worked! BTW, honor to be your first sponsor :1st_place_medal:  (as LipSurf) Appreciate the project!

You're welcome and thank you very, very much! ❤️😁
