### ISSUE TITLE
reach the localhost from inside docker-osx

### ISSUE THREAD

**Issue by alexerisov** [sickcodes/Docker-OSX#424]
I wanna open localhost webserver in safari inside docker-osx. How can i do that?

**Comment by sickcodes** [comment]
Local webhost webserver example for safari inside Docker-OSX right here :)

https://github.com/sickcodes/Docker-OSX#forward-additional-ports-nginx-hosting-example

**Comment by alexerisov** [comment]
Yes, I've seen it, but this example describes how to start nginx in docker-osx and get it from localhost. But I wanna to start server on Local host and get it from inside docker-osx. I got problem that server and docker-osx require the same port on host machine. If I started server on 10024, Docker cannot start with same port. And if docker starts first, then server can't start.

**Comment by sickcodes** [comment]
From inside the mac, you can reach 192.168.1.x naturally.

On host:
`nginx` will start on 80
`ip addr` will show all your IP's and bridges, which are localhost.

For me, I can visit the host on any of:

172.17.0.1
172.16.32.1
192.168.63.1
192.168.122.1
192.168.1.4

**Comment by alexerisov** [comment]
Yep, It works. Thanks, you. I had tried 127.0.0.1:3000 and localhost:3000, and it had not worked. But as you advice 172.17.. and 192.168 works now. Thanks again )
