### ISSUE TITLE
Windows users

### ISSUE THREAD

**Issue by Hoopex** [sickcodes/Docker-OSX#426]
Hello everyone
Can you please help me with clear instructions for windows with WSL 2 & Docker desktop 
I tried everything on README but I think I miss something 
Thanks.

**Comment by leixdd** [comment]
I am also new to Docker OSX and took me a while installing it in Windows.
Currently, I am now installing.

![image](https://user-images.githubusercontent.com/8527882/150270350-1aebb9a3-0d07-42fe-8b12-c9af42ea9251.png)

May I know what problem that you have encountered? Maybe I could help?

**Comment by Hoopex** [comment]
@leixdd
To be honest, I don't know how to get started at all
Thank you for the reply

**Comment by leixdd** [comment]
@Hoopex 

Honestly, I only follow this part of Readme.md
https://github.com/sickcodes/Docker-OSX#id-like-to-run-docker-osx-on-windows

Did you already have a distro in your wsl?

**Comment by sickcodes** [comment]
A PR was merged last night with added Windows instructions:

https://github.com/sickcodes/Docker-OSX#id-like-to-run-docker-osx-on-windows

Let me know if there's any issues

**Comment by MDeev** [comment]
@leixdd @sickcodes 
Yeah, I have Ubuntu 20.04 installed but i keep getting **Can't open display** with wslg
and (qemu) gtk initialization failed with **VNC**

**Comment by leixdd** [comment]
@MDeev 

I also encounter that in WSLG. 
So I use VcXsrv (https://www.makeuseof.com/tag/linux-desktop-windows-subsystem)

**Comment by Hoopex** [comment]
@leixdd & @sickcodes 
Thank you guys, I fixed the issue using the steps on this articles
https://medium.com/@japheth.yates/the-complete-wsl2-gui-setup-2582828f4577
kinda same as @leixdd  mentioned but with extra steps like xubuntu-desktop, etc..

Thanks
