### ISSUE TITLE
Xvfb missing from image

### ISSUE THREAD

**Issue by johnf** [sickcodes/Docker-OSX#446]
I think the upstream arch image may have changed and is breaking things.

Xvfb is missing
```
nohup: failed to run command 'Xvfb': No such file or directory
```

If I install manually using pacman like the DOckerfile does I get an error about a conflixt between two different xfat packages

If I then install manually supermin has issues with the kernel version. The Dockerfiles reference 5.14 but the underlying image has 5.16 installed.

**Comment by AdoPi** [comment]
Same issue here, did you find a workaround?

**Comment by johnf** [comment]
I built the docker images from source, which seems to work fine. :shrug:

**Comment by johnf** [comment]
The latest builds are fine.
Given it was only a README change, and it worked fine built locally, I suspect it was an issue with what was pushed to Docker Hub.

**Comment by sickcodes** [comment]
Xvfb comes with `xorg-server-xvfb`

supermin and libguestfs are the biggest headache ever we have to use an old version.

Is every Gucci again on 5.16?
