### ISSUE TITLE
How to run installed catalina on boot qemu

### ISSUE THREAD

**Issue by lohnsonok** [sickcodes/Docker-OSX#448]
i'm installed catalina and shutdown qemu now i can't see on boot to avoir reinstall. 
Command used:
`docker run -it    --device /dev/kvm     -p 50922:10022     -v /tmp/.X11-unix:/tmp/.X11-unix     -e "DISPLAY=${DISPLAY:-:0.0}"     sickcodes/docker-osx:latest`
# OS related issued, please help us identify the issue by posting the output of this
Linux leprofesseur-HP-ENVY-15-X360-PC 5.13.0-28-generic #31-Ubuntu SMP Thu Jan 13 17:41:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by itdsntwork** [comment]
I had the same issue. How did you solve this?

**Comment by itdsntwork** [comment]
https://github.com/sickcodes/Docker-OSX#start-the-same-container-later-persistent-disk

**Comment by lohnsonok** [comment]
Run 
`sudo docker ps`
you will see your image **dock codes/docker-xos**
And run docker container Id
`docker start -ai containerId`
