### ISSUE TITLE
Cannot Add  Apple Id in XCode

### ISSUE THREAD

**Issue by noorbakerally** [sickcodes/Docker-OSX#454]
I have properly installed XCode. However, when I'm trying to add an Apple Id, i'm getting the error "Unable to sign you in to your Apple Id. Try again later". I am using the same credentials on a real Mac and it is working.

Also, I have tried to create an Apple Id as I wasn't able to sign in, a dialog is poping out saying "Could not create Apple Id, This Mac has been used to create too many new Apple IDs. Please contact Apple Support to request another Apple Id to use with this Mac"

# OS related issued, please help us identify the issue by posting the output of this
Linux localhost.localdomain 5.14.18-100.fc33.x86_64 #1 SMP Fri Nov 12 17:38:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
:0
1
NAME=Fedora
VERSION_CODENAME=""
PRETTY_NAME="Fedora 33 (Workstation Edition)"
CPE_NAME="cpe:/o:fedoraproject:fedora:33"
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p3  237G  233G  3.6G  99% /home
QEMU emulator version 5.1.0 (qemu-5.1.0-9.fc33)
Copyright (c) 2003-2020 Fabrice Bellard and the QEMU Project developers
libvirtd (libvirt) 6.6.0
              total        used        free      shared  buff/cache   available
Mem:          7.4Gi       6.1Gi       188Mi       363Mi       1.1Gi       659Mi
Swap:         3.7Gi       3.5Gi       167Mi
8
16
crw-rw-rw- 1 root kvm 10, 232 Feb 22 17:26 /dev/kvm
total 0
drwxrwxrwt  3 root root 140 Feb 21 15:37 .
drwxrwxrwt 30 root root 780 Feb 22 14:33 ..
drwxr-xr-x  2 root root  40 Feb 21 15:37 mac_hdd_ng.img
srwxr-xr-x  1 noor noor   0 Feb 20 19:43 X0
srwxr-xr-x  1 noor noor   0 Feb 20 19:43 X1
srwxr-xr-x  1 gdm  gdm    0 Feb 20 19:43 X1024
srwxr-xr-x  1 gdm  gdm    0 Feb 20 19:43 X1025
root       48413  0.0  0.1 2353344 12296 ?       Ssl  Feb21   0:19 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
root      174044  0.0  0.0 221572   788 pts/0    S+   17:32   0:00 grep --color=auto dockerd
fb9437534b25   sickcodes/docker-osx   "/bin/bash -c 'sudo …"   30 hours ago   Up 6 minutes             sad_maxwell
kvm:x:36:qemu
libvirt:x:981:
docker:x:971:

**Comment by noorbakerally** [comment]
This is tutorial I used to create the container->https://www.funkyspacemonkey.com/how-to-install-macos-catalina-in-a-docker-container-on-linux

I short the command is: docker run --privileged -e "DISPLAY=${DISPLAY:-:0.0}" -v /tmp/.X11-unix:/tmp/.X11-unix sickcodes/docker-osx

**Comment by noorbakerally** [comment]
I've been trying this, i'm getting the following error when trying to starting a previous running container:

022-02-28T13:35:20.245585865+04:00 network connect ea212d64c3831e5397033c79c88614b35171f11dc0fe6666800dfba36adccbbc (container=8faf3518b17ee57d70104b437220a4a50b8fd919881536b3d6cd6c99fe74dbb7, name=bridge, type=bridge)
2022-02-28T13:35:20.874615714+04:00 container start 8faf3518b17ee57d70104b437220a4a50b8fd919881536b3d6cd6c99fe74dbb7 (image=sickcodes/docker-osx, maintainer=https://twitter.com/sickcodes <https://sick.codes>, name=inspiring_shamir)
2022-02-28T13:35:21.217308575+04:00 container die 8faf3518b17ee57d70104b437220a4a50b8fd919881536b3d6cd6c99fe74dbb7 (exitCode=1, image=sickcodes/docker-osx, maintainer=https://twitter.com/sickcodes <https://sick.codes>, name=inspiring_shamir)
2022-02-28T13:35:21.444844228+04:00 network disconnect ea212d64c3831e5397033c79c88614b35171f11dc0fe6666800dfba36adccbbc (container=8faf3518b17ee57d70104b437220a4a50b8fd919881536b3d6cd6c99fe74dbb7, name=bridge, type=bridge)

**Comment by noorbakerally** [comment]
[](url)

**Comment by noorbakerally** [comment]
Sorry for closing the above, it's a mistake

The full error log can be seen here-> https://docs.google.com/document/d/1JqWql9MyWPKpZptEmHO8MmpBKh4Aa1CGIAG4IKBzpUg

**Comment by jailsonpaca** [comment]
> Add `--e GENERATE_UNIQUE=true` and you should be able to log in.
> 
> But you will have to take your image out first

thank you!!
