### ISSUE TITLE
`(qemu) ALSA lib confmisc.c:767:(parse_card) cannot find card '0'`

### ISSUE THREAD

**Issue by CaptainTux** [sickcodes/Docker-OSX#46]
[log.txt](https://github.com/sickcodes/Docker-OSX/files/4785702/log.txt)
So I am having an issue with ALSA, see the log attached.
I did everything in the README and tried running docker with
```shell
$ docker run --privileged -e "DISPLAY=${DISPLAY:-:0.0}" -v /tmp/.X11-unix:/tmp/.X11-unix sickcodes/docker-osx
```

I tried to find a solution online, I suppose it is not exactly an issue with the docker image, but I couldn't find anything that works.

I am running Manjaro with XMonad, I have all the alsa libs and drivers installed, not sure what else I can do...

**Comment by sickcodes** [comment]
The problem is the display. Alsa errors show up for everyone.

Have you tried all the troubleshooting docs in the readme?

`echo $DISPLAY
ls -lha /dev/kvm`

**Comment by CaptainTux** [comment]
![image](https://user-images.githubusercontent.com/34196765/84767911-8c98b600-afd3-11ea-8650-47a7073949bd.png)
yes I looked at the trouble shooting docs, didn't help

**Comment by CaptainTux** [comment]
Never mind, somehow it works now with the original command 
`docker run --privileged -e "DISPLAY=${DISPLAY:-:0.0}" -v /tmp/.X11-unix:/tmp/.X11-unix sickcodes/docker-osx`

**Comment by sickcodes** [comment]
Great :)
