### ISSUE TITLE
Increase RAM

### ISSUE THREAD

**Issue by rodrigofbm** [sickcodes/Docker-OSX#462]
I saw the #197 issue but I didn't get it. I have my container ` 45ecb45be310   sickcodes/docker-osx:monterey                "/bin/bash -c 'sudo …"   2 days ago   Exited (0) 24 hours ago                                               mystifying_hopper` but with only 4 GB of RAM. I want to change it to 8GB. How I do it please

**Comment by sickcodes** [comment]
You will need to pull the image out and use the naked container: https://github.com/sickcodes/Docker-OSX#container-creation-examples

**Comment by gustavotoyota** [comment]
Leaving the solution here as it was hard for me to find: https://github.com/sickcodes/Docker-OSX/discussions/199#discussioncomment-510813
