### ISSUE TITLE
Can't extract container img file using Docker on WSL2

### ISSUE THREAD

**Issue by cbini** [sickcodes/Docker-OSX#464]
Hi! Just started using this this weekend, and it's going well. I'd like to extract the image in the container that I've built, but the suggested command doesn't work:

```
sudo find /var/lib/docker -size +10G | grep mac_hdd_ng.img
find: ‘/var/lib/docker’: No such file or directory
```

I imagine this has something to do with running Docker in WSL2. Has anyone figured this out?

**Comment by rogeriorc** [comment]
I think its located on:

`\\wsl$\docker-desktop-data\version-pack-data\community\docker\overlay2`
