### ISSUE TITLE
screen resolution

### ISSUE THREAD

**Issue by klaumann** [sickcodes/Docker-OSX#47]
The macOS installation is expecting a display with 1920*1080 resolution. 
The Screen I'm running on, is only 1280*1024 ... 
Is there a possibility to change the Screen Size ?

**Comment by sickcodes** [comment]
use ./boot-macOS-NG.sh  at the end of the command

**Comment by sickcodes** [comment]
Or you can use the VNC version.

The bootloader is set to 1920x1080, so if you want to change it, you need to boot and then change it and reboot.

You can do it here:

https://dortania.github.io/OpenCore-Desktop-Guide/post-install/verbose.html
