### ISSUE TITLE
TEMP-FIX is breaking Dockerfile.nakedvnc build

### ISSUE THREAD

**Issue by Andrflor** [sickcodes/Docker-OSX#470]
The glibc has now been updated to 2.34

The TEMP-FIX in the vnc dockerfile is now not fixing the install anymore but breaking it.
The code in TEMP-FIX is not needed anymore. It even must be removed to process proper build.

Thx for this masterpiece btw :slightly_smiling_face:

**Comment by sickcodes** [comment]
Thanks for letting me know!

**Comment by sickcodes** [comment]
What about libguestfs, do you want that patch?

**Comment by Andrflor** [comment]
The libguestfs patch is not needed anymore.
I just got an all functioning build without any patch.
Thanks for the PR the diff will close this issue.

**Comment by sickcodes** [comment]
So this works: https://github.com/sickcodes/Docker-OSX/pull/472?

If so, I'll merge

**Comment by Andrflor** [comment]
Yes it does
