### ISSUE TITLE
Persistent Apple ID not working

### ISSUE THREAD

**Issue by heli-aviator** [sickcodes/Docker-OSX#482]
Hi, first off thank you for a fantastic project!

I'm having a problem with having my Apple ID be persistent. I have to log in every time I boot up the docker osx VM Monterey. 
Meaning every time I start the VM I get a new iMac in my Apple devices under my Apple ID. 

Is there a way to make it remember it from time to time I start it up?

**Comment by Sab-tech-lab** [comment]
Try this solution:
https://github.com/sickcodes/Docker-OSX/issues/416

**Comment by heli-aviator** [comment]
Thank you for that, it worked but, my container is located under /var/lib/docker/containers/

In case anybody else having trouble getting the jq. To work, just change that and try again

**Comment by heli-aviator** [comment]
This can be closed now
