### ISSUE TITLE
SSHFS Option

### ISSUE THREAD

**Issue by sickcodes** [sickcodes/Docker-OSX#486]
Been testing out sshfs and I am impressed.

Will be adding this as a stock solution; secure (hopefully, pending an audit).

Assuming it's strictly fuse + ssh tunneled.

https://github.com/libfuse/sshfs

**Comment by sickcodes** [comment]
Fixed

**Comment by RichardFevrier** [comment]
SSHFS has been archived since then @sickcodes. Not sure it is futureproof.
