### ISSUE TITLE
Can I use xCode on v12 Monterey or v11 BigSur?

### ISSUE THREAD

**Issue by burgil** [sickcodes/Docker-OSX#501]
Hey, Just wondering how come the readme states that only v10.15 Catalina is safe to use with XCode? `(sickcodes/docker-osx:latest)`
What about BigSur or Monterey? `(sickcodes/docker-osx:monterey & sickcodes/docker-osx:big-sur)`

I searched all over your docs and GitHub for keywords like `XCode` and `title: XCode` and found a really old post https://github.com/sickcodes/Docker-OSX/issues/24 that talks about a requirement for the latest version of MacOS in order to use XCode, and people stated that it worked for them on v10.15, and that's it, nothing new was posted for years there, seems like this should still be a valid issue no?

Is it even ok to make apps and upload to the Appstore using this? can't find a disclaimer about that and I was also looking for information about using XCode on the latest Monterey version, please.

Thank you for reading.

https://github.com/sickcodes/Docker-OSX/issues?q=title%3A+xcode+

**Comment by imunique-ZJ** [comment]
Tried Monterey with Xcode and successfully upload application to Appstore. It's fine to take this solution.

**Comment by burgil** [comment]
Thanks! @imunique-ZJ
