### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by Kuba112811** [sickcodes/Docker-OSX#502]
When i will start the command the virtual machine will start, but if i do it again will it be resetted,  or do i use another command to launch the later times?

**Comment by Kuba112811** [comment]
@sickcodes

**Comment by sickcodes** [comment]
You can restart later with `docker start -ai xxxx` where xxx you can get using `docker ps`

**Comment by sickcodes** [comment]
If you want to change the parameters, you will need to use the naked image after creating a normal image
