### ISSUE TITLE
sshpass command not found

### ISSUE THREAD

**Issue by shashank2086** [sickcodes/Docker-OSX#506]
I have successfully builded the naked auto image but when i am to trying to run the image i am getting this error.

Disk is being copied between layers. Repeating until able to copy SSH key into OSX...
/bin/bash: line 1: sshpass: command not found

**Comment by hassinetouil** [comment]
> I have successfully builded the naked auto image but when i am to trying to run the image i am getting this error.
> 
> Disk is being copied between layers. Repeating until able to copy SSH key into OSX... /bin/bash: line 1: sshpass: command not found

i have the same issue can you tell me how you solve it ?

**Comment by apagac2** [comment]
If you are copying snippets from readme, this issue could happen here: https://github.com/sickcodes/Docker-OSX#use-your-own-image-and-manually-and-automatically-log-into-a-shell

The image is missing file extension. This is how it should look like:

```
docker run -it \
    --device /dev/kvm \
    -p 50922:10022 \
    -v "${PWD}/mac_hdd_ng_auto_monterey.img:/image" \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    -e "USERNAME=user" \
    -e "PASSWORD=alpine" \
    -e GENERATE_UNIQUE=true \
    -e MASTER_PLIST_URL=https://raw.githubusercontent.com/sickcodes/Docker-OSX/master/custom/config-nopicker-custom.plist \
    sickcodes/docker-osx:naked-auto
```
The difference being the **.img** here: `-v "${PWD}/mac_hdd_ng_auto_monterey.img:/image"`

**Comment by Nolij** [comment]
I am still encountering this issue even using the modified command.

**Comment by whytewolf** [comment]
I'm seeing this error also. and the "fix" didn't change anything. I even trying listing directly where the file was located instead of using PWD. still no go.

**Comment by BonifacioCalindoro** [comment]
Same issue here. the fix didn't work.
