### ISSUE TITLE
Unable to start docker

### ISSUE THREAD

**Issue by jacobtread** [sickcodes/Docker-OSX#514]
# OS related issued, please help us identify the issue by posting the output of this
uname -a \
; echo "${DISPLAY}" \
; echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs \
; grep NAME /etc/os-release \
; df -h . \
; qemu-system-x86_64 --version \
; libvirtd --version \
; free -mh \
; nproc \
; egrep -c '(svm|vmx)' /proc/cpuinfo \
; ls -lha /dev/kvm \
; ls -lha /tmp/.X11-unix/ \
; ps aux | grep dockerd \
; docker ps | grep osx \
; grep "docker\|kvm\|virt" /etc/group

Linux fedora 5.18.7-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Jun 25 20:06:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
:0
[sudo] password for jacobtread: 
1
NAME="Fedora Linux"
VERSION_CODENAME=""
PRETTY_NAME="Fedora Linux 36 (Workstation Edition)"
CPE_NAME="cpe:/o:fedoraproject:fedora:36"
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme1n1p3  476G   69G  406G  15% /home
QEMU emulator version 6.2.0 (qemu-6.2.0-12.fc36)
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers
libvirtd (libvirt) 8.1.0
               total        used        free      shared  buff/cache   available
Mem:            15Gi       3.2Gi       3.6Gi       4.5Gi       8.4Gi       7.2Gi
Swap:          8.0Gi          0B       8.0Gi
8
16
crw-rw-rw-. 1 root kvm 10, 232 Jul  1 13:05 /dev/kvm
total 0
drwxrwxrwt.  2 root       root       120 Jul  1 12:50 .
drwxrwxrwt. 30 root       root       780 Jul  1 13:07 ..
srwxr-xr-x.  1 jacobtread jacobtread   0 Jul  1 12:50 X0
srwxr-xr-x.  1 jacobtread jacobtread   0 Jul  1 12:50 X1
srwxr-xr-x.  1 gdm        gdm          0 Jul  1 12:50 X1024
srwxr-xr-x.  1 gdm        gdm          0 Jul  1 12:50 X1025
jacobtr+   10273  0.0  0.0 222164  2280 pts/0    S+   13:07   0:00 grep --color=auto dockerd
kvm:x:36:qemu,jacobtread
libvirt:x:984:jacobtread
docker:x:978:jacobtread

When running the command
docker run -it \
    --device /dev/kvm \
    -p 50922:10022 \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    sickcodes/docker-osx:big-sur

The output from this is
docker: Error response from daemon: error gathering device information while adding custom device "/dev/kvm": no such file or directory.
ERRO[0000] error waiting for container: context canceled

**Comment by sickcodes** [comment]
Incompatible host

**Comment by EMPAT94** [comment]
> `"/dev/kvm": no such file or directory.`

Install qemu, kvm and dependencies (for whatever distro you are on, see initial setup), then restart your system for good measure. 

`ls -l /dev/kvm` should show some output.

**Comment by jacobtread** [comment]
Closing the issue as I no longer need it switched operating systems.
