### ISSUE TITLE
Changing OpenCoreBoot's config.plist to allow to select the default boot disk via AllowSetDefault

### ISSUE THREAD

**Issue by sck** [sickcodes/Docker-OSX#53]
I have been trying to enable `AllowSetDefault` in `OpenCore-Catalina`'s `config.plist`.  There is a script called `opencore-image-ng.sh` which builds a new `OpenCore.qcow2` and also uses the `config.plist`.  But the generated `OpenCore.qcow2` never behaves like the original qcow2 (even when not changing the `config.plist` at all).  It prints `start pxe over ipv4` in the beginning and after pressing ESC it just starts the UEFI shell, and doesn't offer to  boot into OSX at all

**Comment by sickcodes** [comment]
You can try loop mounting the qcow image or just hexedit it and turn that value on.

**Comment by sck** [comment]
I've now been able to rebuilt OpenCoreBoot with a new config.plist:

For libguestfs/loop mounting I added these packages to my Dockerfile:
```
RUN sudo pacman -S --noconfirm linux cpio
RUN sudo pacman -S --noconfirm unzip
```

OpenCore is missing some files for the image to be rebuild, so I reinstalled it under `/home/arch/OSX-KVM/OpenCore-Catalina`

```
F="OpenCore-0.5.9-DEBUG.zip"

test -f $F || (
  wget https://github.com/acidanthera/OpenCorePkg/releases/download/0.5.9/$F
  unzip -o $F
)

```

Now the image can be rebuild without errors:
```
sudo rm -f OpenCore.qcow2; sudo ./opencore-image-ng.sh  --cfg config.plist --img OpenCore.qcow2

```

For enabling to boot automatically I removed `-device ide-hd,bus=sata.3,drive=InstallMedia` and `-drive id=InstallMedia,if=none,file=$BASESYSTEM,format=raw` from the qemu parameters and used this patch for config.plist:

```
                        <key>HideAuxiliary</key>
                        <false/>
                        <key>PickerAttributes</key>
-                       <integer>1</integer>
+                       <integer>0</integer>
                        <key>PickerAudioAssist</key>
                        <false/>
                        <key>PickerMode</key>
-                       <string>External</string>
+                       <string>Builtin</string>
                        <key>PollAppleHotKeys</key>
                        <true/>
                        <key>ShowPicker</key>
-                       <true/>
+                       <false/>
                        <key>TakeoffDelay</key>
                        <integer>0</integer>
                        <key>Timeout</key>
                        <key>Timeout</key>
-                       <integer>0</integer>
+                       <integer>5</integer>
                </dict>
                <key>Debug</key>
                <dict>
```

This will then boot from the first hdd which is where my macos installation resides.

**Comment by sickcodes** [comment]
You’re awesome dude, pull request or can I include this in the code for you?

**Comment by sck** [comment]
Feel free to use what I documented!  I have a slightly different setup atm, so not easy to generate a pull request...

**Comment by daraul** [comment]
Any way we can see the code, @sck? Even if it's not in a PR, it would still be useful.
