### ISSUE TITLE
Animations lags. |Monterey|

### ISSUE THREAD

**Issue by Danila-hub** [sickcodes/Docker-OSX#530]
I try to use **Monterey** version, but had some problem:
Animations in system and browser works bad, with laggy.
Ryzen 7 2700X, RTX 2080ti, 32GB ram, on SSD M.2
Cpu virtualization is on.

For container:
CORES: 8
SMP: 8
RAM: 16

Video (Don't worry, it doesn't have any sound)
https://user-images.githubusercontent.com/55277394/184935217-63c71167-e0d4-4889-8bc1-33c3f0e80b45.mp4

**Comment by Bananz0** [comment]
I think that is expected since you do not have native graphics acceleration supported by macOS. For that, you need a recent AMD graphics card passed through to it.
