### ISSUE TITLE
OTA update help

### ISSUE THREAD

**Issue by gitcomit8** [sickcodes/Docker-OSX#556]
I installed the OTA update to ventura and on the boot selection screen a new option is shown named "Macintosh HD". If i boot with this one I get a kernel panic. It would be helluva lot better if internal ota updates were supported

**Comment by unity20221019** [comment]
i have try update too. in my case reboot , only show some error and can do nothing at all. at last i give up that container.

**Comment by gerold-penz** [comment]
Same problem. :-(

**Comment by sickcodes** [comment]
Ventura is ready, please use fresh images.

**Comment by gitcomit8** [comment]
As I didn't see this problem getting resolved any time in the near future, this issue has been closed
