### ISSUE TITLE
Accessing the macOS VM over SSH

### ISSUE THREAD

**Issue by jviotti** [sickcodes/Docker-OSX#56]
I'm following the instructions and running the VM by port forwarding the SSH port `-p 50922:10022`, however I can't get a shell on the VM at `localhost` from the host as the connection is refused and `nmap` doesn't show the port being open.

Am I missing something?

**Comment by sickcodes** [comment]
ssh localhost -p 50922
You also have to turn on system sharing once you've installed the OS 
Its under "remote login" in OSX settings

**Comment by jviotti** [comment]
> You also have to turn on system sharing once you've installed the OS
Its under "remote login" in OSX settings

I see. It would be nice to mention this in the docs! Thanks!

**Comment by jviotti** [comment]
I'm afraid I can't make it work yet. I enabled remote login in macOS, and I can ssh to the VM *from within the VM* at port 22, but 50922 never gets forwarded to the host.

**Comment by sickcodes** [comment]
`docker ps`
See if you have anything else using that port

Did you copy the ports exactly as they are in the readme and/or top of the docker file?

localhost:50922 goes to container:10022 which goes to guest:22

**Comment by jviotti** [comment]
@sickcodes This is the output of `docker ps`:

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
e082f90113ab        catalina            "/bin/sh -c 'ls -la …"   25 hours ago        Up 25 hours                             competent_bassi
```

And I'm running the image as:

```
docker run \
  --privileged \
  --net host \
  -p 50922:10022 \
  -e "DISPLAY=${DISPLAY:-:0.0}" \
  -e RAM=6 \
  --cap-add=ALL \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v /dev:/dev -v /lib/modules:/lib/modules \
  -v /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock \
  sickcodes/docker-osx
```

**Comment by jviotti** [comment]
@sickcodes I was able to connect to it by omitting the `--net host` option in `docker run`. The port is bound and I can see that in `docker ps`, however the VM has no internet connection now :/

**Comment by jviotti** [comment]
@sickcodes Any clues about this? I've been trying some long shots, but I feel that I'm mostly in the dark. I'm following the instructions exactly as described in the README, so it must be something in my host system, right?

**Comment by sickcodes** [comment]
Building on mine and checking now

**Comment by jviotti** [comment]
@sickcodes I think got to the bottom of it. The DNS requests would get blocked by `firewalld` on my Fedora 32 system. See this snippet from `docker0` after trying to ping google from within the container:

![Screen Sharing Picture 7 July 2020 at 11 04 14 BST](https://user-images.githubusercontent.com/2192773/86765897-add44b80-c041-11ea-968f-f05a263e1b15.png)

Apparently things work again if I set `docker0` to the trusted zone:

```
firewall-cmd --permanent --zone=trusted --add-interface=docker0
firewall-cmd --reload
```

See https://github.com/docker/for-linux/issues/955
