### ISSUE TITLE
Mouse integration

### ISSUE THREAD

**Issue by TeoConan** [sickcodes/Docker-OSX#561]
Hi everyone,

I was wondering : is there a way to have an usb passthrough or something like this for this docker ?
I ask this because I got a very very slow mouse when I'm inside qemu

I tried to pass my device like this : 
``` shell
docker run -it \
    --device /dev/kvm \
    --device /dev/input/by-id/usb-Logitech_G502_HERO_Gaming_Mouse_0D7839673831-mouse \ # I added this
    -p 50922:10022 \
```

But nothing change

I also tried to pass through qemu with extra options like this : 
``` shell
-e "DISPLAY=${DISPLAY:-:0.0}" \
    -e EXTRA='-smp 16,sockets=8,cores=2 -device usb-host,hostbus=1,hostport=4' \ # I added hostbus and hostport address
    -v "${PWD}/imgs/mac_hdd_ng_auto_monterey.img:/image" \
```

But nothing change again

Does anyone have an idea ?

Thanks

**Comment by sickcodes** [comment]
USB instructions, including hot plugging: https://github.com/sickcodes/Docker-OSX#mount-usb-drive-hotplughot-plug-usb

iPhone requires https://github.com/sickcodes/Docker-OSX#usbfluxd-iphone-usb---network-style-passthrough-osx-kvm-docker-osx
