### ISSUE TITLE
MacOS Catalina Pre-Installed (Repeating until able to copy SSH key into OSX)

### ISSUE THREAD

**Issue by softplace-io** [sickcodes/Docker-OSX#565]
Hello, 

I ran the commands:

docker pull sickcodes/docker-osx:auto
docker run -it \
     --device /dev/kvm \
     -p 50922:10022 \
     -v /tmp/.X11-unix:/tmp/.X11-unix \
     -e "DISPLAY=${DISPLAY:-:0.0}" \
     -e GENERATE_UNIQUE=true \
     sickcodes/docker-osx:auto

Shell: Disk is being copied between layers. Repeating until able to copy SSH key into OSX (LOOP)

And I have this message in "infinite loop" what should I do?

**Comment by softplace-io** [comment]
Solved, enable SSH Service :D

**Comment by xVemu** [comment]
How did you manage to fix that?

**Comment by altschuler** [comment]
How did you solve this?
