### ISSUE TITLE
Ventura install fails under Windows 11/WSL

### ISSUE THREAD

**Issue by mark-ramsey-ri** [sickcodes/Docker-OSX#571]
After the ventura image is restored to the large disk, it appears to try to perform an upgrade and displays a popup window with the message "An error occurred preparing the software update".  I have tried building the container a number of times as well as trying to stop and restart the existing container with the same results.

I used the following command in wsl:

docker run -it \
    --device /dev/kvm \
    -p 50922:10022 \
    -v /mnt/wslg/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    -e GENERATE_UNIQUE=true \
    -e MASTER_PLIST_URL='https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom.plist' \
    sickcodes/docker-osx:ventura

I submitted this on Discord and the only response was that Windows/wsl sucks and it will never work.....doubt that is the real answer.  I was able to build catalina and monterey with this same setup.....but I need ventura for the compile process I am doing.

Here are the results from the commands:

1
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
Filesystem      Size  Used Avail Use% Mounted on
drvfs           1.9T  1.3T  650G  66% /mnt/c
QEMU emulator version 6.2.0 (Debian 1:6.2+dfsg-2ubuntu6.5)
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers
Command 'libvirtd' not found, but can be installed with:
sudo apt install libvirt-daemon
               total        used        free      shared  buff/cache   available
Mem:            31Gi       1.3Gi       4.3Gi       3.0Mi        25Gi        29Gi
Swap:          8.0Gi       6.0Mi       8.0Gi
16
32
crw-rw-rw- 1 root root 10, 232 Nov 22 09:00 /dev/kvm
total 4.0K
drwxrwxrwx 2 root    root      60 Nov 22 09:00 .
drwxrwxrwt 3 root    root    4.0K Nov 10 15:05 ..
srwxrwxrwx 1 mramsey mramsey    0 Nov 22 09:00 X0
mramsey    272  0.0  0.0   4024  1940 pts/2    S+   10:27   0:00 grep --color=auto dockerd
kvm:x:109:
docker:x:1001:mramsey

**Comment by RichardFevrier** [comment]
Not sure it is related to `WSL` since it happens to me under `Fedora`

**Comment by RichardFevrier** [comment]
Resolved for me using `HFS+ journaled` instead of `APFS` during the partition formating step.
Can you try that too @mark-ramsey-ri ?

**Comment by RichardFevrier** [comment]
Going to `Disk Utility` after macOS is booted and my volumes seems to be ... `APFS` 🤔
Unable to understand...

**Comment by mark-ramsey-ri** [comment]
Just kicked off a restore after using HFS+ journaled instead of APFS.  I guess we will know in about 2hrs if that works under Windows too.

**Comment by mark-ramsey-ri** [comment]
Using that approach worked for me too.

The documentation should be updated for Ventura to set the initial disk format to HFS+ journaled so that the install will finish correctly.  I believe as it installs and updates, it updates the disk format to APFS.

**Comment by RichardFevrier** [comment]
Glad it worked for you too @mark-ramsey-ri 🙂
I agree the documentation should probably reflect this @sickcodes

**Comment by PTAHume** [comment]
where do you find this option as its no in the list of formatting options for the mac boot format option dropdown list?

**Comment by RichardFevrier** [comment]
![Screenshot from 2023-02-13 12-00-55](https://user-images.githubusercontent.com/5154754/218442270-2981dce1-a9a6-4bac-a182-0091a872be7c.png)
![Screenshot from 2023-02-13 12-01-15](https://user-images.githubusercontent.com/5154754/218442265-5488ca11-57bf-4265-8bd1-f72f96c3941f.png)

**Comment by PTAHume** [comment]
thank you :)

**Comment by singpolyma** [comment]
This hasn't changed anything for me, I get the same error.

**Comment by kocoman2** [comment]
is there any way to get the error log?
