### ISSUE TITLE
Selecting MacOS Base system does nothing

### ISSUE THREAD

**Issue by ngengesenior** [sickcodes/Docker-OSX#58]
I have followed the installation instructions and when I start the docker container the machine boots and I select MacOS Base system, nothing happens and I am left on the same display. I am running Ubuntu 20. Are there any additional steps I have to take?

**Comment by ngengesenior** [comment]
![mac](https://user-images.githubusercontent.com/17143469/86444037-10f37480-bd08-11ea-9d14-206d623e112e.png)

**Comment by sickcodes** [comment]
Hit the enter key and you should boot in

**Comment by ngengesenior** [comment]
It did work.
