### ISSUE TITLE
Sheel Appears after installation

### ISSUE THREAD

**Issue by FaiqOsitech** [sickcodes/Docker-OSX#59]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/67308157/86443993-815ebd80-bd29-11ea-854b-4107b9aea1f5.png)

**Comment by sickcodes** [comment]
Which OS are you using? I will check upstream

**Comment by FaiqOsitech** [comment]
I am trying to setup on Ubuntu 18.04 LTS and i get the above screen right after the installation of Mac Os.

**Comment by sickcodes** [comment]
5 seconds after this screen appears, the system will boot into the OpenCore menu, closing as appropriate.
