### ISSUE TITLE
SSH Connection Refused (Loop)

### ISSUE THREAD

**Issue by NotZer0Two** [sickcodes/Docker-OSX#596]
# OS related issued, please help us identify the issue by posting the output of this
Linux PurpleTwoOS 6.0.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 08 Dec 2022 11:03:38 +0000 x86_64 GNU/Linux
:0
1
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
File system     Dim. Usati Dispon. Uso% Montato su
/dev/sda2       458G   61G    373G  15% /
bash: qemu-system-x86_64: comando non trovato
bash: libvirtd: comando non trovato
               total        used        free      shared  buff/cache   available
Mem:           3,7Gi       1,9Gi       139Mi        22Mi       1,6Gi       1,5Gi
Swap:          1,8Gi        69Mi       1,8Gi
4
egrep: warning: egrep is obsolescent; using grep -E
8
crw-rw-rw- 1 root kvm 10, 232 16 dic 13.15 /dev/kvm
totale 0
drwxrwxrwt  2 root root  60 16 dic 12.46 .
drwxrwxrwt 13 root root 300 16 dic 13.03 ..
srwxrwxrwx  1 root root   0 16 dic 12.46 X0
root         526  0.1  1.3 1529568 51908 ?       Ssl  12:47   0:02 /usr/bin/dockerd -H fd://
purplet+   13129  0.0  0.0   6584  2296 pts/1    S+   13:27   0:00 grep dockerd
kvm:x:992:
docker:x:971:purpletwo

Error:
Disk is being copied between layers. Repeating until able to copy SSH key into OSX...
/usr/sbin/ssh-copy-id: INFO: Source of key(s) to be installed: "/home/arch/.ssh/id_docker_osx.pub"
ssh: connect to host 127.0.0.1 port 10022: Connection refused

**Comment by shainegordon** [comment]
Same here

Ryzen 5900X
Kubuntu 22.04

using this method:
```
wget https://images.sick.codes/mac_hdd_ng_auto_monterey.img

docker run -it \
    --device /dev/kvm \
    -p 50922:10022 \
    -v "${PWD}/mac_hdd_ng_auto_monterey.img:/image" \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    -e "USERNAME=user" \
    -e "PASSWORD=alpine" \
    -e GENERATE_UNIQUE=true \
    -e MASTER_PLIST_URL=https://raw.githubusercontent.com/sickcodes/Docker-OSX/master/custom/config-nopicker-custom.plist \
    sickcodes/docker-osx:naked-auto
```

**Comment by glani** [comment]
Same happens with me:

/usr/sbin/ssh-copy-id: INFO: Source of key(s) to be installed: "/home/arch/.ssh/id_docker_osx.pub"
ssh: connect to host 127.0.0.1 port 10022: Connection refused
Disk is being copied between layers. Repeating until able to copy SSH key into OSX...


```
docker run -it \
        --device /dev/kvm \
        -p 50922:10022 \
        -e USERNAME=yourusername \
        -e PASSWORD=yourpassword \
        sickcodes/docker-osx:naked-auto
```
Ubuntu 22

**Comment by shainegordon** [comment]
> Same happens with me:
> 
> /usr/sbin/ssh-copy-id: INFO: Source of key(s) to be installed: "/home/arch/.ssh/id_docker_osx.pub" ssh: connect to host 127.0.0.1 port 10022: Connection refused Disk is being copied between layers. Repeating until able to copy SSH key into OSX...
> 
> ```
> docker run -it \
>         --device /dev/kvm \
>         -p 50922:10022 \
>         -e USERNAME=yourusername \
>         -e PASSWORD=yourpassword \
>         sickcodes/docker-osx:naked-auto
> ```
> 
> Ubuntu 22

I actually did get it running correctly, using this

```
wget https://images.sick.codes/mac_hdd_ng_auto_monterey.img

docker run -it \       
    --device /dev/kvm \  
    -p 50922:10022 \   
    -v "${PWD}/mac_hdd_ng_auto_monterey.img:/image" \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    sickcodes/docker-osx:naked
```

notice `sickcodes/docker-osx:naked` vs `sickcodes/docker-osx:naked-auto`

**Comment by glani** [comment]
> -v "${PWD}/mac_hdd_ng_auto_monterey.img:/image" \
>     -v /tmp/.X11-unix:/tmp/.X11-unix \

Ohh. Thank you.
