### ISSUE TITLE
Container Fails to Open in QNAP 473A

### ISSUE THREAD

**Issue by Dems1984** [sickcodes/Docker-OSX#600]
[DockerOutput.pdf](https://github.com/sickcodes/Docker-OSX/files/10252985/DockerOutput.pdf)

Sorry that this isn't the best presentation (was unable to get the text direct, hence PDF) and I am very new to containers, Docker.  I am using a QNAP 473A NAS running its Container Station app.  Unfortunately the OS is proprietary but I think it is a Linux of some sort, possibly Debian.  Not sure.  Anyway, I have had success with other containers and was able to download this one.  I see in the code you are specifying the processor.  This NAS is using an AMD Ryzen V1500B as the processor.  Do I need to change the processor type in the command line for the  qemu and how would I do this?  Is the container you made just not compatible with AMD processors, QNAP products (AMD and Intel), and/or QNAP products with AMD chips?  Is there something else outside of the processor that would cause the problem?  Thank you for your time and help.  I hope this is not too much of a bother for you to review and answer.  Best.

**Comment by Dems1984** [comment]
Here is the text from trying to run the container.  I ran Docker from the CLI on the QNAP:

ssh-keygen: generating new host keys: RSA ECDSA ED25519 
nohup: appending output to 'nohup.out'
++ id -u
++ id -g
+ sudo chown 1000:1000 /dev/kvm
++ id -u
++ id -g
+ sudo chown -R 1000:1000 /dev/snd
+ [[ 4 = max ]]
+ [[ 4 = half ]]
++ id -u
++ id -g
+ sudo chown -R 1000:1000 /dev/snd
+ exec qemu-system-x86_64 -m 4000 -cpu Penryn,vendor=GenuineIntel,+invtsc,vmware-cpuid-freq=on,+ssse3,+sse4.2,+popcnt,+avx,+aes,+xsave,+xsaveopt,check, -machine q35,accel=kvm:tcg -smp 4,cores=4 -usb -device usb-kbd -device usb-tablet -device 'isa-applesmc,osk=ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc' -drive if=pflash,format=raw,readonly=on,file=/home/arch/OSX-KVM/OVMF_CODE.fd -drive if=pflash,format=raw,file=/home/arch/OSX-KVM/OVMF_VARS-1024x768.fd -smbios type=2 -audiodev alsa,id=hda -device ich9-intel-hda -device hda-duplex,audiodev=hda -device ich9-ahci,id=sata -drive id=OpenCoreBoot,if=none,snapshot=on,format=qcow2,file=/home/arch/OSX-KVM/OpenCore/OpenCore.qcow2 -device ide-hd,bus=sata.2,drive=OpenCoreBoot -device ide-hd,bus=sata.3,drive=InstallMedia -drive id=InstallMedia,if=none,file=/home/arch/OSX-KVM/BaseSystem.img,format=qcow2 -drive id=MacHDD,if=none,file=/home/arch/OSX-KVM/mac_hdd_ng.img,format=qcow2 -device ide-hd,bus=sata.4,drive=MacHDD -netdev user,id=net0,hostfwd=tcp::10022-:22,hostfwd=tcp::5900-:5900, -device vmxnet3,netdev=net0,id=net0,mac=52:54:00:09:49:17 -monitor stdio -boot menu=on -vga vmware
QEMU 7.1.0 monitor - type 'help' for more information

(qemu) ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM default
alsa: Could not initialize DAC
alsa: Failed to open `default':
alsa: Reason: No such file or directory
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM default
alsa: Could not initialize DAC
alsa: Failed to open `default':
alsa: Reason: No such file or directory
audio: Failed to create voice `dac'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM default
alsa: Could not initialize ADC
alsa: Failed to open `default':
alsa: Reason: No such file or directory
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM default
alsa: Could not initialize ADC
alsa: Failed to open `default':
alsa: Reason: No such file or directory
audio: Failed to create voice `adc'
gtk initialization failed


I ran under sudo and normal rights.  Any ideas why the container will not start?  ALSA is complaining there is no sound device but I don't think that's a problem.  I also have no /home/aarch directory.  Is the container installation suppose to build that?  Is it a rights issue?  Should the processor be changed in the qemu command from Penryn to something else for the AMD Ryzen V1500B?

Thanks you,

Dems1984

**Comment by Dems1984** [comment]
Thanks to Dulat at SickCodes Discord chat...  Since the NAS has no physical monitor/display attached, it failed to open the container and keep it running.  Dulat directed me to the ReadMe.md on the docker-osx and to look at the  -vnc option.  I removed the display (none) and added the -vnc option to the qemu and was able to get the container to startup, run, and stay runing.  Dulat also mentioned xhost+ as the problem/solution.  Not sure 100% what that is so can't really comment.  xhost has something to do with display in Unix/Linux.  Just commenting for those who might know more and understand what to do with that.  The 'gtk failed initialization' has to do with a failure of the container not being able to start up/redirect video output to the physical monitor/display.  Using the -vnc option allowed the work around and directed display to vnc.  I used the following Docker command via SSH and CLI, not Container Station:

docker run -i \
    --device /dev/kvm \
    -p 50922:10022 \
    -p 5999:5999 \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    -e EXTRA="-display none -vnc 0.0.0.0:99" \
    sickcodes/docker-osx:high-sierra

Be aware the vnc connection in this example is without password protection.  See ReadMe.md for details on how to add that to the VNC connection.

**Comment by deten** [comment]
I am working on this on Synology.  My issue is the following error: Bind mount failed: '/tmp/.X11-unix' does not exists

Did you have this too?
