### ISSUE TITLE
Can't boot to macOS after installation.

### ISSUE THREAD

**Issue by JCionx** [sickcodes/Docker-OSX#623]
Today I installed macOS using Docker-OSX on my laptop. It took around 8 hours to install. After the installation, I decided to shut down the VM. Then I launched Docker-OSX again, but it only showed up the recovery drive. How can I fix this?

**Comment by sdekna** [comment]
did you happen to solve it? I'm stuck at the same point

**Comment by JCionx** [comment]
> did you happen to solve it? I'm stuck at the same point

I solved it. You need to run "docker ps", ans that will list all your containers. Then you find the id of the docker-osx. Then run "docker start <id>"

**Comment by sdekna** [comment]
many thanks !
