### ISSUE TITLE
Rebuilding and repushing Docker-OSX to get the new OSX-KVM updates

### ISSUE THREAD

**Issue by jviotti** [sickcodes/Docker-OSX#63]
Hey there! 

I recently sent a PR to OSX-KVM (https://github.com/kholia/OSX-KVM/pull/135) to add a new OpenCore image in `OpenCore-Catalina` directory. I plan to use this on a base image that extends `sickcodes/docker-osx` to boot into the VM in headless mode.

Would you mind re-building and re-pushing `sickcodes/docker-osx` to Dockerhub (so that https://github.com/sickcodes/Docker-OSX/blob/master/Dockerfile#L115 clones the latest OSX-KVM version) so that we can start using this new OpenCore image?

Thanks a lot!

**Comment by sickcodes** [comment]
Let me take a look now!

**Comment by sickcodes** [comment]
Building as we speak!

**Comment by sickcodes** [comment]
Let's keep it open to make sure it's all good :)

**Comment by jviotti** [comment]
Thanks for the quick response. Trying it out now...

**Comment by jviotti** [comment]
The updates are there. Thanks a lot!
