### ISSUE TITLE
Display Problem on Ventura

### ISSUE THREAD

**Issue by rubidev68** [sickcodes/Docker-OSX#647]
Hello,
I have a display problem on all the official apple apps on Ventura on Docker.
For example, on safari, whatever website you are looking for he's displayed briefly before disappearing.
I noticed that when I remove the focus from the window, the website is then visible.

Any idea to solve the problem?

Thanks

**Comment by jailsonpaca** [comment]
up

**Comment by clockdev** [comment]
Noticed this problem too. It didn't happen a couple of weeks ago, though.

**Comment by oacs** [comment]
same issue here, I installed firefox with homebrew and it didn't had the same issue, this is also happening for the app store when you try to create a new account to sign in

**Comment by programmrz** [comment]
same issue here

**Comment by JoaoAlem** [comment]
Hello!
i'm new to here, but i realizing tests in my local machine and having the same problem.
Try using the Safari Technology Preview, it worked for me.

https://developer.apple.com/safari/technology-preview/

**Comment by mbilalbenli** [comment]
did someone solve this?

**Comment by lggdev7** [comment]
Update safari in settings.

**Comment by vnphanquang** [comment]
> Update safari in settings.

This fixed it for me. Here are the steps I took:

- go to `System Settings \ Software Update`,
- scroll down and click on additional updates (or something worded similar),
- Choose the safari update.

**Comment by continue-revolution** [comment]
can confirm that the solution is as simple as just updating safari
