### ISSUE TITLE
Ventura is not booting on my Ryzen CPU

### ISSUE THREAD

**Issue by Kibi1984** [sickcodes/Docker-OSX#649]
Hello,

i have a laptop with a ryzen CPU.
When i run this command it always ends in the recovery mode.

docker run -it \
    --device /dev/kvm \
    -p 50922:10022 \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    -e GENERATE_UNIQUE=true \
    -e MASTER_PLIST_URL='https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom.plist' \
    sickcodes/docker-osx:ventura

When i install MacOS Big Sur and try to update to Ventura nothing happen.
It looks like ventura will be installed but after the installation it boots again in MacOS Big Sur.

For me looks like is not possible to run Ventura on an AMD CPU.

Or have someone a running Ventura on an AMD CPU?

**Comment by Kibi1984** [comment]
Hello again,

i tried the installation of MacOS Ventura many times again on my AMD Ryzen Laptop.
The installation always need the whole night.
But finally it works. :)
Im very happy.

Thank you all for this great project.

**Comment by yogawa** [comment]
@Kibi1984 Hi, can you share tour tricks?
I tried to install venture on AMD ryzen laptop too and never finished

![image_2023-05-08_09-13-06](https://user-images.githubusercontent.com/1804598/236720814-e2b3b359-08ba-49ca-a721-f3f3142dd231.png)
