### ISSUE TITLE
Docker: Unknown Server OS

### ISSUE THREAD

**Issue by vm-hacker** [sickcodes/Docker-OSX#650]
I saw this error, when I ran the ventura command given in the README
docker: unknown server OS: .
See 'docker run --help'.

docker run -it \
    --device /dev/kvm \
    -p 50922:10022 \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    -e GENERATE_UNIQUE=true \
    -e MASTER_PLIST_URL='https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom.plist' \
    sickcodes/docker-osx:ventura

# docker build -t docker-osx --build-arg SHORTNAME=ventura .

This is occuring across all linux distros I tried

**Comment by h113331pp** [comment]
This is probably your docker daemon is not running.
For fast check, open another terminal and run **dockerd** then try again.

**Comment by vm-hacker** [comment]
root        1155  0.0  0.2 1742976 64796 ?       Ssl  06:55   0:01 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
brain      12665  0.0  0.0  11740  2704 pts/2    S+   10:21   0:00 grep --color=auto dockerd

**Comment by vm-hacker** [comment]
systemctl status docker returns

● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2023-04-17 06:55:29 +0530; 3h 26min ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
   Main PID: 1155 (dockerd)
      Tasks: 14
     Memory: 103.7M
        CPU: 1.412s
     CGroup: /system.slice/docker.service
             └─1155 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock

**Comment by h113331pp** [comment]
OK, It seems the docker daemon is running well.
Did you also setup your user account is in the group docker?
https://docs.docker.com/engine/install/linux-postinstall/

Or you just use "sudo" everytime when call "docker run -it ..."?

**Comment by sonicdevo** [comment]
I, too and running into the same error with the same troubleshooting results.

**Comment by sickcodes** [comment]
Is this snap docker on Ubuntu?

**Comment by vm-hacker** [comment]
It's not the snap, it's the docker.io package

**Comment by vm-hacker** [comment]
I found a solution, sorry I just ignored the step of creating a docker user group and then logging out
https://docs.docker.com/engine/install/linux-postinstall/
