### ISSUE TITLE
unable to login to Monterey using SSH

### ISSUE THREAD

**Issue by XoneTan** [sickcodes/Docker-OSX#653]
i have already turn on remote sharing in my monterey like so:
![image](https://user-images.githubusercontent.com/80412385/234200899-e43db43b-243c-42b5-be71-08fa6fdeb218.png)

but i still can't connect to my monterey, using my monterey password, i also tested 'alpine', my apple account password, and my host password, and try the same think in my visual studio code 
![image](https://user-images.githubusercontent.com/80412385/234201521-7c603bf8-234a-42bc-a7d9-2055b6eeec90.png)

is there any step there i'm missing to anable ssh, or is it only happen in monterey? (i have not try it in any other version)

edit:

my host os is gnome-Manjaro

this is how i run my docker
`docker run -it \
    --device /dev/kvm \
    -p 50922:10022 \
    -v "${PWD}/mac_hdd_ng.img:/image" \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    -e MASTER_PLIST_URL=https://raw.githubusercontent.com/sickcodes/Docker-OSX/master/custom/config-nopicker-custom.plist \
    sickcodes/docker-osx:naked`

**Comment by NandoLopes** [comment]
I'm also having the same problem, but with Catalina.
Now I'm trying to run the Venture image to see if I get anything different, since on the Catalina I was stuck on the SSH loop (on Docker's console)

Still searching for some issue related to this, but couldn't find anything by now.

**Comment by PTAHume** [comment]
try using the ip address for the wsl and your machine name ( you can get this from network settings) example:

ssh -p 50922 mymachinename@172.31.114.144

failing that recreate the mac image but use port 22 as that is the default for ssh and then try:

ssh -p 22 mymachinename@172.31.114.144
or 
ssh -p 22 user@localhost

**Comment by sickcodes** [comment]
your username is `wirandywira@`, you're trying `user@`

**Comment by XoneTan** [comment]
> your username is `wirandywira@`, you're trying `user@`

thank you this work. i didn't know that you are supposed to use the machine name. because i try `ssh wirandywira@10.0.2.15' just like how i used to do with macOS in VMware, but it was flat out can't connect to the ssh. when i try connecting with user@localhost, it connect and ask for the password, just like how VMware i used to do, so i just thought that is how the qemu tunnel the ssh.
