### ISSUE TITLE
Automatically select boot disk

### ISSUE THREAD

**Issue by brappier** [sickcodes/Docker-OSX#689]
![image](https://github.com/sickcodes/Docker-OSX/assets/126301759/78efab11-01f4-4d62-b4de-ca10bc156d37)

I want to automate the booting, right now i have to select the disk, else it does not boot.

**Comment by Johannp02180** [comment]
You can set "-e NOPICKER=true" to autoboot

**Comment by brappier** [comment]
ahh okay
