### ISSUE TITLE
Issues booting into mac and mac installer

### ISSUE THREAD

**Issue by Fhasaj** [sickcodes/Docker-OSX#690]
Hi all, 

i have been trying for a few weeks now to try and sort out the issue before i ask here but I am am having a slight issue when trying to load / setup osx (all of them). 

I am getting an issue when I run the docker container and QEMU loads it fails on the boot and shows me the images below. It was working fine about two weeks ago and now nothing. 

here is the continence of the command the following commands 

uname -a \       
; echo "${DISPLAY}" \
; echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs \
; grep NAME /etc/os-release \
; df -h . \
; qemu-system-x86_64 --version \
; libvirtd --version \
; free -mh \
; nproc \
; egrep -c '(svm|vmx)' /proc/cpuinfo \
; ls -lha /dev/kvm \
; ls -lha /tmp/.X11-unix/ \
; ps aux | grep dockerd \
; docker ps | grep osx \
; grep "docker\|kvm\|virt" /etc/group
Linux fatlum-Manjaro 6.4.9-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Aug  9 08:32:12 UTC 2023 x86_64 GNU/Linux
:0

1

NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p2  458G  246G  189G  57% /
QEMU emulator version 8.0.3
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers
libvirtd (libvirt) 9.6.0
free: Multiple unit options don't make sense.
12
egrep: warning: egrep is obsolescent; using grep -E
12
crw-rw-rw- 1 root kvm 10, 232 Aug 24 15:45 /dev/kvm
total 0
drwxrwxrwt  2 root root  60 Aug 24 15:19 .
drwxrwxrwt 16 root root 480 Aug 24 15:45 ..
srwxrwxrwx  1 root root   0 Aug 24 15:19 X0
root         674  0.1  0.4 2354504 112492 ?      Ssl  15:19   0:01 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
fhasa       8432  0.0  0.0   6984  2560 pts/2    S+   15:46   0:00 grep dockerd
kvm:x:992:libvirt-qemu,qemu,fhasa
libvirt:x:961:fhasa
libvirt-qemu:x:960:
docker:x:958:fhasa
libvirtdbus:x:953:

as well as a screenshot of the issue. 

![Screenshot_20230824_154537](https://github.com/sickcodes/Docker-OSX/assets/11924807/46d24cd9-1194-4f7b-bbf2-5ab390d75c02)

Thank you all

**Comment by luizribeiro** [comment]
It’s likely this is the same issue as #686.

**Comment by Fhasaj** [comment]
Thank you sir,

From reading the thread it looks like I need to update My bios and role back my Linux kernel version. Appreciate the help.

**Comment by Fhasaj** [comment]
Also as an update to before If you are having an issue I found that 5.4.252-1 on manjaro is working for me
