### ISSUE TITLE
How to use VNC after setting up container?

### ISSUE THREAD

**Issue by EndCod3r** [sickcodes/Docker-OSX#701]
I can't figure out how to use VNC with an already setup container.

I already setup the container and reinstalling macOS on it and change some settings on macOS but now I want to use VNC but I can't figure out how to.

**Comment by hendkai** [comment]
For example i start this:
`docker run -i     --device /dev/kvm     -p 50922:10022     -p 5999:5999     -v /tmp/.X11-unix:/tmp/.X11-unix     -e "DISPLAY=${DISPLAY:-:0.0}"     -e EXTRA="-display none -vnc 0.0.0.0:99,password=on"     sickcodes/docker-osx:big-sur`
Then i have wait until its bootet. At some point it seems to stop. Hit enter then. Then u see (qemu) in the terminal. Insert `change vnc password` and you will be asked for the vnc password. Then use tightvnc or guacamole vnc or whatever vnc client u want and connect to the macOSx. Be carefull this is not the encrypted version.

**Comment by EndCod3r** [comment]
@hendkai, I'm already made the Docker container using
``docker run -it \
    --device /dev/kvm \
    -p 50922:10022 \
	-v /mnt/wslg/.X11-unix:/tmp/.X11-unix \
	-e "DISPLAY=${DISPLAY:-:0}" \
    -e GENERATE_UNIQUE=true \
    -e MASTER_PLIST_URL='https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom.plist' \
    sickcodes/docker-osx:monterey``

If I run the command you gave me it makes a new Docker container. I want to know how to use VNC on an already created container.

**Comment by hendkai** [comment]
Then you need your docker container id. If u have it, start that containter with `docker start -ai yourdockercontainerid`.
What i did i started the container and listed the id with `docker container ls` if dont know it.
