### ISSUE TITLE
Support for Sonoma

### ISSUE THREAD

**Issue by dmelo** [sickcodes/Docker-OSX#711]
Does anybody knows when/if it'll be possible to have support for Sonoma?

**Comment by sohamksuvarna** [comment]
i don't think the docker image is released yet, but i installed monterey recently and got a sonoma update, so maybe you can try that
![image](https://github.com/sickcodes/Docker-OSX/assets/61341723/bb3ea1c3-fca3-4fdc-84fe-132348c03cd6)

**Comment by dmelo** [comment]
Did it work? Because I have the option to update on Ventura. It downloads the updates, but breaks at some point.

**Comment by waseem852** [comment]
I think this is related to this ? #715

**Comment by dmelo** [comment]
Sonoma is now supported :partying_face:
