### ISSUE TITLE
Is there a way to increase RAM and cores after container is created?

### ISSUE THREAD

**Issue by CrotchBurnt** [sickcodes/Docker-OSX#726]

**Comment by cbongard90** [comment]
You can try the solution below:
[https://github.com/sickcodes/Docker-OSX/issues/500#issuecomment-1429066474](url)

1. `docker export `your image as `xxx.tar`
2. `docker load` your `xxx.tar`
3. `docker run` with updated resources allocation

**Comment by CrotchBurnt** [comment]
See in discussions [#199](https://github.com/sickcodes/Docker-OSX/discussions/199)
