### ISSUE TITLE
Xcode can't run simulator due to docker not allowing more than "3.91gb" of RAM

### ISSUE THREAD

**Issue by SaintCodak** [sickcodes/Docker-OSX#737]
Ive tried to run multiple containers of ventura and download xcode. it seems to work, but even if I specify how much RAM I want upon creation, the OS never has more than 4, which is needed for xcode simulation. I found a closed issue relating, but it didn't help and is old. What am I doing wrong?

Im on Linux Mint, pretty fresh install. I know docker is native and should have access to all RAM, but Xcode doesn't see that maybe? Has anyone been successful here?

**Comment by QuentinSc** [comment]
what was the solution ?

**Comment by cesarsicas** [comment]
Same here, any update? 

I already increased the container memory on docker to 12GB but nothing changed. Is it possible to make the  SO recognize the new available memory or bypass this problem ?

![Captura de tela 2024-06-04 152251](https://github.com/sickcodes/Docker-OSX/assets/7783112/27f26368-bf69-42fe-8d42-7930c0ed7d4f)

**Comment by pipikui** [comment]
Same,has been solved?

**Comment by claudioscheer** [comment]
@skon-L @QuentinSc https://github.com/sickcodes/Docker-OSX/issues/622#issuecomment-1936503355
