### ISSUE TITLE
Increase RAM of existing container

### ISSUE THREAD

**Issue by dmbr0** [sickcodes/Docker-OSX#764]
I am trying to increase the ram of an existing container. I have tried this from another post:

docker update --memoryswap=8g --memory=8g containerID

but it returns:

unknown flag: --memoryswap
See 'docker update --help'.

does anyone know a way to do this?

**Comment by dmbr0** [comment]
Edit launch.sh

docker update --memory=8g  --memoryswap=8g containerID

**Comment by iclouden** [comment]
`--memory-swap`

**Comment by GustavoFigueira** [comment]
> Edit launch.sh and change RAM
> 
> docker update --memory=8g --memoryswap=8g containerID

Hi! Sorry, I'm not that familiar with Docker... Where can I find this file to change the settings of an existing container?
