### ISSUE TITLE
[FEATURE] Run multiple Screen

### ISSUE THREAD

**Issue by qlaffont** [sickcodes/Docker-OSX#78]
Hello,
I want to have two screens inside this VM. Is it possible ? If yes, how i can do this ?
Thanks !

**Comment by sickcodes** [comment]
I really don't know, you can run two machines though... maybe screen share port

**Comment by chris231989** [comment]
https://www.google.com/url?sa=t&source=web&rct=j&url=https://hub.docker.com/r/oaklabs/app-multi-display&ved=2ahUKEwizgtbPu_zrAhVPOKwKHUAHCQUQFjAAegQIARAB&usg=AOvVaw1h47Uj6-q3mgdCDAuD7PEw

This might help
