### ISSUE TITLE
Publish to App Store

### ISSUE THREAD

**Issue by neves** [sickcodes/Docker-OSX#8]
Can I use it to build my app with Xcode and publish to App Store?

**Comment by albatrossturkey1** [comment]
Yes Xcode
App signing
Transporter
Keychain etc

Everything except for usb mounting of an iPhone (might work on it soon, help appreciated)

**Comment by sickcodes** [comment]
Yes you can. Download Xcode from the App Store and run as normal.

Just make sure you have enough disk space because the application alone is 15GB or so!

**Comment by amreniouinnovent** [comment]
@sickcodes Could I run this docker on windows?
