### ISSUE TITLE
Docker build error.

### ISSUE THREAD

**Issue by kushhh01** [sickcodes/Docker-OSX#828]
I am using Ubuntu on WSL2, I have docker installed on my host and inside my Ubuntu as well. But when I am trying to build the docker container/image, I am getting the following error.

**ERROR: failed to solve: process "/bin/bash -c make     && qemu-img convert BaseSystem.dmg -O qcow2 -p -c BaseSystem.img     && rm ./BaseSystem.dmg" did not complete successfully: exit code: 2**

![image](https://github.com/user-attachments/assets/49048aa7-1ddb-4ac5-abdc-faac4c534088)

**Comment by dmrusanov** [comment]
Same on native ubuntu 22 and 24

**Comment by dmrusanov** [comment]
I guess problem in 
http://oscdn.apple.com/content/downloads/11/58/062-53943/of12aseueo2jnehp03qh5g3o17lx4139t1/RecoveryImage/BaseSystem.chunklist
getting 403

**Comment by sickcodes** [comment]
Upstream fix here, waiting for merge via @kholia https://github.com/kholia/OSX-KVM/pull/249

**Comment by fddn** [comment]
> Upstream fix here, waiting for merge via @kholia [kholia/OSX-KVM#249](https://github.com/kholia/OSX-KVM/pull/249)

It was merged about half an hour ago

**Comment by kushhh01** [comment]
Thanks 💯 @sickcodes
