### ISSUE TITLE
[Question] Automated ci/cd pipeline with no display?

### ISSUE THREAD

**Issue by xRiot** [sickcodes/Docker-OSX#83]
Is there any way to build/perform a full installation of the container with no display to make it fully automated?

Thanks in advance for any help with this.

**Comment by sickcodes** [comment]
Yes, using the VNC version.

@jviotti knows how to setup the auto boot to correct disk, I'm not sure how.

You can write a an xdotool script to format the disk first too or can use hfsprogs to make the disks

**Comment by jviotti** [comment]
@sickcodes @xRiot The trick is to create a custom OpenCore image (https://github.com/kholia/OSX-KVM/blob/master/OpenCore-Catalina/OpenCore.qcow2) that boots in the way you want it to boot. Docker-OSX loads this image here: https://github.com/sickcodes/Docker-OSX/blob/master/Dockerfile#L156-L157

```
    && tee -a Launch.sh <<< '-drive id=OpenCoreBoot,if=none,snapshot=on,format=qcow2,file=/home/arch/OSX-KVM/OpenCore-Catalina/OpenCore.qcow2 \' \
    && tee -a Launch.sh <<< '-device ide-hd,bus=sata.2,drive=OpenCoreBoot \' \
```

You can tweak OpenCore's `config.plist` (https://github.com/kholia/OSX-KVM/blob/master/OpenCore-Catalina/config.plist) and re-build it using this script: https://github.com/kholia/OSX-KVM/blob/master/OpenCore-Catalina/opencore-image-ng.sh.

These are some of the settings you might be interested in: https://github.com/kholia/OSX-KVM/blob/master/OpenCore-Catalina/config.plist#L520-L529

```
			<key>PickerMode</key>
			<string>External</string>
			<key>PollAppleHotKeys</key>
			<true/>
			<key>ShowPicker</key>
			<true/>
			<key>TakeoffDelay</key>
			<integer>0</integer>
			<key>Timeout</key>
			<integer>0</integer>
```

You can find the docs here: https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf

**Comment by xRiot** [comment]
Thanks a lot for the information @jviotti @sickcodes!

I can see that there's a display being exported in the VNC version. Would it be possible to entirely drop rendering of the desktop to save resources? I'm looking into only using SSH to access the container post installation.

**Comment by sickcodes** [comment]
Maybe try booting into the recovery disk, it has a terminal, I haven't tried automating it tho.

**Comment by sickcodes** [comment]
@jviotti Thanks for uploading that mate! I will add that second auto-booter next week unless someone wants to do a PR 😛

**Comment by xRiot** [comment]
Thanks for the insights @sickcodes!

At the moment the VNC container boots into boot disk selection menu, is there a way to automatically boot into the (predefined/right) disk?

**Comment by sickcodes** [comment]
Yes there is, @jviotti just explained above that you need to build a custom OpenCore qcow boot disk.

**Comment by JB-CHAUVIN** [comment]
Hello @sickcodes, have you released the auto-booter option yet? 
Thanks @jviotti for the tips !!

**Comment by sickcodes** [comment]
I think this is it:


https://github.com/kholia/OSX-KVM/blob/master/OpenCore-Catalina/OpenCore-nopicker.qcow2

Will have a look later this week

**Comment by JB-CHAUVIN** [comment]
> I think this is it:
> 
> https://github.com/kholia/OSX-KVM/blob/master/OpenCore-Catalina/OpenCore-nopicker.qcow2
> 
> Will have a look later this week

This is working ! It would be great if you add an option to choose the OpenCore version :)

**Comment by sickcodes** [comment]
Sure, unless someone would like to submit a PR:

`docker exec id sed -i -e opencore.qcow` to the new version

**Comment by sickcodes** [comment]
Done! https://github.com/sickcodes/Docker-OSX/commit/81682df5febf936cbadd889b8ec46c73b8d1466e

**Comment by sickcodes** [comment]
Will work in both VNC and regular containers btw

**Comment by AdamMomen** [comment]
Thanks for your amazing efforts @sickcodes, I am running this on a VM on the cloud and wanted to make it boot autmatically, so I tried these two commands but did not work yet!
 ```bash
# find you containerID
docker ps
# move the no picker script on top of the Launch script
# NEW CONTAINERS
docker exec containerID mv ./Launch-nopicker.sh ./Launch.sh
# LEGACY CONTAINERS
docker exec containerID bash -c "grep -v InstallMedia ./Launch.sh > ./Launch-nopicker.sh
chmod +x ./Launch-nopicker.sh
sed -i -e s/OpenCore\.qcow2/OpenCore\-nopicker\.qcow2/ ./Launch-nopicker.sh
"
```
![2020-11-06-09-38-29](https://user-images.githubusercontent.com/55929982/98345251-b438fb00-2014-11eb-8e56-b47ed7573394.gif)

**Comment by sickcodes** [comment]
Added in https://github.com/sickcodes/Docker-OSX/commit/a09c565e36d45f6663567b7c4f1402279e725519

See https://github.com/sickcodes/Docker-OSX#quick-start-175gb-pre-made-image
