### ISSUE TITLE
Not Working anymore

### ISSUE THREAD

**Issue by clearclown** [sickcodes/Docker-OSX#833]
# Not Working anymore

**Comment by ArcCal** [comment]
docker pull sickcodes/docker-osx:latest
Error response from daemon: pull access denied for sickcodes/docker-osx, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by ArcCal** [comment]
DMCAed by Apple？

**Comment by SirMorfield** [comment]
Looks like it

**Comment by clearclown** [comment]
yeah.seems like it

**Comment by ThaDaVos** [comment]
It made be taken down from docker hub - but you've got the source, so you could probably build it yourself (haven't looked at it yet)

**Comment by hello112334** [comment]
#799 Docker Image disappeared

**Comment by jackbillstrom** [comment]
I found https://hub.docker.com/r/dickhub/docker-osx/tags

So simply replacing `sickcodes` with `dickhub` did the trick for me.

**Comment by praisesunsei** [comment]
why

**Comment by clearclown** [comment]
# solved : 


bro u r right!

change `sickcodes` --> `dickhub`

```sh
docker run -it \
    --device /dev/kvm \
    -p 50922:10022 \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    -e GENERATE_UNIQUE=true \
    -e CPU='Haswell-noTSX' \
    -e CPUID_FLAGS='kvm=on,vendor=GenuineIntel,+invtsc,vmware-cpuid-freq=on' \
    -e MASTER_PLIST_URL='https://raw.githubusercontent.com/dickhub/osx-serial-generator/master/config-custom-sonoma.plist' \
    -e SHORTNAME=sonoma \
    dickhub/docker-osx:latest

# docker build -t docker-osx .
```

**Comment by lightspect** [comment]
> # solved :
> bro u r right!
> 
> change `sickcodes` --> `dickhub`
> 
> docker run -it \
>     --device /dev/kvm \
>     -p 50922:10022 \
>     -v /tmp/.X11-unix:/tmp/.X11-unix \
>     -e "DISPLAY=${DISPLAY:-:0.0}" \
>     -e GENERATE_UNIQUE=true \
>     -e CPU='Haswell-noTSX' \
>     -e CPUID_FLAGS='kvm=on,vendor=GenuineIntel,+invtsc,vmware-cpuid-freq=on' \
>     -e MASTER_PLIST_URL='https://raw.githubusercontent.com/dickhub/osx-serial-generator/master/config-custom-sonoma.plist' \
>     -e SHORTNAME=sonoma \
>     dickhub/docker-osx:latest
> 
> # docker build -t docker-osx .

I tried  this but got 
`curl: (3) URL rejected: Port number was not a decimal number between 0 and 65535`
