### ISSUE TITLE
Network speed issue for VM

### ISSUE THREAD

**Issue by xyuan240** [sickcodes/Docker-OSX#88]
Thanks for creatting this project, and I managed to install & run the Mac OS VM in a Ubuntu host.

However, I noticed that the VM network speed is much worse than the host's. (Note, I noticed it by remote connecting to my office machine from the host and guest systems, and I noticed there is quite a difference between them).

I did a bit search and I noticed some people experienced similar issues, and a possible solution is to apply Virtio (http://www.linux-kvm.org/page/Virtio). So my question is that are you aware this issue? And how do I possibly apply Virtio with your image? 

Thanks for you attention and any help will be much appreciated!

**Comment by MrBenFTW** [comment]
Weird, I’m getting about 8Gbps on speedtest.net and fast.com (my server has a 10Gbps symmetrical fibre connection)

**Comment by sickcodes** [comment]
@MrBenFTW feel free to enlighten us how to boost net speeds :)

**Comment by MrBenFTW** [comment]
lol, no idea but here is the result just ran it https://www.speedtest.net/result/c/f6f862d5-b8ae-4c81-b644-c1f2d7ed20a6

**Comment by sickcodes** [comment]
Bridged networking or user mode?

Any changes to the qemu arguments?

And VNC only yeah?

@MrBenFTW 

Thanks for showing us that pic btw, that is F A S T lmao

**Comment by MrBenFTW** [comment]
I think it is bridged but I am not 100% sure. Like I said, I use subnets with physical/public IPs and fancy routing

**Comment by weskerfoot** [comment]
I have been looking into this and it seems like MacOS doesn't support virtio for NIC unless you manage to get https://github.com/pmj/virtio-net-osx/ working (but it's out of date).

Apparently creating a bridge is better somehow, but I'm not 100% clear why

**Comment by sickcodes** [comment]
@weskerfoot  here are the two types of networking

I might add an environment flag to the Docker to allow people to choose between networking types today.

**Comment by sickcodes** [comment]
Fixed with https://github.com/sickcodes/Docker-OSX/pull/147
