### ISSUE TITLE
AWS EC2 support?

### ISSUE THREAD

**Issue by xRiot** [sickcodes/Docker-OSX#90]
Did anyone have any success with hosting the docker container in AWS EC2? As it turns out only `metal` instances offer nested virtualization according to a [old blog post from 2018](https://aws.amazon.com/blogs/compute/running-hyper-v-on-amazon-ec2-bare-metal-instances/). I personally tried `c5.xlarge` and `t3.medium` instances in `eu-west-1` using `Ubuntu Server 20.04 LTS (HVM)` official image with no luck:
```bash
INFO: Your CPU does not support KVM extensions
KVM acceleration can NOT be used
```

**Comment by xRiot** [comment]
Missed this completely: #68

**Comment by ajmalkhalil** [comment]
@xRiot @sickcodes  which specific version of EC2 supports this docker container hosting, please share?

**Comment by 1derfulLewis** [comment]
> @xRiot @sickcodes which specific version of EC2 supports this docker container hosting, please share?

I believe he answered this here - https://github.com/sickcodes/Docker-OSX/issues/68#issuecomment-672076461

I don't believe anything has changed.
