### ISSUE TITLE
Serve to browser?

### ISSUE THREAD

**Issue by CoreyVidal** [sickcodes/Docker-OSX#93]
I've only been using Docker (and Linux and command lines and coding in general) for the past year. Apologies if this question doesn't even make sense:

Is there a way to output the video of docker-osx so that it can be accessed and used from a browser? So I can install it on my local server (running Ubuntu and Docker), and then access it over IP / HTML from a browser on my local network?

**Comment by sickcodes** [comment]
Use the VNC version and connect using noVNC browser project https://github.com/novnc/noVNC

**Comment by CoreyVidal** [comment]
Amazing! Thank you.

**Comment by sickcodes** [comment]
@CoreyVidal if you want to contribute the code you used to get it working in noVNC feel free to create a PR :)

You could add to that Dockerfile in the VNC folder or post some of the code here.

Would be freakingggggg awesome to run docker-osx and just open up the browser 🚀

**Comment by CoreyVidal** [comment]
@sickcodes you overestimate my ability, but I will try, haha.

I prefer to use docker-compose. Is the VNC version able to run in docker-compose by implementing the few additional lines?

**Comment by sickcodes** [comment]
I'm not sure as I've never used docker compose but feel free to just paste some code here and we can get a PR up or I can edit it :)
