### ISSUE TITLE
[not issue] Reduce size container and make it lighter

### ISSUE THREAD

**Issue by stefanodecillis** [sickcodes/Docker-OSX#97]
Hello,

I have a question. Is it possible to reduce the disk usage of the container once it is created? 
If not, it would be good to many people to have a lighter version for CICD operations. How much is it the minimun disk space required to run macos? 
I'm planning to make a image i can use for compiling applications.

Thank you in advance and congrats because you made a great job with this image!

**Comment by MrBenFTW** [comment]
It's not possible to reduce the size once crated. However you can change the disk size during the build. I can't remember exactly but I think it's `--build-arg SIZE=64G` 

I've tried it with 64 GB and it works, Apple says the minimum is 12.5GB or 18.5 GB if you're doing an upgrade. 

So unless you're crazy I'd say go with 32GB as a bare minimum or 20GB as an insane minimum to ensure you have no issues.

**Comment by stefanodecillis** [comment]
Thank you for your help!
